#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

# ============ 08-from-react ============
swap("    ('08-from-react', '从 React 迁移', []),", r"""    ('08-from-react', '从 React 迁移', [
      ('H1','从 React 迁移'),
      ('P','如果你熟悉 React，这份文档帮你 30 分钟切换到 xunay。核心概念基本一一对应，但有几个关键区别。'),
      ('H2','API 对照速查'),
      ('Table',['React','XuNay','备注'],[
        ['useState(0)','signal(0)','读用 n() 不是 n'],
        ['setN(1)','n(1)','没有 set 前缀'],
        ['setN(v => v+1)','n(v => v+1)','一样'],
        ['useMemo(fn, deps)','computed(fn)','无依赖数组'],
        ['useEffect(fn, deps)','effect(fn)','无依赖数组'],
        ['useEffect(fn, [])','onMount(fn)','只挂载时跑'],
        ['useEffect(() => fn, [])','onUnmount(fn)','只卸载时跑'],
        ['useRef()','ref()','一样'],
        ['useContext','ctx()','更简单'],
        ['React.memo','不需要','自动精确更新'],
        ['useCallback','不需要','组件只跑一次'],
        ['createRoot().render()','mount()','更简单'],
        ['React.lazy','lazy()','一样'],
        ['<Suspense>','show(loading, ...)','手动控制'],
      ]),
      ('H2','第一个例子：计数器'),
      ('Code',"// ===== React =====\nfunction Counter() {\n  const [n, setN] = useState(0)\n  return (\n    <div>\n      <button onClick={() => setN(n - 1)}>-</button>\n      <span>{n}</span>\n      <button onClick={() => setN(n + 1)}>+</button>\n    </div>\n  )\n}\n\n// ===== XuNay =====\nfunction Counter() {\n  const n = signal(0)\n  return div(null,\n    button({ on: { click: () => n(v => v - 1) } }, '-'),\n    span(null, () => n()),\n    button({ on: { click: () => n(v => v + 1) } }, '+')\n  )\n}",'xuy'),
      ('H2','关键区别 1：读 signal 加 ()'),
      ('Code',"// React\n<span>{n}</span>\n\n// XuNay\nspan(null, () => n())\n//             ↑ 加 ()\n//      ↑ 加函数包",'xuy'),
      ('H2','关键区别 2：没有依赖数组'),
      ('Code',"// React：必须手动写依赖\nuseEffect(() => {\n  console.log(a, b)\n}, [a, b])   // 忘了写就是 bug\n\n// XuNay：自动收集\nеffect(() => {\n  console.log(a(), b())\n})   // 自动订阅 a、b",'xuy'),
      ('H2','关键区别 3：组件只执行一次'),
      ('Code',"// React：每次 count 变，整个组件重跑\nfunction List() {\n  const [items, setItems] = useState([])\n  console.log('渲染')   // 每次 items 变都打印\n  const total = items.reduce((s, i) => s + i.price, 0)   // 每次重算\n  return <div>{total}</div>\n}\n\n// XuNay：只跑一次\nfunction List() {\n  const items = signal([])\n  console.log('初始化')   // 只打印一次\n  const total = computed(() => items().reduce((s, i) => s + i.price, 0))\n  return div(null, () => total())\n}",'xuy'),
      ('H2','关键区别 4：不需要 useCallback / useMemo'),
      ('Code',"// React：怕重复创建，需要 memo\nconst handleClick = useCallback(() => {\n  setN(n => n + 1)\n}, [])\nconst total = useMemo(() => items.reduce(...), [items])\n\n// XuNay：想怎么建就怎么建\nconst handleClick = () => n(v => v + 1)\nconst total = computed(() => items().reduce(...))",'xuy'),
      ('H2','关键区别 5：没有 key'),
      ('Code',"// React\n{items.map(i => <li key={i.id}>{i.title}</li>)}\n\n// XuNay\nlist(items, i => i.id, i => li(null, i.title))\n//        ↑ key 函数",'xuy'),
      ('H2','useEffect 三种场景的替换'),
      ('H3','挂载时执行一次'),
      ('Code',"// React\nuseEffect(() => {\n  fetchData()\n}, [])\n\n// XuNay\nonMount(() => {\n  fetchData()\n})",'xuy'),
      ('H3','依赖变化时执行'),
      ('Code',"// React\nuseEffect(() => {\n  console.log(a, b)\n}, [a, b])\n\n// XuNay\neffect(() => {\n  console.log(a(), b())\n})",'xuy'),
      ('H3','挂载/卸载各执行一次'),
      ('Code',"// React\nuseEffect(() => {\n  const id = setInterval(tick, 1000)\n  return () => clearInterval(id)\n}, [])\n\n// XuNay\neffect(() => {\n  const id = setInterval(tick, 1000)\n  return () => clearInterval(id)\n})",'xuy'),
      ('H2','Context 对比'),
      ('Code',"// React\nconst ThemeCtx = createContext('light')\n\n<ThemeCtx.Provider value=\"dark\">\n  <Card />\n</ThemeCtx.Provider>\n\nfunction Card() {\n  const theme = useContext(ThemeCtx)\n}\n\n// XuNay\nconst ThemeCtx = ctx('light')\n\nThemeCtx.provide('dark', () => Card())\n\nfunction Card() {\n  const theme = ThemeCtx.get()\n}",'xuy'),
      ('H2','常见 React 模式的 XuNay 写法'),
      ('H3','受控输入'),
      ('Code',"// React\nconst [value, setValue] = useState('')\n<input value={value} onChange={e => setValue(e.target.value)} />\n\n// XuNay\nconst value = signal('')\ninput({ value: () => value(), on: { input: e => value(e.target.value) } })",'xuy'),
      ('H3','列表渲染'),
      ('Code',"// React\n<ul>\n  {todos.map(t => (\n    <li key={t.id} className={t.done ? 'done' : ''}>\n      <input type=\"checkbox\" checked={t.done} onChange={() => toggle(t.id)} />\n      {t.title}\n    </li>\n  ))}\n</ul>\n\n// XuNay\nul(null,\n  list(todos, t => t.id, t => li({ class: () => t.done ? 'done' : '' },\n    input({ type: 'checkbox', checked: () => t.done, on: { change: () => toggle(t.id) } }),\n    t.title\n  ))\n)",'xuy'),
      ('H3','条件渲染'),
      ('Code',"// React\n{loading ? <Spinner /> : <Content data={data} />}\n\n// XuNay\nshow(() => loading(), () => Spinner({}), () => Content({ data: data() }))\n// 或\n() => loading() ? Spinner({}) : Content({ data: data() })",'xuy'),
      ('H3','错误边界'),
      ('Code',"// React\nclass ErrorBoundary extends React.Component { ... }\n\n// XuNay\nerr(() => risky(), () => div(null, '出错了'))",'xuy'),
      ('H2','不需要的东西'),
      ('Ul',
        'useCallback / useMemo（组件只跑一次）',
        'React.memo（自动精确更新）',
        'useReducer（signal + 手写 reducer）',
        'Hooks 顺序规则（没有 hooks）',
        '依赖数组（自动收集）',
        'StrictMode（无双重渲染）',
        'Portals（直接操作 DOM）',
        'Fragments 的 <></> 语法（用 frag）'),
      ('H2','迁移清单'),
      ('Table',['步骤','操作'],[
        ['1','npm install xunay'],
        ['2','把 useState 换成 signal'],
        ['3','把 setN(x) 换成 n(x)'],
        ['4','把读值改成 n()'],
        ['5','把 useEffect 换成 effect / onMount'],
        ['6','把 useMemo 换成 computed'],
        ['7','把 .map 换成 list'],
        ['8','把 && / 三目换成 show'],
        ['9','删掉 useCallback / memo / useRef 包装'],
        ['10','把 <div>...</div> 换成 div(null, ...)'],
      ]),
      ('H2','迁移示例：Todo'),
      ('Code',"// ===== React 版本 =====\nfunction Todo() {\n  const [todos, setTodos] = useState([])\n  const [draft, setDraft] = useState('')\n  const add = () => {\n    setTodos([...todos, { id: Date.now(), title: draft }])\n    setDraft('')\n  }\n  const toggle = id => setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t))\n\n  return (\n    <div>\n      <input value={draft} onChange={e => setDraft(e.target.value)} />\n      <button onClick={add}>添加</button>\n      <ul>\n        {todos.map(t => (\n          <li key={t.id}>\n            <input type=\"checkbox\" checked={t.done} onChange={() => toggle(t.id)} />\n            {t.title}\n          </li>\n        ))}\n      </ul>\n    </div>\n  )\n}\n\n// ===== XuNay 版本 =====\nfunction Todo() {\n  const todos = signal([])\n  const draft = signal('')\n  const add = () => {\n    todos(list => [...list, { id: Date.now(), title: draft() }])\n    draft('')\n  }\n  const toggle = id => todos(list => list.map(t => t.id === id ? { ...t, done: !t.done } : t))\n\n  return div(null,\n    input({ value: () => draft(), on: { input: e => draft(e.target.value) } }),\n    button({ on: { click: add } }, '添加'),\n    ul(null,\n      list(todos, t => t.id, t => li(null,\n        input({ type: 'checkbox', checked: () => t.done, on: { change: () => toggle(t.id) } }),\n        t.title\n      ))\n    )\n  )\n}",'xuy'),
      ('H2','适应期常见错误'),
      ('H3','错误 1：忘了 ()'),
      ('Code',"// 错误：忘加 ()\ndiv(null, () => n)\n\n// 正确\ndiv(null, () => n())",'xuy'),
      ('H3','错误 2：直接传值而不是函数'),
      ('Code',"// 错误：立即求值\ndiv(null, n())\n\n// 正确\ndiv(null, () => n())",'xuy'),
      ('H3','错误 3：在 effect 里读又写'),
      ('Code',"// 错误：死循环\neffect(() => {\n  n(n() + 1)\n})\n\n// 正确：放事件回调\nbutton({ on: { click: () => n(v => v + 1) } })",'xuy'),
    ]),""", "08-from-react")

# ============ 09-from-vue ============
swap("    ('09-from-vue', '从 Vue 迁移', []),", r"""    ('09-from-vue', '从 Vue 迁移', [
      ('H1','从 Vue 迁移'),
      ('P','Vue 3 的 setup + Composition API 和 xunay 非常像——都是信号驱动，都精确更新。主要区别是模板语法。'),
      ('H2','API 对照速查'),
      ('Table',['Vue 3','XuNay','备注'],[
        ['ref(0)','signal(0)','读用 () 不是 .value'],
        ['n.value','n()','读'],
        ['n.value = 1','n(1)','写'],
        ['computed(fn)','computed(fn)','一样'],
        ['watch(fn)','effect(fn)','effect 自动追踪'],
        ['watchEffect(fn)','effect(fn)','完全一样'],
        ['onMounted(fn)','onMount(fn)','一样'],
        ['onUnmounted(fn)','onUnmount(fn)','一样'],
        ['provide/inject','ctx','更简单'],
        ['v-if','show','函数式'],
        ['v-for','list','函数式'],
        ['v-model','手写或 model()','函数式'],
        ['<template>','frag','函数式'],
      ]),
      ('H2','第一个例子：计数器'),
      ('Code',"<!-- Vue 3 -->\n<template>\n  <div>\n    <button @click=\"n--\">-</button>\n    <span>{{ n }}</span>\n    <button @click=\"n++\">+</button>\n  </div>\n</template>\n\n<script setup>\nimport { ref } from 'vue'\nconst n = ref(0)\n</script>\n\n// ===== XuNay =====\nimport { signal, div, button, span } from 'xunay'\n\nfunction Counter() {\n  const n = signal(0)\n  return div(null,\n    button({ on: { click: () => n(v => v - 1) } }, '-'),\n    span(null, () => n()),\n    button({ on: { click: () => n(v => v + 1) } }, '+')\n  )\n}",'xuy'),
      ('H2','关键区别 1：没有 .value'),
      ('Code',"// Vue 3\nconst n = ref(0)\nconsole.log(n.value)   // 读\nn.value = 1            // 写\n\n// XuNay\nconst n = signal(0)\nconsole.log(n())       // 读\nn(1)                   // 写",'xuy'),
      ('H2','关键区别 2：没有模板'),
      ('Code',"<!-- Vue 3 -->\n<ul>\n  <li v-for=\"t in todos\" :key=\"t.id\" :class=\"{ done: t.done }\">\n    {{ t.title }}\n  </li>\n</ul>\n\n// ===== XuNay =====\nul(null,\n  list(todos, t => t.id, t => li({ class: () => t.done ? 'done' : '' },\n    t.title\n  ))\n)",'xuy'),
      ('H2','关键区别 3：没有 ref 的 value'),
      ('Table',['','Vue 3','XuNay'],[
        ['定义','ref(0)','signal(0)'],
        ['读','n.value','n()'],
        ['写','n.value = 1','n(1)'],
        ['模板里自动解包','✓','手动 () =>'],
        ['computed 读','c.value','c()'],
      ]),
      ('H2','响应式原理对比'),
      ('Table',['','Vue 3','XuNay'],[
        ['方式','Proxy 拦截','手动追踪'],
        ['依赖收集','编译期 + 运行时','纯运行时'],
        ['更新粒度','组件 + 节点','节点'],
        ['嵌套对象','自动深层','需整体替换'],
        ['数组方法','patch 过','原生'],
      ]),
      ('H2','常见 Vue 模式的 XuNay 写法'),
      ('H3','ref 和 reactive'),
      ('Code',"// Vue\nconst n = ref(0)\nconst user = reactive({ name: 'x', age: 0 })\n\n// XuNay：只有 signal 一种\nconst n = signal(0)\nconst user = signal({ name: 'x', age: 0 })\n// 更新整个对象\nuser(u => ({ ...u, age: 18 }))",'xuy'),
      ('H3','watch'),
      ('Code',"// Vue\nwatch(n, (val, oldVal) => {\n  console.log('n 变:', val)\n})\n\n// XuNay\neffect(() => {\n  const val = n()\n  console.log('n 变:', val)\n})",'xuy'),
      ('H3','watchEffect'),
      ('Code',"// Vue\nwatchEffect(() => {\n  console.log(a.value, b.value)\n})\n\n// XuNay：完全一样\neffect(() => {\n  console.log(a(), b())\n})",'xuy'),
      ('H3','生命周期'),
      ('Code',"// Vue\nonMounted(() => { ... })\nonUnmounted(() => { ... })\n\n// XuNay：一样\nonMount(() => { ... })\nonUnmount(() => { ... })",'xuy'),
      ('H3','v-model'),
      ('Code',"// Vue\n<input v-model=\"name\" />\n\n// XuNay：手写\ninput({\n  value: () => name(),\n  on: { input: e => name(e.target.value) }\n})\n// 或封装\nfunction model(sig) {\n  return {\n    value: () => sig(),\n    on: { input: e => sig(e.target.value) }\n  }\n}\ninput({ ...model(name) })",'xuy'),
      ('H3','v-if / v-else / v-else-if'),
      ('Code',"// Vue\n<div v-if=\"status === 'loading'\">加载中</div>\n<div v-else-if=\"status === 'error'\">出错了</div>\n<div v-else>内容</div>\n\n// XuNay\n() => {\n  const s = status()\n  if (s === 'loading') return div(null, '加载中')\n  if (s === 'error') return div(null, '出错了')\n  return div(null, '内容')\n}",'xuy'),
      ('H3','v-for'),
      ('Code',"// Vue\n<li v-for=\"(t, i) in todos\" :key=\"t.id\">\n  {{ i }}. {{ t.title }}\n</li>\n\n// XuNay\nlist(todos, t => t.id, (t, i) => li(null, i + '. ' + t.title))",'xuy'),
      ('H3','v-show vs v-if'),
      ('Code',"// Vue：v-show 用 display 切换，v-if 挂载卸载\n<div v-show=\"open\">内容</div>\n<div v-if=\"open\">内容</div>\n\n// XuNay：show 类似 v-if（挂载卸载）\nshow(() => open(), () => div(null, '内容'))\n// v-show 效果用 style\n// div({ style: () => ({ display: open() ? 'block' : 'none' }) }, '内容')",'xuy'),
      ('H3','slots'),
      ('Code',"// Vue\n<Card>\n  <template #title>标题</template>\n  <p>正文</p>\n</Card>\n\n// XuNay：直接传 children / 函数\nCard({\n  title: () => h2(null, '标题'),\n  default: () => p(null, '正文')\n})\n// 或\nCard({}, h2(null, '标题'), p(null, '正文'))",'xuy'),
      ('H3','computed 的 getter/setter'),
      ('Code',"// Vue\nconst fullName = computed({\n  get: () => first.value + ' ' + last.value,\n  set: (v) => { [first.value, last.value] = v.split(' ') }\n})\n\n// XuNay：computed 只读，写用 signal\nconst fullName = computed(() => first() + ' ' + last())\n// 需要写时手动处理\nfunction setFullName(v) {\n  const [f, l] = v.split(' ')\n  batch(() => { first(f); last(l) })\n}",'xuy'),
      ('H2','provide / inject 对比'),
      ('Code',"// Vue\n// 祖先\nprovide('theme', ref('light'))\n// 后代\nconst theme = inject('theme')\n\n// XuNay\n// 定义\nconst ThemeCtx = ctx('light')\n// 祖先\nThemeCtx.provide(theme(), () => Child())\n// 后代\nconst theme = ThemeCtx.get()",'xuy'),
      ('H2','迁移示例：Todo'),
      ('Code',"<!-- Vue 3 版本 -->\n<script setup>\nimport { ref, computed } from 'vue'\nconst todos = ref([])\nconst filter = ref('all')\nconst filtered = computed(() => {\n  if (filter.value === 'active') return todos.value.filter(t => !t.done)\n  return todos.value\n})\nconst add = (title) => todos.value.push({ id: Date.now(), title, done: false })\n</script>\n\n<template>\n  <ul>\n    <li v-for=\"t in filtered\" :key=\"t.id\" :class=\"{ done: t.done }\">\n      <input type=\"checkbox\" v-model=\"t.done\" />\n      {{ t.title }}\n    </li>\n  </ul>\n</template>\n\n// ===== XuNay 版本 =====\nimport { signal, computed, ul, li, input, list } from 'xunay'\n\nfunction Todo() {\n  const todos = signal([])\n  const filter = signal('all')\n  const filtered = computed(() => {\n    if (filter() === 'active') return todos().filter(t => !t.done)\n    return todos()\n  })\n  const add = (title) => todos(list => [...list, { id: Date.now(), title, done: false }])\n\n  return ul(null,\n    list(filtered, t => t.id, t => li({ class: () => t.done ? 'done' : '' },\n      input({ type: 'checkbox', checked: () => t.done, on: { change: () => toggle(t.id) } }),\n      t.title\n    ))\n  )\n}",'xuy'),
      ('H2','Vue 的响应式陷阱 XuNay 没有'),
      ('Table',['陷阱','Vue 3','XuNay'],[
        ['ref 忘记 .value','常见','n() 也容易忘，但报错明确'],
        ['reactive 解构丢失响应','有','不存在'],
        ['数组索引修改不触发','有','数组整体替换'],
        ['新增属性不触发','有','对象整体替换'],
        ['shallowRef 性能优化','需要','默认就是浅比较'],
      ]),
      ('H2','迁移清单'),
      ('Table',['步骤','操作'],[
        ['1','npm install xunay'],
        ['2','把 .value 全部删掉'],
        ['3','把 ref(0) 换成 signal(0)'],
        ['4','把模板改成函数调用'],
        ['5','把 v-for 换成 list'],
        ['6','把 v-if 换成 show'],
        ['7','把 watchEffect 换成 effect'],
        ['8','把 onMounted 换成 onMount'],
        ['9','删掉 <template> / <script setup>'],
        ['10','用 .xuy 或直接写 JS'],
      ]),
    ]),""", "09-from-vue")

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("08 / 09 已填")
