#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

swap("    ('tool-devtools', 'DevTools 总览', []),", r"""    ('tool-devtools', 'DevTools 总览', [
      ('H1','DevTools 总览'),
      ('P','xunay 内置调试面板——右下角悬浮按钮，点击展开。不用装浏览器扩展。'),
      ('H2','启动'),
      ('Code',"import 'xunay/devtools'",'xuy'),
      ('P','页面加载后右下角出现悬浮按钮。点击打开面板。'),
      ('H2','四个面板'),
      ('Table',['面板','内容'],[
        ['网络','所有 fetch / XHR 请求 + 详情'],
        ['Signals','所有 signal 的值 + 写入历史'],
        ['控制台','log / warn / error + 输入 JS 执行'],
        ['性能','FCP / LCP / 请求分解 / 长任务'],
      ]),
      ('H2','按钮特性'),
      ('Ul',
        '可拖拽——按住拖到任意位置',
        '位置记忆——刷新后停在原位',
        '呼吸光晕——一眼能看见',
        '打开时变红，图标变 ×'),
      ('H2','面板特性'),
      ('Ul',
        '玻璃拟态——半透明磨砂',
        '响应式——手机自动底部抽屉',
        '过滤——输入框实时筛选',
        '复制——每个区块一键复制'),
      ('H2','打包控制'),
      ('P','在 package.json 里控制是否包含 devtools：'),
      ('Code',"{\n  \"xunay\": {\n    \"devtools\": true\n  }\n}",'json'),
      ('Table',['值','行为'],[
        ['true','打包并在页面显示'],
        ['false','完全剔除——产物无按钮代码']),
      ('H2','配置为 false 时'),
      ('P','构建产物里没有 devtools 相关代码——gzip 从 6.2KB 降到 4.7KB。'),
      ('H2','不打包也能用'),
      ('P','用 CDN 或手动引入：'),
      ('Code',"<script src=\"/xunay-devtools.js\"></script>\n<script>\n  window.openDevtools()\n</script>",'html'),
      ('H2','下一步'),
      ('Link','#tool-devtools-net','网络面板'),
      ('Link','#tool-devtools-sig','Signals 面板'),
    ]),""", "tool-devtools")

swap("    ('tool-devtools-net', '网络面板', []),", r"""    ('tool-devtools-net', '网络面板', [
      ('H1','网络面板'),
      ('P','显示所有 fetch / XHR 请求，能看请求头、响应头、请求体、响应体。'),
      ('H2','列表'),
      ('Code',"POST  200  /rpc/addTodo   14:32:05.123   342 B   18ms\nGET   200  /rpc/getTodos  14:32:05.100   2.4 KB  12ms\nGET   200  /rpc/token     14:32:04.988   76 B    8ms",'txt'),
      ('H2','列表列'),
      ('Table',['列','内容'],[
        ['方法','GET / POST / PUT / PATCH / DELETE / HEAD'],
        ['状态','HTTP 状态码（颜色区分）'],
        ['URL','路径（紫色）'],
        ['时间','毫秒级时间戳'],
        ['大小','响应体字节数'],
        ['耗时','请求到响应的时间']),
      ('H2','过滤'),
      ('P','顶部输入框，模糊匹配 URL / 方法 / 状态码：'),
      ('Code',"addTodo    → 只显示 URL 含 addTodo\nPOST       → 只显示 POST 请求\n200        → 只显示 200 状态\n/rpc/      → 只显示 rpc 接口",'txt'),
      ('H2','详情页'),
      ('P','点任一行进入详情页，6 个子 tab：'),
      ('Table',['Tab','内容'],[
        ['概览','方法、URL、状态、耗时、大小、类型、开始时间'],
        ['请求头','所有请求头（键值对）'],
        ['请求体','JSON 自动格式化'],
        ['响应头','所有响应头'],
        ['响应体','JSON 自动格式化（最多 16KB）'],
        ['时间','等待响应 + 下载内容分解']),
      ('H2','复制功能'),
      ('Table',['位置','复制什么'],[
        ['顶部大按钮','完整信息（头 + 体 + 时间）'],
        ['每个 tab 标题','该 tab 的原始数据']),
      ('H2','主动发请求'),
      ('P','网络面板顶部有请求构造器——不用切 Postman：'),
      ('Code',"方法: POST\nURL:  /rpc/addTodo\n请求体: {\"title\":\"test\"}\n\n点发送 → 自动进列表",'txt'),
      ('H2','状态码颜色'),
      ('Table',['范围','颜色'],[
        ['2xx','绿色'],
        ['3xx','黄色'],
        ['4xx','橙色'],
        ['5xx','红色'],
        ['进行中','灰色']),
    ]),""", "tool-devtools-net")

swap("    ('tool-devtools-sig', 'Signals 面板', []),", r"""    ('tool-devtools-sig', 'Signals 面板', [
      ('H1','Signals 面板'),
      ('P','显示所有 signal 的当前值、写入次数、订阅者数量。'),
      ('H2','列表'),
      ('Code',"#0   string   0w   4s   \"/\"\n#1   object   0w   3s   [{\"id\":1,\"title\":\"...\"]\n#2   string   1w   1s   \"all\"\n#4   object   1w   2s   {\"total\":2,...}",'txt'),
      ('H2','列含义'),
      ('Table',['列','含义'],[
        ['序号','#0 / #1 / ...'],
        ['类型','string / number / object / boolean'],
        ['写入次数','橙色 Xw，表示写了 X 次'],
        ['订阅者','灰色 Xs，表示有 X 个订阅者'],
        ['当前值','红色，超长截断']),
      ('H2','过滤'),
      ('Code',"object     → 只显示 object 类型\n\"all\"      → 值含 all 的\n#3         → 只看 #3\ntodo       → 值含 todo 的",'txt'),
      ('H2','复制全部'),
      ('P','顶部 📋 按钮——一键复制所有 signal 的 JSON 快照：'),
      ('Code',"[\n  { \"index\": 0, \"type\": \"string\", \"value\": \"/\", \"writes\": 0, \"subs\": 4 },\n  { \"index\": 1, \"type\": \"object\", \"value\": [...], \"writes\": 0, \"subs\": 3 }\n]",'json'),
      ('H2','详情页'),
      ('P','点任一行查看单条 signal 的完整信息：'),
      ('Ul',
        '头部：序号、类型、订阅者、写入、创建时间',
        '当前值（JSON 格式化）',
        '写入历史（最近 30 条，时间 + 旧值 → 新值）'),
      ('H2','写入历史'),
      ('Code',"10:31:05.234  \"all\" → \"active\"\n10:31:04.988  \"active\" → \"all\"\n10:31:03.512  \"\" → \"all\"",'txt'),
      ('H2','实战用法'),
      ('H3','找内存泄漏'),
      ('P','反复操作后看 signal 数量是否持续增长。'),
      ('H3','找性能瓶颈'),
      ('P','看某个 signal 的写入次数——如果一次点击写 100 次，说明有循环。'),
      ('H3','追踪状态变化'),
      ('P','详情页看写入历史，一眼看出什么时候变成什么值。'),
    ]),""", "tool-devtools-sig")

swap("    ('tool-devtools-console', '控制台', []),", r"""    ('tool-devtools-console', '控制台', [
      ('H1','控制台'),
      ('P','显示所有 console.log / warn / error，可以在页面里直接执行 JS。'),
      ('H2','捕获的日志'),
      ('Ul',
        'console.log —— 白色',
        'console.warn —— 黄色 + 左侧色条',
        'console.error —— 红色 + 左侧色条',
        'window.onerror —— 未捕获异常',
        'unhandledrejection —— Promise 拒绝'),
      ('H2','输入框'),
      ('P','顶部输入框——输入 JS 表达式，回车执行：'),
      ('Code',"> 1 + 2\n3\n\n> location.href\n\"http://example.com/\"\n\n> localStorage.getItem('token')\n\"abc123\"\n\n> window.__XD__.nets.length\n3",'txt'),
      ('H2','执行结果'),
      ('Ul',
        '原始表达式回显（带 > 前缀）',
        '结果美化：字符串原样，对象 JSON，函数显示 ƒ name'),
      ('H2','常见用途'),
      ('H3','调试 signal'),
      ('Code',"> window.__XUNAY_RUNTIME__\n\n> document.querySelector('#app').__xunay_scope",'js'),
      ('H3','读 localStorage'),
      ('Code',"> JSON.parse(localStorage.getItem('myapp-todos'))",'js'),
      ('H3','手动触发事件'),
      ('Code',"> document.querySelector('button').click()",'js'),
      ('H3','测试接口'),
      ('Code',"> fetch('/rpc/token').then(r => r.json()).then(console.log)",'js'),
      ('H2','清空'),
      ('P','顶栏 🗑 按钮清空所有日志。'),
      ('H2','详情页'),
      ('P','点任一条日志——进入详情页，有：'),
      ('Ul',
        '序号、时间、长度、级别',
        '完整内容',
        '一键复制'),
      ('H2','和浏览器控制台的区别'),
      ('Table',['','DevTools 控制台','浏览器控制台'],[
        ['在手机上','✓ 能用','✗ 难开'],
        ['历史保留','sessionStorage','仅当前页面'],
        ['可复制','一键','手动'],
        ['跨刷新','保留','清空']),
    ]),""", "tool-devtools-console")

swap("    ('tool-devtools-perf', '性能面板', []),", r"""    ('tool-devtools-perf', '性能面板', [
      ('H1','性能面板'),
      ('P','显示页面加载性能——FCP / LCP / 请求分解 / 长任务。'),
      ('H2','核心指标'),
      ('Table',['指标','含义','目标'],[
        ['FCP','首次内容绘制','< 1000ms'],
        ['LCP','最大内容绘制','< 2500ms'],
        ['DOM Ready','DOM 解析完成','< 1000ms'],
        ['Load','所有资源加载完','< 2000ms']),
      ('H2','请求分解'),
      ('P','把页面加载请求拆成各阶段：'),
      ('Code',"┌──────────────────────────────────────┐\n│ ██ ██ ████ ██████ ███               │\n└──────────────────────────────────────┘\nDNS  2ms      下载    12ms\nTCP  1ms      DOM解析 8ms\nTTFB 15ms",'txt'),
      ('H2','运行时'),
      ('Table',['指标','说明'],[
        ['JS 堆内存','当前用多少 / 上限'],
        ['DOM 节点数','页面元素数量'],
        ['资源数','加载的资源数量'],
        ['长任务数','超过 50ms 的阻塞任务']),
      ('H2','长任务列表'),
      ('P','超过 50ms 的 JS 执行：'),
      ('Code',"187ms 时刻 · 187ms\n512ms 时刻 · 76ms\n843ms 时刻 · 62ms",'txt'),
      ('P','>200ms 标红，>100ms 标黄。'),
      ('H2','复制 JSON'),
      ('P','顶部按钮一键复制完整快照：'),
      ('Code',"{\n  \"capturedAt\": \"2026-10-02T02:45:50.085Z\",\n  \"url\": \"http://...\",\n  \"core\": { \"fcp\": 2000, \"lcp\": 2348, \"domReady\": 1965, \"load\": 1989 },\n  \"stages\": { \"dns\": 1.3, \"tcp\": 366, \"ttfb\": 379, \"download\": 4.2, \"domParse\": 36.6 },\n  \"runtime\": { \"jsHeap\": 11200000, \"domNodes\": 124, \"resources\": 2 },\n  \"longTasks\": [{ \"start\": 6536, \"duration\": 57 }],\n  \"requests\": [...],\n  \"signals\": [...]\n}",'json'),
      ('H2','注意'),
      ('Warn','FCP / LCP 是页面加载时采集的。打开 devtools 后要刷新一次才能看到完整数据。'),
      ('H2','实战'),
      ('H3','页面慢'),
      ('P','看 FCP / LCP 具体多少。'),
      ('H3','卡顿'),
      ('P','看长任务列表——哪段时间卡了。'),
      ('H3','内存泄漏'),
      ('P','反复操作，看 JS 堆是否持续涨。'),
    ]),""", "tool-devtools-perf")

swap("    ('tool-scaffold', '脚手架', []),", r"""    ('tool-scaffold', '脚手架', [
      ('H1','脚手架'),
      ('P','bin/create.js 一键生成项目骨架。'),
      ('H2','使用'),
      ('Code',"node bin/create.js my-new-app",'bash'),
      ('H2','生成的结构'),
      ('Code',"my-new-app/\n├── app.xuy              入口\n├── index.html\n├── package.json\n├── src/\n│   ├── components/\n│   ├── pages/\n│   ├── store/\n│   └── style.css\n└── README.md",'txt'),
      ('H2','初始 app.xuy'),
      ('Code',"// title: my-new-app\nimport { div, h1, button, signal, mount } from 'xunay'\n\nconst n = signal(0)\n\nmount(() => div({ class: 'app' },\n  h1(null, 'Hello XuNay'),\n  button({ on: { click: () => n(v => v + 1) } }, () => '点了 ' + n() + ' 次')\n), '#app')",'xuy'),
      ('H2','启动'),
      ('Code',"cd my-new-app\nnpm install\nnpm run build\nnpm run dev",'bash'),
      ('H2','内置脚本'),
      ('Table',['命令','作用'],[
        ['npm run build','编译 .xuy → dist'],
        ['npm run dev','构建 + 起静态服务器'],
        ['npm run deploy','部署到服务器']),
      ('H2','自定义'),
      ('P','想改默认结构——直接改 bin/create.js 里的模板字符串。'),
    ]),""", "tool-scaffold")

swap("    ('tool-test', '测试', []),", r"""    ('tool-test', '测试', [
      ('H1','测试'),
      ('P','xunay 用 Node 内置测试——零依赖。'),
      ('H2','跑测试'),
      ('Code',"node --test test/core.test.js\nnode --test test/compiler.test.js\n# 或\nnode --test test/*.test.js",'bash'),
      ('H2','写测试'),
      ('Code',"// test/core.test.js\nimport { test } from 'node:test'\nimport assert from 'node:assert/strict'\nimport { signal, computed, effect, batch } from '../core/src/core.js'\n\ntest('signal 读写', () => {\n  const s = signal(1)\n  assert.equal(s(), 1)\n  s(2)\n  assert.equal(s(), 2)\n})\n\ntest('effect 订阅与清理', () => {\n  const s = signal(0)\n  let runs = 0\n  const stop = effect(() => { s(); runs++ })\n  assert.equal(runs, 1)\n  s(1); assert.equal(runs, 2)\n  stop()\n  s(2); assert.equal(runs, 2)\n})",'js'),
      ('H2','现有测试'),
      ('Table',['文件','用例数','内容'],[
        ['test/core.test.js','5','signal / computed / effect / batch'],
        ['test/compiler.test.js','2','参数化模板 / IIFE'],
      ]),
      ('H2','断言方法'),
      ('Code',"assert.equal(a, b)      // ==\nassert.deepEqual(a, b)   // 深比较\nassert.ok(v)             // 真值\nassert.throws(fn)        // 抛错",'js'),
      ('H2','测试异步'),
      ('Code',"test('异步', async () => {\n  const r = await fetch('/api')\n  assert.equal(r.status, 200)\n})",'js'),
      ('H2','CI 集成'),
      ('Code',"# .github/workflows/test.yml\n- run: node --test test/*.test.js",'yaml'),
    ]),""", "tool-test")

swap("    ('tool-bench', '基准测试', []),", r"""    ('tool-bench', '基准测试', [
      ('H1','基准测试'),
      ('P','xunay 的核心性能——每操作纳秒级。'),
      ('H2','跑基准'),
      ('Code',"node scripts/bench-runtime.mjs",'bash'),
      ('H2','实测结果'),
      ('Table',['操作','耗时','ops/s'],[
        ['signal 创建','~228 ns','4.4M'],
        ['signal 读','~128 ns','7.8M'],
        ['signal 写（无订阅）','~183 ns','5.5M'],
        ['signal 写 → 触发 effect','~650 ns','1.5M'],
        ['computed 读','~230 ns','4.3M'],
        ['computed 写触发','~1.3 µs','0.79M'],
        ['batch 两写合并','~4.8 µs','0.21M']),
      ('H2','对比 React'),
      ('Table',['操作','XuNay','React'],[
        ['读状态','130ns','Hook 调度 ~50ns'],
        ['写状态','180ns','调度 + Diff ~50µs'],
        ['更新 1 个文本节点','1µs','~10µs ~ 5ms']),
      ('H2','为什么快'),
      ('Ul',
        '无 VDOM——不创建 vnode 树',
        '无 diff——直接改对应节点',
        '精确订阅——一个 signal 变化只触发订阅它的 effect'),
      ('H2','怎么写基准'),
      ('Code',"function bench(name, fn, n = 100000) {\n  for (let i = 0; i < 1000; i++) fn(i)   // 预热\n  const t0 = performance.now()\n  for (let i = 0; i < n; i++) fn(i)\n  const dt = performance.now() - t0\n  console.log(name, ((dt / n) * 1000).toFixed(3) + ' µs/op')\n}\n\nbench('signal 读', () => n())",'js'),
      ('H2','注意'),
      ('Warn','基准跑在单机单进程——真实浏览器里还有 DOM 开销。signal 本身极快，瓶颈通常在 DOM 操作。'),
    ]),""", "tool-bench")

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("工具 8 篇已填")
