import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core2", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ batch ============
swap(`    ('core-batch', 'batch', []),`,
`    ('core-batch', 'batch', [
      ('H1','batch'),
      ('P','batch 把多次 signal 写合并成一次更新。括号里的代码执行完，订阅者只收到一次通知——即使中间改了好几次。'),
      ('H2','为什么需要它'),
      ('P','假设一个按钮同时改 3 个 signal，不 batch 的话，每个 signal 变都会触发一次 effect 重跑——3 次渲染。用 batch 包起来，只渲染 1 次。'),
      ('Code',"import { signal, effect, batch } from 'xunay'\\n\\nconst a = signal(0)\\nconst b = signal(0)\\nconst c = signal(0)\\n\\neffect(() => {\\n  console.log('重跑:', a(), b(), c())\\n})\\n// 立即打印: 0 0 0\\n\\n// 不加 batch：跑 3 次\\na(1)   // 重跑 → 1 0 0\\nb(2)   // 重跑 → 1 2 0\\nc(3)   // 重跑 → 1 2 3\\n\\n// 加 batch：跑 1 次\\nbatch(() => {\\n  a(10)\\n  b(20)\\n  c(30)\\n})\\n// 只重跑一次 → 10 20 30",'xuy'),
      ('H2','基础用法'),
      ('Code',"import { batch } from 'xunay'\\n\\nbatch(() => {\\n  n(1)\\n  m(2)\\n  k(3)\\n})\\n// 三个 signal 都改完，才通知订阅者一次",'xuy'),
      ('H2','什么时候用'),
      ('Table',['场景','要不要 batch'],[
        ['一个事件里改多个 signal','✓ 强烈建议'],
        ['只改一个 signal','不需要（本来就 1 次）'],
        ['批量导入数据','✓'],
        ['初始化状态','✓ 但通常只在 setup 里跑一次'],
        ['循环里改 signal','✓ 否则循环 1000 次就重跑 1000 次'],
      ]),
      ('H2','经典场景：批量初始化'),
      ('Code',"// 不好：7 次更新\\nuser(user => ({ ...user, name: 'x' }))\\ntodos([...list, item1])\\ntodos([...list, item2])\\n// ... 每个都触发一次 effect\\n\\n// 好：1 次更新\\nbatch(() => {\\n  user(u => ({ ...u, name: 'x' }))\\n  todos([...list, item1])\\n  todos([...list, item2])\\n  // ...\\n})",'xuy'),
      ('H2','嵌套 batch'),
      ('P','batch 可以嵌套。内层 batch 结束时不会触发更新，只有最外层结束时才真正 flush。'),
      ('Code',"batch(() => {\\n  a(1)\\n  batch(() => {\\n    b(2)\\n    c(3)\\n  })\\n  d(4)\\n})\\n// 全部改完才更新一次",'xuy'),
      ('P','实现上是一个深度计数器 runtime.batchDepth——进 batch 加 1，出 batch 减 1，减到 0 才真正跑 effect。'),
      ('H2','与 requestAnimationFrame 的关系'),
      ('P','batch 只解决"同一 tick 内的合并"。如果你希望把跨 tick 的多次更新合并到一帧里跑，用 requestAnimationFrame 配合 batch：'),
      ('Code',"let pending = false\\nconst queue = []\\n\\nfunction scheduleUpdate() {\\n  if (pending) return\\n  pending = true\\n  requestAnimationFrame(() => {\\n    batch(() => {\\n      for (const fn of queue) fn()\\n      queue.length = 0\\n    })\\n    pending = false\\n  })\\n}",'xuy'),
      ('H2','性能实测'),
      ('Table',['场景','不 batch','加 batch'],[
        ['改 3 个 signal（3 个订阅者）','3 次 effect','1 次 effect'],
        ['循环 1000 次改同一 signal','1000 次','1 次'],
        ['导入 100 条数据','100 次','1 次'],
      ]),
      ('P','实测：单次 batch 调用的开销约 3~5 微秒。如果不加 batch 要跑 100 次 effect，那就省了 100 倍。'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：在 batch 里 await'),
      ('Code',"batch(async () => {\\n  a(1)\\n  await something()\\n  b(2)   // ✗ await 之后 batch 已经退出了\\n})",'xuy'),
      ('P','batch 只在同步执行期生效。await 会让执行权交出去，batch 深度已经归零，后续改动会立即触发。'),
      ('H3','陷阱 2：以为 batch 会合并"值"'),
      ('Code',"batch(() => {\\n  a(1)\\n  a(2)\\n  a(3)\\n})\\n// a 的最终值是 3，中间值 1 和 2 不会被 effect 看到\\n// 但如果有其他代码读了中间值，那个读取不会被回滚",'xuy'),
      ('P','batch 只合并"触发"，不合并"值的历史"。effect 重跑时读到的是最新值，不是中间值。'),
      ('H3','陷阱 3：在 batch 里读 signal 的旧值'),
      ('Code',"const n = signal(0)\\nbatch(() => {\\n  n(1)\\n  console.log(n())   // 已经读到 1，不是 0\\n  n(2)\\n  console.log(n())   // 读到 2\\n})",'xuy'),
      ('P','batch 只延迟 effect 的重跑，不延迟 signal 本身的写。你写进去立刻能读到。'),
      ('H2','在 effect 里自动 batch'),
      ('P','effect 重跑期间，任何 signal 的写都会自动进 pendingEffects 队列——等 effect 跑完才处理。所以不用手动 batch。'),
      ('Code',"effect(() => {\\n  a()\\n  b(10)   // 写 b，但 b 的订阅者会排到队列里\\n  c(20)   // 同上\\n})\\n// effect 退出后，队列里所有 effect 一起跑",'xuy'),
      ('H2','完整示例：表单批量提交'),
      ('Code',"import { signal, batch, div, button, input, span, mount } from 'xunay'\\n\\nfunction Form() {\\n  const name = signal('')\\n  const email = signal('')\\n  const agree = signal(false)\\n  const submitting = signal(false)\\n  const msg = signal('')\\n\\n  async function submit() {\\n    // 提交前先重置所有 UI 状态——用 batch 一次到位\\n    batch(() => {\\n      submitting(true)\\n      msg('')\\n    })\\n\\n    try {\\n      const r = await fetch('/api/signup', {\\n        method: 'POST',\\n        headers: { 'Content-Type': 'application/json' },\\n        body: JSON.stringify({ name: name(), email: email(), agree: agree() })\\n      })\\n      if (!r.ok) throw new Error('HTTP ' + r.status)\\n      batch(() => {\\n        submitting(false)\\n        msg('提交成功')\\n        name('')\\n        email('')\\n        agree(false)\\n      })\\n    } catch (e) {\\n      batch(() => {\\n        submitting(false)\\n        msg('失败: ' + e.message)\\n      })\\n    }\\n  }\\n\\n  return div(null,\\n    input({ value: () => name(), on: { input: e => name(e.target.value) }, placeholder: '姓名' }),\\n    input({ value: () => email(), on: { input: e => email(e.target.value) }, placeholder: '邮箱' }),\\n    button({ on: { click: submit }, disabled: () => submitting() }, '提交'),\\n    span(null, () => msg())\\n  )\\n}\\n\\nmount(() => Form(), '#app')",'xuy'),
      ('H2','下一步'),
      ('P','读 element 了解 vnode 和标签工厂，或看 list 学习列表渲染。'),
    ]),`,
"batch")

// ============ element ============
swap(`    ('core-element', '元素', []),`,
`    ('core-element', '元素', [
      ('H1','元素'),
      ('P','XuNay 里的"元素"就是一段描述 DOM 的纯数据——类似 React 的 vnode，但更简单：没有 fiber，没有 key，没有 diff 需要的额外字段。'),
      ('H2','元素是数据，不是 DOM'),
      ('P','div(null, \'hello\') 不创建真实 DOM，它返回一个对象：'),
      ('Code',"{\\n  [ELEMENT]: true,\\n  type: 'div',\\n  props: null,\\n  children: ['hello']\\n}",'js'),
      ('P','这个对象是纯数据，可以被缓存、比较、序列化。等 render 真正跑起来，才把它变成 document.createElement。'),
      ('H2','五种元素类型'),
      ('Table',['类型','标志','例子'],[
        ['普通元素','[ELEMENT]','div() / span() / button()'],
        ['Fragment','[FRAGMENT]','frag(a, b, c)'],
        ['文本','字符串/数字','span(null, "hi") 里的 "hi"'],
        ['动态','函数','span(null, () => n())'],
        ['条件','__xunay_show','show(cond, fn)'],
      ]),
      ('H2','标签工厂'),
      ('P','core 内置了 30 多个标签工厂。每个都是 createElement(tag) 的简写。'),
      ('Code',"import { div, span, p, a, button, input, form, label,\\n  ul, ol, li, h1, h2, h3, h4, h5, h6,\\n  table, thead, tbody, tr, td, th, img, br, hr,\\n  pre, code, blockquote } from 'xunay'",'xuy'),
      ('H2','三个参数'),
      ('P','每个工厂函数接受 (props, ...children)：'),
      ('Code',"div(\\n  { class: 'card', id: 'main' },   // props（可选）\\n  h1(null, '标题'),                   // 子节点 1\\n  p(null, '正文'),                     // 子节点 2\\n  () => '动态内容'                     // 子节点 3（函数）\\n)",'xuy'),
      ('H2','props 传 null'),
      ('P','没有 props 时传 null（不用 {}，虽然也行）。null 是最省内存的写法。'),
      ('Code',"div(null, 'hello')      // ✓ 推荐\\ndiv({}, 'hello')        // ✓ 但多创建一个对象\\ndiv('hello')            // ✗ 第一个参数必须是 props 或 null",'xuy'),
      ('H2','createElement 直接调用'),
      ('P','不在内置列表里的标签，用 createElement：'),
      ('Code',"import { createElement } from 'xunay'\\n\\ncreateElement('video', { src: '/movie.mp4', controls: true })\\ncreateElement('canvas', { width: 800, height: 600 })\\ncreateElement('custom-tag', null, 'hello')",'xuy'),
      ('H2','tag 高阶函数'),
      ('P','需要在多处用同一个自定义标签，用 tag 生成工厂：'),
      ('Code',"import { tag } from 'xunay'\\n\\nconst video = tag('video')\\nconst canvas = tag('canvas')\\nconst myTag = tag('my-custom-element')\\n\\nvideo({ src: '/a.mp4' })\\ncanvas({ width: 100 })",'xuy'),
      ('H2','子节点的四种形态'),
      ('Code',"div(null,\\n  'plain string',              // 1. 静态文本\\n  42,                          // 2. 数字\\n  h1(null, 'nested'),          // 3. 嵌套元素\\n  () => n()                    // 4. 动态函数\\n)",'xuy'),
      ('P','前三种在 render 时立即处理，第四种会建立 effect——只有它会在 n 变化时重跑。'),
      ('H2','动态子节点的判定规则'),
      ('P','只要是函数，就当成"动态子节点"。函数返回什么决定怎么渲染：'),
      ('Table',['函数返回','处理方式'],[
        ['字符串/数字','建文本节点，只改 textContent'],
        ['vnode','整块重建（简单但成本高）'],
        ['列表对象','走 list 的 keyed diff'],
        ['show 对象','走条件渲染'],
        ['null / false','渲染成空文本'],
      ]),
      ('H2','属性值也有静态/动态'),
      ('Code',"div({\\n  class: 'card',                 // 静态：直接 setAttribute\\n  id: () => 'item-' + n(),      // 动态：绑 effect\\n  disabled: () => n() > 10,     // 布尔自动处理\\n  style: { color: 'red' }       // 对象自动 assign\\n})",'xuy'),
      ('H2','Fragment'),
      ('P','需要返回多个并列节点时用 frag。它不产生真实的 DOM 节点（内部用一个 display:contents 的 span 占位）。'),
      ('Code',"import { frag } from 'xunay'\\n\\nfrag(\\n  h1(null, '标题'),\\n  p(null, '正文')\\n)\\n// 等价于返回两个并列节点，不包一层 div",'xuy'),
      ('H2','性能'),
      ('Table',['操作','耗时'],[
        ['div(null, "x") 创建 vnode','~150ns'],
        ['render 成 DOM','~2~5µs（createElement + appendChild）'],
        ['更新文本节点','~1µs'],
        ['更新属性','~1~3µs'],
      ]),
      ('P','对比：React 创建一个 element 对象约 200ns，但 diff 整个子树要 10~100µs。xunay 没有 diff，创建成本类似，更新成本低一个量级。'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：把元素当 DOM 用'),
      ('Code',"const el = div(null, 'hi')\\nel.textContent          // ✗ undefined，它是纯数据\\nel.className            // ✗ 同理\\nel.type                 // ✓ 'div'（vnode 的字段）",'xuy'),
      ('P','需要真实 DOM 时用 ref 或 onMount 拿。'),
      ('H3','陷阱 2：children 里写对象'),
      ('Code',"div(null, { foo: 1 })   // ✗ 对象会渲染成 [object Object]\\ndiv(null, JSON.stringify({ foo: 1 }))   // ✓ 手动字符串化",'xuy'),
      ('H3','陷阱 3：忘记 null'),
      ('Code',"div({ class: 'x' }, 'text')   // ✓ 有 props\\ndiv(null, 'text')            // ✓ 无 props\\ndiv('text')                  // ✗ 'text' 被当成 props",'xuy'),
      ('H2','完整示例：构建一个卡片组件'),
      ('Code',"import { div, h1, p, span, img, button, signal, mount } from 'xunay'\\n\\nfunction Card({ title, desc, cover, onClose }) {\\n  return div({ class: 'card' },\\n    img({ class: 'cover', src: cover, alt: title }),\\n    div({ class: 'body' },\\n      h1(null, title),\\n      p(null, desc),\\n      div({ class: 'actions' },\\n        button({ on: { click: onClose } }, '关闭')\\n      )\\n    )\\n  )\\n}\\n\\nmount(() => div(null,\\n  Card({\\n    title: 'XuNay',\\n    desc: '极简前端框架',\\n    cover: '/logo.png',\\n    onClose: () => console.log('关闭')\\n  })\\n), '#app')",'xuy'),
      ('H2','下一步'),
      ('P','读 props 了解属性细节，或看 children 了解子节点处理。'),
    ]),`,
"element")

writeFileSync(p, s)
console.log("batch / element 两篇已填")
