import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core6", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ err ============
swap(`    ('core-err', 'err', []),`,
`    ('core-err', 'err', [
      ('H1','err'),
      ('P','err 是错误边界——把一段可能抛错的代码包起来，出错时返回兜底内容，不炸整个应用。'),
      ('H2','基础用法'),
      ('Code',"import { err, div } from 'xunay'\\n\\nerr(() => {\\n  return risky()   // 可能抛错\\n}, () => div(null, '出错了'))",'xuy'),
      ('H2','两个参数'),
      ('Table',['参数','类型','作用'],[
        ['fn','() => T','可能抛错的函数'],
        ['fallback','T 或 (e) => T','出错时的兜底'],
      ]),
      ('H2','fallback 是函数'),
      ('P','fallback 是函数时会拿到错误对象。'),
      ('Code',"err(\\n  () => JSON.parse(userInput),\\n  (e) => div(null, 'JSON 格式错误: ' + e.message)\\n)",'xuy'),
      ('H2','fallback 是值'),
      ('P','fallback 是普通值时直接返回。'),
      ('Code',"const data = err(() => JSON.parse(str), null)\\n// str 不是合法 JSON 时返回 null",'xuy'),
      ('H2','什么时候用'),
      ('Ul',
        'JSON.parse 用户输入',
        '访问可能不存在的字段',
        '第三方库调用',
        '可能为 null 的 API 结果'),
      ('H2','默认行为'),
      ('P','不传 fallback 时，出错会打印 console.error，返回 undefined。'),
      ('Code',"err(() => JSON.parse('bad'))\\n// console: [XuNay] SyntaxError: ...\\n// 返回 undefined",'xuy'),
      ('H2','和 try/catch 对比'),
      ('Table',['','err','try/catch'],[
        ['写法','表达式','语句'],
        ['返回值','有','手动 return'],
        ['日志','自动','手动'],
        ['嵌在 JSX 里','✓','✗'],
      ]),
      ('H2','完整示例：容错解析'),
      ('Code',"import { err, div, input, signal, span, mount } from 'xunay'\\n\\nfunction JsonViewer() {\\n  const text = signal('{\\\"name\\\":\\\"x\\\"}')\\n  const parsed = () => err(\\n    () => JSON.parse(text()),\\n    (e) => ({ __error: e.message })\\n  )\\n\\n  return div(null,\\n    input({\\n      value: () => text(),\\n      on: { input: e => text(e.target.value) }\\n    }),\\n    () => {\\n      const p = parsed()\\n      if (p && p.__error) return div({ class: 'error' }, '错误: ' + p.__error)\\n      return div({ class: 'ok' }, JSON.stringify(p, null, 2))\\n    }\\n  )\\n}\\n\\nmount(() => JsonViewer(), '#app')",'xuy'),
      ('H2','异步错误不归 err 管'),
      ('Warn','err 只捕获同步抛错。异步 Promise 拒绝要用 .catch 或 try/catch 包 async。'),
      ('Code',"// ✗ err 抓不到异步错误\\nerr(() => {\\n  fetch('/api').then(r => r.json().then(j => { throw new Error() }))\\n})\\n\\n// ✓ 手动 catch\\nfetch('/api')\\n  .then(r => r.json())\\n  .catch(e => console.error(e))",'xuy'),
    ]),`,
"err")

// ============ lazy ============
swap(`    ('core-lazy', 'lazy', []),`,
`    ('core-lazy', 'lazy', [
      ('H1','lazy'),
      ('P','lazy 是"延迟加载的组件"——第一次渲染时才加载模块，加载期间显示空，加载完再渲染。类似 React.lazy + Suspense。'),
      ('H2','基础用法'),
      ('Code',"import { lazy } from 'xunay'\\n\\nconst HeavyChart = lazy(() => import('./Chart.js'))\\n\\n// 用的时候\\ndiv(null, HeavyChart({ data }))",'xuy'),
      ('H2','工作流程'),
      ('P','1. 第一次调用 HeavyChart 时触发 loader；2. loader 返回 Promise；3. 加载期间返回 null；4. 加载完拿到组件，重新渲染。'),
      ('H2','加载失败'),
      ('P','loader 拒绝时错误会抛出，用 err 捕获或让父级的错误边界处理。'),
      ('Code',"import { lazy, err, div } from 'xunay'\\n\\nconst Lazy = lazy(() => import('./Missing.js'))\\n\\nerr(() => Lazy({}), () => div(null, '模块加载失败'))",'xuy'),
      ('H2','加载中状态'),
      ('P','lazy 不内置加载态。要显示 loading，包一层：'),
      ('Code',"import { lazy, signal, show, div, span } from 'xunay'\\n\\nconst loading = signal(true)\\nconst Heavy = lazy(() => {\\n  return import('./Heavy.js').then(m => {\\n    loading(false)\\n    return m\\n  })\\n})\\n\\ndiv(null,\\n  show(() => loading(), () => span(null, '加载中...')),\\n  () => loading() ? null : Heavy({})\\n)",'xuy'),
      ('H2','路由懒加载'),
      ('Code',"const pages = {\\n  '/': lazy(() => import('./pages/Home.js')),\\n  '/about': lazy(() => import('./pages/About.js')),\\n  '/todo': lazy(() => import('./pages/Todo.js'))\\n}\\\n\\nfunction Router() {\\n  return div(null, () => {\\n    const Page = pages[route()]\\n    return Page ? Page({}) : div(null, '404')\\n  })\\n}",'xuy'),
      ('H2','为什么有用'),
      ('Table',['场景','不用 lazy','用 lazy'],[
        ['首屏体积','全部打进去','只打首屏'],
        ['加载时机','立即','用到才加载'],
        ['首屏速度','慢','快'],
        ['后续切换','无延迟','可能有延迟'],
      ]),
      ('H2','与代码分割配合'),
      ('P','lazy 配合动态 import 才能触发代码分割。esbuild / vite 看到 import() 会拆成独立 chunk。'),
      ('Code',"// 静态引入：打进同一个 bundle\\nimport { Heavy } from './Heavy.js'\\n\\n// 动态引入：拆成独立文件\\nconst Heavy = lazy(() => import('./Heavy.js'))",'xuy'),
      ('H2','实现原理'),
      ('Code',"// 简化的 lazy 实现\\nfunction lazy(loader) {\\n  const comp = signal(null)\\n  const error = signal(null)\\n  let started = false\\n  return function Lazy(...args) {\\n    if (!started) {\\n      started = true\\n      loader().then(m => comp(m.default || m)).catch(e => error(e))\\n    }\\n    if (error()) throw error()\\n    const c = comp()\\n    return c ? c(...args) : null\\n  }\\n}",'js'),
      ('H2','完整示例：按需加载图表'),
      ('Code',"import { lazy, div, button, signal, show, span, mount } from 'xunay'\\n\\nconst showChart = signal(false)\\nconst loading = signal(false)\\n\\nconst Chart = lazy(() => {\\n  loading(true)\\n  return import('./Chart.js').then(m => {\\n    loading(false)\\n    return m\\n  })\\n})\\n\\nmount(() => div(null,\\n  button({ on: { click: () => showChart(true) } }, '显示图表'),\\n  show(() => loading(), () => span(null, '加载中...')),\\n  show(() => showChart(), () => Chart({ data: [1, 2, 3] }))\\n), '#app')",'xuy'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：loader 立即执行了'),
      ('Code',"// ✗ loader 立即执行\\nconst Heavy = lazy(import('./Heavy.js'))\\n\\n// ✓ 传函数，让 lazy 决定何时执行\\nconst Heavy = lazy(() => import('./Heavy.js'))",'xuy'),
      ('H3','陷阱 2：加载中返回 null 导致布局跳动'),
      ('Code',"// ✗ 加载完布局跳动\\ndiv(null, () => loading() ? null : Heavy({}))\\n\\n// ✓ 占位保持尺寸\\ndiv({ style: { minHeight: '200px' } },\\n  () => loading() ? span(null, '加载中') : Heavy({})\\n)",'xuy'),
    ]),`,
"lazy")

// ============ trans ============
swap(`    ('core-trans', 'trans', []),`,
`    ('core-trans', 'trans', [
      ('H1','trans'),
      ('P','trans 是内置的过渡助手——返回一对 enter / leave 方法，用在 onMount / onUnmount 里做淡入淡出动画。'),
      ('H2','基础用法'),
      ('Code',"import { trans, div, onMount, onUnmount } from 'xunay'\\n\\nconst fade = trans(200)   // 200ms\\n\\ndiv(null, '内容')   // 在这个元素上用 fade.enter / fade.leave",'xuy'),
      ('H2','trans 返回什么'),
      ('Code',"const fade = trans(300)\\n// 返回：\\n{\\n  enter(el) { ... },        // 元素出现时调用\\n  leave(el, done) { ... }   // 元素消失时调用\\n}",'js'),
      ('H2','enter'),
      ('P','设置 opacity: 0，下一帧改 opacity: 1——触发 CSS transition 淡入。'),
      ('Code',"enter(el) {\\n  el.style.transition = 'opacity 200ms ease'\\n  el.style.opacity = '0'\\n  requestAnimationFrame(() => { el.style.opacity = '1' })\\n}",'js'),
      ('H2','leave'),
      ('P','设置 opacity: 0，动画结束后调用 done 回调。'),
      ('Code',"leave(el, done) {\\n  el.style.transition = 'opacity 200ms ease'\\n  el.style.opacity = '0'\\n  setTimeout(done, 200)\\n}",'js'),
      ('H2','完整用法'),
      ('Code',"import { trans, div, onMount, onUnmount, signal, show, button, mount } from 'xunay'\\n\\nfunction Modal() {\\n  const fade = trans(300)\\n  const open = signal(false)\\n\\n  return div(null,\\n    button({ on: { click: () => open(!open()) } }, '切换'),\\n    show(() => open(), () => {\\n      const overlay = div({ class: 'overlay' }, '模态框')\\n      onMount(() => fade.enter(overlay))\\n      onUnmount(() => {\\n        // leave 需要异步——show 会立即卸载，所以这里用同步淡出效果有限\\n        fade.leave(overlay, () => {})\\n      })\\n      return overlay\\n    })\\n  )\\n}\\n\\nmount(() => Modal(), '#app')",'xuy'),
      ('H2','show 的过渡限制'),
      ('Warn','show 切换是同步的——leave 阶段元素已经被移除，动画看不到。需要真过渡时手动控制挂载：'),
      ('Code',"const open = signal(false)\\nconst visible = signal(false)\\n\\nfunction toggle() {\\n  if (open()) {\\n    open(false)\\n    setTimeout(() => visible(false), 300)   // 等动画完再隐藏\\n  } else {\\n    visible(true)\\n    requestAnimationFrame(() => open(true))\\n  }\\n}\\n\\ndiv(null,\\n  button({ on: { click: toggle } }, '切换'),\\n  show(() => visible(), () => {\\n    const el = div({ class: () => 'modal' + (open() ? ' in' : '') }, '内容')\\n    return el\\n  })\\n)",'xuy'),
      ('P','配合 CSS：.modal { opacity: 0; transition: opacity .3s } .modal.in { opacity: 1 }。'),
      ('H2','用 CSS 替代 trans'),
      ('P','大多数场景不需要 trans——纯 CSS 更简单：'),
      ('Code',".fade-enter { opacity: 0 }\\n.fade-enter-active { opacity: 1; transition: opacity .3s }",'css'),
      ('P','用 class 切换即可。trans 适合需要 JS 精确控制时机的场景。'),
      ('H2','完整示例：列表项淡入'),
      ('Code',"import { div, ul, li, list, onMount, signal, button, mount } from 'xunay'\\n\\nfunction List() {\\n  const items = signal([1, 2, 3])\\n\\n  return div(null,\\n    button({ on: { click: () => items(list => [...list, list.length + 1]) } }, '添加'),\\n    ul(null,\\n      list(items, i => i, i => {\\n        const el = li({ class: 'item-enter' }, '项目 ' + i)\\n        onMount(() => {\\n          requestAnimationFrame(() => el.classList.add('item-enter-active'))\\n        })\\n        return el\\n      })\\n    )\\n  )\\n}\\n\\nmount(() => List(), '#app')",'xuy'),
      ('Code',".item-enter { opacity: 0; transform: translateX(-20px) }\\n.item-enter-active { opacity: 1; transform: none; transition: all .3s }",'css'),
    ]),`,
"trans")

// ============ txt ============
swap(`    ('core-txt', 'txt 模板', []),`,
`    ('core-txt', 'txt 模板', [
      ('H1','txt 模板'),
      ('P','txt 是"响应式模板字符串"——用反引号写，内部插值里的值自动响应式。比拼接字符串更自然。'),
      ('H2','基础用法'),
      ('Code',"import { txt } from 'xunay'\\n\\nconst n = signal(0)\\n\\nspan(null, txt\\\`n = \\\${n}\\\`)\\n// 等价于 span(null, () => 'n = ' + n())",'xuy'),
      ('H2','对比拼接'),
      ('Table',['写法','示例'],[
        ['拼接','() => "n = " + n()'],
        ['txt','txt\\\`n = \\\${n}\\\`'],
      ]),
      ('P','txt 更短，视觉更清楚。复杂插值时优势明显。'),
      ('H2','多个插值'),
      ('Code',"const a = signal(1)\\nconst b = signal(2)\\nconst c = signal(3)\\n\\ndiv(null, txt\\\`a=\\\${a} b=\\\${b} c=\\\${c}\\\`)\\n// a、b、c 任一变化都会重跑",'xuy'),
      ('H2','插值可以是函数'),
      ('Code',"txt\\\`共 \\\${() => count().total} 条\\\`\\n// 内层函数也会被追踪",'xuy'),
      ('H2','文本节点最小更新'),
      ('P','txt 内部创建单个文本节点。任一插值变化时，只改 textContent——不重建元素。'),
      ('Code',"// 一次渲染后\\n// <span>n = 0</span>\\n// n 变化 → 只改 span.textContent\\n// span 元素、属性、父级都不动",'js'),
      ('H2','用在哪里'),
      ('Ul',
        '标题里的动态数字',
        '副标题的统计',
        '按钮文字',
        '任何需要拼字符串的地方'),
      ('H2','txt vs 函数返回字符串'),
      ('Code',"// 两种等价\\nspan(null, txt\\\`n = \\\${n}\\\`)\\nspan(null, () => 'n = ' + n())\\n\\n// txt 适合 3 个以上插值\\nspan(null, txt\\\`\\\${a} + \\\${b} = \\\${c}\\\`)",'xuy'),
      ('H2','完整示例'),
      ('Code',"import { div, h1, p, button, signal, txt, mount } from 'xunay'\\n\\nfunction Stats() {\\n  const online = signal(128)\\n  const total = signal(200)\\n\\n  return div(null,\\n    h1(null, txt\\\`在线用户 \\\${online} / \\\${total}\\\`),\\n    p(null, txt\\\`占比 \\\${() => Math.round(online() / total() * 100)}%\\\`),\\n    button({ on: { click: () => online(online() + 1) } }, '+1'),\\n    button({ on: { click: () => total(total() + 1) } }, '总数+1')\\n  )\\n}\\n\\nmount(() => Stats(), '#app')",'xuy'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：外层忘记加 ()'),
      ('Code',"// ✗ 直接写 signal\\nspan(null, txt\\\`n = \\\${n()}\\\`)   // 立即求值\\n\\n// ✓ 传函数\\nspan(null, txt\\\`n = \\\${n}\\\`)      // 响应式",'xuy'),
      ('P','txt 内部会自动包函数——不用手动 () => n()。'),
      ('H3','陷阱 2：格式复杂时用模板更好'),
      ('Code',"// 复杂条件用模板难写\\ntxt\\\`\\\${() => n() > 0 ? '正' : '负'}\\\`   // ✗ 太挤\\n\\n// 拆开写\\nspan(null,\\n  () => n() > 0 ? '正' : '负'\\n)",'xuy'),
    ]),`,
"txt")

// ============ ssr ============
swap(`    ('core-ssr', 'SSR', []),`,
`    ('core-ssr', 'SSR', [
      ('H1','SSR'),
      ('P','服务端渲染——在服务器把 vnode 转成 HTML 字符串，直接送到浏览器。首屏不用等 JS 加载，内容立刻显示。'),
      ('H2','两个 API'),
      ('Table',['API','运行环境','作用'],[
        ['renderToString(vnode)','Node / 服务器','vnode → HTML 字符串'],
        ['hydrate(vnode, target)','浏览器','接管已有的 HTML'],
      ]),
      ('H2','renderToString'),
      ('Code',"import { renderToString, div, h1, p } from 'xunay'\\n\\nconst html = renderToString(\\n  div({ class: 'app' },\\n    h1(null, '标题'),\\n    p(null, '正文')\\n  )\\n)\\n// html = '<div class=\\\"app\\\"><h1>标题</h1><p>正文</p></div>'",'xuy'),
      ('H2','hydrate'),
      ('P','客户端拿服务端渲染好的 HTML，不重新创建 DOM，而是"接管"——绑定事件、建立 effect、恢复响应式。'),
      ('Code',"import { hydrate, div, h1, p } from 'xunay'\\n\\nhydrate(\\n  div({ class: 'app' },\\n    h1(null, '标题'),\\n    p(null, '正文')\\n  ),\\n  '#app'   // 已有的 DOM 容器\\n)",'xuy'),
      ('H2','完整流程'),
      ('Code',"// ===== 服务端 =====\\nimport { renderToString } from 'xunay/ssr'\\nimport { App } from './App.js'\\n\\napp.get('/', (req, res) => {\\n  const html = renderToString(App())\\n  res.send(\\`\\n    <!DOCTYPE html>\\n    <html><body>\\n      <div id=\\\"app\\\">\\${html}</div>\\n      <script src=\\\"/app.js\\\"></script>\\n    </body></html>\\n  \\`)\\n})\\n\\n// ===== 浏览器 =====\\nimport { hydrate } from 'xunay/ssr'\\nimport { App } from './App.js'\\n\\nhydrate(App(), '#app')",'xuy'),
      ('H2','服务端能做和不能做的'),
      ('Table',['能做','不能做'],[
        ['创建 vnode','访问 document'],
        ['拼 HTML 字符串','访问 window'],
        ['计算 initial 状态','绑定事件'],
        ['读写数据','使用定时器'],
      ]),
      ('Warn','服务端渲染时不要写 onMount、effect、setTimeout——环境里没有 DOM。用 if (typeof window !== \\'undefined\\') 判断。'),
      ('H2','hydration 不匹配'),
      ('P','服务端和客户端渲染的内容不一致时，xunay 会报警告。原因通常是：'),
      ('Ul',
        '服务端和客户端的初始 signal 不同',
        '用了 Date.now() / Math.random()',
        '用了 typeof window 分支'),
      ('Code',"// ✗ 不一致：服务端渲染的是空\\ndiv(null, () => typeof window !== 'undefined' ? 'browser' : 'server')\\n\\n// ✓ 用 onMount 之后才更新\\nconst isBrowser = signal(false)\\nonMount(() => isBrowser(true))\\ndiv(null, () => isBrowser() ? 'browser' : 'server')",'xuy'),
      ('H2','性能'),
      ('Table',['','CSR','SSR + hydrate'],[
        ['首屏内容','等 JS 加载后显示','HTML 到达立即显示'],
        ['交互','立即可用','hydrate 后可用'],
        ['服务器成本','低','高（每请求渲染）'],
        ['SEO','差','好'],
      ]),
      ('H2','什么时候用 SSR'),
      ('Ul',
        'SEO 重要（博客、电商、新闻）',
        '首屏速度关键',
        '有服务端渲染能力'),
      ('P','纯后台 / 内部工具不需要 SSR——CSR 更快更简单。'),
      ('H2','完整示例'),
      ('Code',"// ===== 共享 App =====\\n// App.js\\nimport { div, h1, p, button, signal } from 'xunay'\\n\\nexport function App() {\\n  const n = signal(0)\\n  return div({ class: 'app' },\\n    h1(null, 'SSR 演示'),\\n    p(null, () => '计数: ' + n()),\\n    button({ on: { click: () => n(v => v + 1) } }, '+1')\\n  )\\n}\\n\\n// ===== 服务端 =====\\n// server.js\\nimport { renderToString } from 'xunay/ssr'\\nimport { App } from './App.js'\\n\\nconst html = renderToString(App())\\n// <div class=\\\"app\\\"><h1>SSR 演示</h1><p>计数: 0</p><button>+1</button></div>\\n\\n// ===== 浏览器 =====\\n// client.js\\nimport { hydrate } from 'xunay/ssr'\\nimport { App } from './App.js'\\n\\nhydrate(App(), '#app')",'xuy'),
    ]),`,
"ssr")

writeFileSync(p, s)
console.log("err / lazy / trans / txt / ssr 五篇已填")
