#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

# 在 ai-contract 后面插入 4 篇
old = """    ('ai-contract', 'API 契约', ["""
# 我们先在 ai-contract 结束位置后追加。找到 ai-contract 项结尾
# 更简单的做法：在 "('入门', [" 前追加
anchor = "  ('入门', ["

new_entries = """    ('ai-patterns', '模式库', [
      ('H1','模式库'),
      ('P','30 个常见场景的正确写法。AI 写代码时按图索骥。'),
      ('H2','状态'),
      ('H3','1. 局部状态'),
      ('Code',"function Counter() {\\n  const n = signal(0)\\n  return div(null, () => String(n()))\\n}",'xuy'),
      ('H3','2. 全局状态'),
      ('Code',"// store.js\\nexport const user = signal(null)\\nexport const todos = signal([])\\n\\n// 组件\\nimport { user } from './store.js'\\ndiv(null, () => user() ? user().name : '未登录')",'xuy'),
      ('H3','3. 派生状态'),
      ('Code',"const items = signal([])\\nconst total = computed(() => items().reduce((s, i) => s + i.price, 0))",'xuy'),
      ('H3','4. 状态持久化'),
      ('Code',"import { effect } from 'xunay'\\nconst n = signal(+localStorage.getItem('n') || 0)\\neffect(() => localStorage.setItem('n', n()))",'xuy'),
      ('H2','列表'),
      ('H3','5. 基础列表'),
      ('Code',"ul(null, list(items, i => i.id, i => li(null, i.title)))",'xuy'),
      ('H3','6. 添加'),
      ('Code',"todos(l => [...l, { id: Date.now(), title, done: false }])",'xuy'),
      ('H3','7. 删除'),
      ('Code',"todos(l => l.filter(t => t.id !== id))",'xuy'),
      ('H3','8. 修改一项'),
      ('Code',"todos(l => l.map(t => t.id === id ? { ...t, done: !t.done } : t))",'xuy'),
      ('H3','9. 过滤'),
      ('Code',"const filtered = computed(() => {\\n  const f = filter()\\n  if (f === 'active') return todos().filter(t => !t.done)\\n  return todos()\\n})\\n\\nul(null, list(filtered, t => t.id, t => li(null, t.title)))",'xuy'),
      ('H3','10. 排序'),
      ('Code',"todos(l => [...l].sort((a, b) => a.priority - b.priority))",'xuy'),
      ('H2','表单'),
      ('H3','11. 受控输入'),
      ('Code',"const value = signal('')\\ninput({ value: () => value(), on: { input: e => value(e.target.value) } })",'xuy'),
      ('H3','12. 表单封装'),
      ('Code',"function model(sig) {\\n  return {\\n    value: () => sig(),\\n    on: { input: e => sig(e.target.value) }\\n  }\\n}\\ninput({ ...model(name) })",'xuy'),
      ('H3','13. 复选框'),
      ('Code',"const agree = signal(false)\\ninput({ type: 'checkbox', checked: () => agree(), on: { change: e => agree(e.target.checked) } })",'xuy'),
      ('H3','14. 实时校验'),
      ('Code',"const email = signal('')\\nconst emailErr = computed(() => {\\n  if (!email()) return ''\\n  return /^[^@]+@[^@]+$/.test(email()) ? '' : '邮箱格式错误'\\n})\\ninput({ value: () => email(), on: { input: e => email(e.target.value) } })\\nshow(emailErr, () => div({ class: 'error' }, () => emailErr()))",'xuy'),
      ('H3','15. 提交'),
      ('Code',"async function submit(e) {\\n  e.preventDefault()\\n  const r = await fetch('/api/submit', {\\n    method: 'POST',\\n    headers: { 'Content-Type': 'application/json' },\\n    body: JSON.stringify({ name: name() })\\n  })\\n  if (r.ok) success(true)\\n}\\nform({ on: { submit } }, ...)",'xuy'),
      ('H2','条件'),
      ('H3','16. show 条件'),
      ('Code',"show(() => open(), () => div(null, '内容'))",'xuy'),
      ('H3','17. 三目'),
      ('Code',"() => open() ? div(null, '显示') : div(null, '隐藏')",'xuy'),
      ('H3','18. 多分支'),
      ('Code',"() => {\\n  const s = status()\\n  if (s === 'loading') return div(null, '加载中')\\n  if (s === 'error') return div(null, '错误')\\n  return div(null, 'OK')\\n}",'xuy'),
      ('H3','19. 空态'),
      ('Code',"show(() => items().length === 0, () => p(null, '暂无数据'))",'xuy'),
      ('H2','异步'),
      ('H3','20. 加载态三件套'),
      ('Code',"const data = signal(null)\\nconst error = signal(null)\\nconst loading = signal(false)\\n\\nonMount(async () => {\\n  loading(true)\\n  try {\\n    data(await (await fetch('/api/todos')).json())\\n  } catch (e) {\\n    error(e.message)\\n  } finally {\\n    loading(false)\\n  }\\n})",'xuy'),
      ('H3','21. 竞态处理'),
      ('Code',"let token = 0\\nasync function load(id) {\\n  const my = ++token\\n  const r = await fetch('/api/' + id)\\n  if (my !== token) return\\n  data(await r.json())\\n}",'xuy'),
      ('H3','22. 防抖搜索'),
      ('Code',"const q = signal('')\\nlet timer = null\\nfunction onInput(e) {\\n  q(e.target.value)\\n  clearTimeout(timer)\\n  timer = setTimeout(() => search(q()), 300)\\n}",'xuy'),
      ('H2','生命周期'),
      ('H3','23. 挂载后执行'),
      ('Code',"onMount(() => { el().focus() })",'xuy'),
      ('H3','24. 定时器'),
      ('Code',"onMount(() => {\\n  const id = setInterval(tick, 1000)\\n  onUnmount(() => clearInterval(id))\\n})",'xuy'),
      ('H3','25. 事件监听'),
      ('Code',"onMount(() => {\\n  const h = e => console.log(e.key)\\n  window.addEventListener('keydown', h)\\n  onUnmount(() => window.removeEventListener('keydown', h))\\n})",'xuy'),
      ('H2','路由'),
      ('H3','26. hash 路由'),
      ('Code',"// router.js\\nimport { signal } from 'xunay'\\nexport const route = signal(location.hash.slice(1) || '/')\\nwindow.addEventListener('hashchange', () => route(location.hash.slice(1) || '/'))",'xuy'),
      ('H3','27. 页面切换'),
      ('Code',"() => {\\n  const r = route()\\n  if (r === '/') return Home()\\n  if (r === '/about') return About()\\n  return div(null, '404')\\n}",'xuy'),
      ('H2','DOM 操作'),
      ('H3','28. ref 引用'),
      ('Code',"const el = ref()\\ninput({ ref: e => el(e) })\\nonMount(() => el().focus())",'xuy'),
      ('H3','29. 尺寸测量'),
      ('Code',"const size = signal({ w: 0, h: 0 })\\nconst el = ref()\\nonMount(() => {\\n  const r = el().getBoundingClientRect()\\n  size({ w: r.width, h: r.height })\\n})",'xuy'),
      ('H3','30. 滚动到底'),
      ('Code',"const el = ref()\\nfunction scrollBottom() {\\n  const e = el()\\n  if (e) e.scrollTop = e.scrollHeight\\n}",'xuy'),
    ]),
    ('ai-antipatterns', '反模式', [
      ('H1','反模式'),
      ('P','最常见的错误写法 —— 及正确做法。AI 写代码时避免。'),
      ('H2','1. 静态求值'),
      ('Code',"// 错\\nspan(null, n())\\ninput({ value: name() })\\n\\n// 对\\nspan(null, () => n())\\ninput({ value: () => name() })",'xuy'),
      ('H2','2. 少加 ()'),
      ('Code',"// 错——显示函数本身\\ndiv(null, () => n)\\n\\n// 对\\ndiv(null, () => n())",'xuy'),
      ('H2','3. effect 里读又写'),
      ('Code',"// 错——死循环\\neffect(() => { n(n() + 1) })\\n\\n// 对——放事件里\\nbutton({ on: { click: () => n(v => v + 1) } })",'xuy'),
      ('H2','4. 深层对象修改'),
      ('Code',"// 错——引用没变，不触发\\nconst u = signal({ a: { b: 1 } })\\nu().a.b = 2\\n\\n// 对——整体替换\\nu(u => ({ ...u, a: { ...u.a, b: 2 } }))",'xuy'),
      ('H2','5. 数组 push'),
      ('Code',"// 错\\ntodos().push({ id: 1 })\\n\\n// 对\\ntodos(l => [...l, { id: 1 }])",'xuy'),
      ('H2','6. list 用索引做 key'),
      ('Code',"// 错——重排时状态错乱\\nlist(items, (i, idx) => idx, ...)\\n\\n// 对\\nlist(items, i => i.id, ...)",'xuy'),
      ('H2','7. list 里做副作用'),
      ('Code',"// 错——每次渲染都请求\\nlist(items, i => i.id, i => {\\n  fetch('/api/' + i.id)\\n  return li(null, i.title)\\n})\\n\\n// 对——副作用放 onMount\\nlist(items, i => i.id, i => {\\n  onMount(() => fetch('/api/' + i.id))\\n  return li(null, i.title)\\n})",'xuy'),
      ('H2','8. 模块顶层 onMount'),
      ('Code',"// 错\\nonMount(() => console.log('x'))\\n\\n// 对\\nfunction App() {\\n  onMount(() => console.log('x'))\\n  return div(null, 'x')\\n}",'xuy'),
      ('H2','9. 动态值里用 if 语句'),
      ('Code',"// 错——不是表达式\\ndiv(null, () => {\\n  if (n() > 0) return '正'\\n  return '负'\\n})\\n\\n// 对——可以是表达式\\ndiv(null, () => n() > 0 ? '正' : '负')",'xuy'),
      ('H2','10. show 条件传值'),
      ('Code',"// 错\\nshow(open(), () => div())\\n\\n// 对\\nshow(() => open(), () => div())",'xuy'),
      ('H2','11. 属性值写成事件'),
      ('Code',"// 错\\nbutton({ onClick: handler })\\n\\n// 对\\nbutton({ on: { click: handler } })",'xuy'),
      ('H2','12. 事件立即执行'),
      ('Code',"// 错——立即执行了\\nbutton({ on: { click: handler() } })\\n\\n// 对——传函数\\nbutton({ on: { click: handler } })\\n// 或\\nbutton({ on: { click: () => handler() } })",'xuy'),
      ('H2','13. 组件里写副作用'),
      ('Code',"// 错——每次父更新可能重跑\\nfunction User({ id }) {\\n  fetch('/api/user/' + id)\\n  return div(null, 'x')\\n}\\n\\n// 对——onMount\\nfunction User({ id }) {\\n  onMount(() => fetch('/api/user/' + id))\\n  return div(null, 'x')\\n}",'xuy'),
      ('H2','14. computed 里写 signal'),
      ('Code',"// 错\\nconst bad = computed(() => {\\n  a(1)   // 副作用\\n  return a()\\n})\\n\\n// 对\\nconst ok = computed(() => a() * 2)",'xuy'),
      ('H2','15. 忘记 onUnmount 清理'),
      ('Code',"// 错——内存泄漏\\nonMount(() => setInterval(tick, 1000))\\n\\n// 对\\nonMount(() => {\\n  const id = setInterval(tick, 1000)\\n  onUnmount(() => clearInterval(id))\\n})",'xuy'),
      ('H2','16. 用 React 的 props.key'),
      ('Code',"// 错\\nli({ key: t.id }, t.title)\\n\\n// 对\\nlist(todos, t => t.id, t => li(null, t.title))",'xuy'),
      ('H2','17. 用 JSX'),
      ('Code',"// 错\\nreturn <div>hello</div>\\n\\n// 对\\nreturn div(null, 'hello')",'xuy'),
      ('H2','18. 用 useEffect 依赖数组'),
      ('Code',"// 错\\neffect(() => { n() }, [n])\\n\\n// 对\\neffect(() => { n() })",'xuy'),
      ('H2','19. 用 useMemo 手写依赖'),
      ('Code',"// 错\\nconst double = useMemo(() => n() * 2, [n])\\n\\n// 对\\nconst double = computed(() => n() * 2)",'xuy'),
      ('H2','20. 忘记 target 的 #'),
      ('Code',"// 错\\nmount(App, 'app')\\n\\n// 对\\nmount(App, '#app')",'xuy'),
    ]),
    ('ai-constraints', '约束清单', [
      ('H1','约束清单'),
      ('P','写 xunay 代码必须遵守的硬约束。违反会出错或性能差。'),
      ('H2','编译器约束'),
      ('Table',['约束','说明'],[
        ['.xuy 里不能写 JSX','用 div(...) 函数调用'],
        ['.xuy 里不能写 type 注解','.xuy 是 JS'],
        ['参数化模板必须包箭头函数','(r) => div(...) 而不是 div(...)'],
        ['字符串里的 div( 可能误处理','避免字符串里写代码'],
        ['正则字面量可能误判','用 new RegExp()'],
        ['不能动态生成标签名','用 createElement']),
      ('H2','运行时约束'),
      ('Table',['约束','说明'],[
        ['signal 读要加 ()','n() 不是 n'],
        ['动态值要包函数','() => n() 不是 n()'],
        ['深层对象要整体替换','{ ...u, a: {...} }'],
        ['数组操作返回新数组','不 push / splice'],
        ['effect 里不能读写同一 signal','会死循环'],
        ['list 的 key 必须唯一稳定','不用索引']),
      ('H2','生命周期约束'),
      ('Table',['约束','说明'],[
        ['onMount 必须在组件内','模块顶层不生效'],
        ['onUnmount 里不能访问 DOM','元素可能已移除'],
        ['show 切换会重建子树','内部 signal 状态重置'],
        ['list 删除项会 dispose scope','内部 effect 自动清理']),
      ('H2','性能约束'),
      ('Table',['约束','说明'],[
        ['函数返回 vnode 会整块重建','大子树用 show / list'],
        ['一个 effect 不要读超过 10 个 signal','拆成多个'],
        ['列表项渲染不要有副作用','纯函数'],
        ['不要深层嵌套对象做 signal','内存和性能都差']),
      ('H2','SSR 约束'),
      ('Table',['约束','说明'],[
        ['服务端不能访问 document / window','用 typeof window 判断'],
        ['服务端不跑 onMount / effect','只渲染结构'],
        ['hydrate 时 DOM 必须匹配','否则警告 + 重建'],
        ['两端 initial state 必须一致','否则闪变']),
      ('H2','安全约束'),
      ('Table',['约束','说明'],[
        ['html 属性有 XSS 风险','先 sanitize'],
        ['用户输入不直接写 innerHTML','用 textContent'],
        ['CORS 不用 *','明确列出来源'],
        ['SQL 必须参数化','防注入']),
      ('H2','设计约束'),
      ('Table',['约束','说明'],[
        ['不写 TypeScript','设计哲学'],
        ['不加不必要的依赖','核心零依赖'],
        ['不用 Hooks 概念','用 scope'],
        ['不引入 VDOM','用 effect 精确更新']),
    ]),
    ('ai-migration', '迁移对照', [
      ('H1','迁移对照'),
      ('P','从 React / Vue 到 xunay 的完整对照表。'),
      ('H2','React → XuNay'),
      ('H3','状态'),
      ('Table',['React','XuNay'],[
        ['useState(0)','signal(0)'],
        ['n','n()'],
        ['setN(1)','n(1)'],
        ['setN(v => v + 1)','n(v => v + 1)'],
        ['useMemo(fn, deps)','computed(fn)'],
        ['useRef()','ref()'],
        ['useContext(Ctx)','Ctx.get()']),
      ('H3','副作用'),
      ('Table',['React','XuNay'],[
        ['useEffect(fn, deps)','effect(fn)'],
        ['useEffect(fn, [])','onMount(fn)'],
        ['useEffect(() => fn, [])','onUnmount(fn)'],
        ['useEffect 清理函数','effect 里 return']),
      ('H3','渲染'),
      ('Table',['React JSX','XuNay'],[
        ['<div>hello</div>','div(null, "hello")'],
        ['<div className="x">','div({ class: "x" })'],
        ['<div onClick={h}>','div({ on: { click: h } })'],
        ['{n}','() => n()'],
        ['{cond && <A />}','show(() => cond, () => A())'],
        ['{cond ? A : B}','() => cond ? A() : B()'],
        ['arr.map(fn)','list(arr, keyFn, fn)'],
        ['<>{a}{b}</>','frag(a, b)'],
        ['key={i.id}','list(arr, i => i.id, fn)']),
      ('H3','不需要的'),
      ('Table',['React','XuNay'],[
        ['useCallback','删掉'],
        ['React.memo','删掉'],
        ['useReducer','signal + 手写'],
        ['Suspense','show(loading, ...)'],
        ['Portals','直接操作 DOM'],
        ['StrictMode','不需要'],
        ['Hooks 顺序规则','不存在']),
      ('H2','Vue 3 → XuNay'),
      ('H3','状态'),
      ('Table',['Vue 3','XuNay'],[
        ['ref(0)','signal(0)'],
        ['n.value','n()'],
        ['n.value = 1','n(1)'],
        ['reactive({})','signal({})'],
        ['computed(fn)','computed(fn)'],
        ['watch(fn)','effect(fn)'],
        ['watchEffect(fn)','effect(fn)']),
      ('H3','生命周期'),
      ('Table',['Vue 3','XuNay'],[
        ['onMounted(fn)','onMount(fn)'],
        ['onUnmounted(fn)','onUnmount(fn)'],
        ['provide/inject','ctx']),
      ('H3','模板'),
      ('Table',['Vue 3','XuNay'],[
        ['v-if="x"','show(() => x, () => ...)'],
        ['v-else','三目或 if'],
        ['v-show="x"','style: () => ({ display: x ? "block" : "none" })'],
        ['v-for="t in list"','list(list, t => t.id, fn)'],
        ['v-model="x"','手写或 model(sig)'],
        ['@click="h"','on: { click: h }'],
        [':value="x"','value: () => x'],
        ['{{ x }}','() => x'],
        ['<template>','frag(...)'],
        ['<slot>','children 参数']),
      ('H2','通用规则'),
      ('Table',['旧习惯','新习惯'],[
        ['手动依赖数组','自动收集'],
        ['组件重渲染','组件执行一次'],
        ['虚拟 DOM','直接 DOM'],
        ['组件级更新','节点级更新'],
        ['状态管理库','全局 signal'],
        ['路由库','20 行自己写']),
      ('H2','完整示例对照'),
      ('H3','React 计数器'),
      ('Code',"function Counter() {\\n  const [n, setN] = useState(0)\\n  return (\\n    <div>\\n      <button onClick={() => setN(n - 1)}>-</button>\\n      <span>{n}</span>\\n      <button onClick={() => setN(n + 1)}>+</button>\\n    </div>\\n  )\\n}",'jsx'),
      ('H3','XuNay 计数器'),
      ('Code',"function Counter() {\\n  const n = signal(0)\\n  return div(null,\\n    button({ on: { click: () => n(v => v - 1) } }, '-'),\\n    span(null, () => String(n())),\\n    button({ on: { click: () => n(v => v + 1) } }, '+')\\n  )\\n}",'xuy'),
      ('H3','Vue 3 计数器'),
      ('Code',"<script setup>\\nimport { ref } from 'vue'\\nconst n = ref(0)\\n</script>\\n\\n<template>\\n  <div>\\n    <button @click=\"n--\">-</button>\\n    <span>{{ n }}</span>\\n    <button @click=\"n++\">+</button>\\n  </div>\\n</template>",'vue'),
      ('H3','XuNay 同上'),
      ('Code',"function Counter() {\\n  const n = signal(0)\\n  return div(null,\\n    button({ on: { click: () => n(v => v - 1) } }, '-'),\\n    span(null, () => String(n())),\\n    button({ on: { click: () => n(v => v + 1) } }, '+')\\n  )\\n}",'xuy'),
    ]),
  ('入门', ["""

s = s.replace(anchor, new_entries, 1)

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("模式库 / 反模式 / 约束清单 / 迁移对照 已填")
