import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core1", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ signal ============
swap(`    ('core-signal', 'signal', [
      ('H1','signal'),
      ('P','信号是 XuNay 的核心。读用 n()，写用 n(1)，函数式更新用 n(v => v + 1)。'),
      ('Code',"const n = signal(0)\\nn()          // 读 → 0\\nn(1)         // 写 → 1\\nn(v => v+1)  // 函数式 → 2",'js'),
    ]),`,
`    ('core-signal', 'signal', [
      ('H1','signal'),
      ('P','signal 是 XuNay 的核心。它是一个"能通知订阅者的函数"——读它返回当前值，写它修改值并通知所有读它的人。整个框架的响应式都建立在它上面。'),
      ('H2','一句话理解'),
      ('P','signal(0) 创建一个初始值为 0 的信号。当你调用 n() 时返回 0；调用 n(1) 时把值改为 1；如果某段代码在"读"这个信号的时候处于 effect 里，那么这段代码就成了订阅者，未来信号一变，它就会重跑。'),
      ('H2','基础用法'),
      ('Code',"import { signal } from 'xunay'\\n\\n// 创建\\nconst n = signal(0)\\n\\n// 读\\nn()          // → 0\\n\\n// 写\\nn(1)         // → 1\\n\\n// 函数式更新（基于旧值）\\nn(v => v + 1)  // → 2\\nn(v => v * 10) // → 20\\n\\n// 对象和数组\\nconst user = signal({ name: 'xuan' })\\nuser({ name: 'ling' })          // 整体替换\\nuser(u => ({ ...u, age: 18 }))  // 函数式展开",'xuy'),
      ('H2','写时不变更等于不触发'),
      ('P','如果新旧值相等（Object.is），signal 会直接返回，不通知订阅者。这是自动的，不需要手动判断。'),
      ('Code',"const n = signal(0)\\nn(0)   // 等于旧值，不触发任何 effect\\nn(0)   // 一样\\nn(1)   // 变了，触发",'xuy'),
      ('H2','依赖自动收集'),
      ('P','signal 不需要你写依赖数组。当你读它的时候，它在运行时知道"当前正在跑哪个 effect"，并自动把自己加进那个 effect 的依赖列表。'),
      ('Code',"import { signal, effect } from 'xunay'\\n\\nconst a = signal(1)\\nconst b = signal(2)\\n\\neffect(() => {\\n  // 这个 effect 只订阅了 a，没订阅 b\\n  console.log('a =', a())\\n  // b 没被读，所以 b 变化不会触发这里\\n})\\n\\na(10)   // 触发，打印 a = 10\\nb(20)   // 不触发",'xuy'),
      ('H2','在 JSX 风格里怎么用'),
      ('P','xunay 没有 JSX，但用法几乎一样——所有动态值都用函数包起来。signal 的读操作必须放在函数里，才会建立订阅关系。'),
      ('Code',"import { div, span, button, signal } from 'xunay'\\n\\nconst n = signal(0)\\n\\ndiv(null,\\n  button({ on: { click: () => n(v => v - 1) } }, '-'),\\n  // 用 () => n() 才能订阅\\n  span(null, () => 'n = ' + n()),\\n  button({ on: { click: () => n(v => v + 1) } }, '+')\\n)",'xuy'),
      ('Warn','不要写成 span(null, n()) —— 那样会立即取值，只显示 0，后续变化不会更新。永远用 () => n()。'),
      ('H2','常用模式'),
      ('H3','计数器'),
      ('Code',"const count = signal(0)\\ncount(v => v + 1)   // +1\\ncount(v => v - 1)   // -1\\ncount(0)             // 重置",'xuy'),
      ('H3','开关'),
      ('Code',"const open = signal(false)\\nopen(!open())       // 切换\\nopen(true)           // 强制开\\nopen(false)          // 强制关",'xuy'),
      ('H3','列表追加'),
      ('Code',"const todos = signal([])\\ntodos(list => [...list, { id: Date.now(), title: '新任务' }])",'xuy'),
      ('H3','列表删除'),
      ('Code',"const todos = signal([])\\ntodos(list => list.filter(t => t.id !== id))",'xuy'),
      ('H3','对象字段更新'),
      ('Code',"const user = signal({ name: 'x', age: 0 })\\nuser(u => ({ ...u, age: 18 }))",'xuy'),
      ('H2','订阅者计数与写入计数'),
      ('P','devtools 里会看到 "Xs Yw"，X 是订阅者数，Y 是写入次数。这两个数字是调试利器——如果某个 signal 有 100 个订阅者，每次变都会重跑 100 个 effect，就要警惕了。'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：在 effect 里写自己订阅的 signal'),
      ('Code',"const n = signal(0)\\neffect(() => {\\n  n(n() + 1)   // ✗ 无限循环！\\n})",'xuy'),
      ('P','effect 执行时读了 n，n 变化又触发 effect，effect 又写 n——死循环。解决办法：不要在同一个 effect 里读和写同一个 signal。'),
      ('H3','陷阱 2：深层对象修改不触发'),
      ('Code',"const user = signal({ profile: { name: 'x' } })\\nuser().profile.name = 'y'   // ✗ 不触发！对象引用没变\\nuser(u => ({ ...u, profile: { ...u.profile, name: 'y' } }))  // ✓ 整体替换",'xuy'),
      ('P','signal 用的是 Object.is 比较，只有顶层引用变才触发。深层修改必须手动构造新对象。'),
      ('H3','陷阱 3：在事件回调外面读'),
      ('Code',"button({ on: { click: () => console.log(n()) } })  // ✗ 事件回调不是 effect，读不会订阅\\nspan(null, () => n())                            // ✓ 在 effect 里读，会订阅",'xuy'),
      ('H2','性能'),
      ('Table',['操作','耗时','说明'],[
        ['创建','~250ns','new 一个闭包 + 分配几个变量'],
        ['读（无订阅）','~130ns','一次属性访问'],
        ['读（在 effect 里）','~200ns','加了一次 Set 操作'],
        ['写（无订阅者）','~180ns','比较 + 赋值'],
        ['写（1 个订阅者）','~650ns','触发一个 effect 重跑'],
      ]),
      ('P','这个量级的意思是：1000 次 signal 读加起来才 0.13 毫秒。相比之下，一次 DOM 写入就要 10~100 微秒。所以 signal 本身几乎不占时间，性能瓶颈在别处。'),
      ('H2','与 React / Vue 对比'),
      ('Table',['操作','XuNay','React','Vue 3'],[
        ['创建','signal(0)','useState(0)','ref(0)'],
        ['读','n()','n','n.value'],
        ['写','n(1)','setN(1)','n.value = 1'],
        ['函数式','n(v => v+1)','setN(v => v+1)','n.value++'],
        ['写时比较','自动','自动','自动'],
        ['依赖收集','运行时','手动数组','编译期'],
      ]),
      ('H2','完整示例：一个小购物车'),
      ('Code',"import { signal, computed, div, h1, button, span, ul, li, list, mount } from 'xunay'\\n\\nconst items = signal([\\n  { id: 1, name: '键盘', price: 299, qty: 1 },\\n  { id: 2, name: '鼠标', price: 99, qty: 2 }\\n])\\n\\nconst total = computed(() =>\\n  items().reduce((sum, i) => sum + i.price * i.qty, 0)\\n)\\n\\nconst setQty = (id, qty) => {\\n  items(list => list.map(i => i.id === id ? { ...i, qty } : i))\\n}\\n\\nconst remove = id => {\\n  items(list => list.filter(i => i.id !== id))\\n}\\n\\nmount(() => div(null,\\n  h1(null, '购物车'),\\n  ul(null,\\n    list(items, i => i.id, i => li(null,\\n      span(null, i.name + ' · ¥' + i.price + ' × '),\\n      button({ on: { click: () => setQty(i.id, i.qty - 1) } }, '-'),\\n      span(null, ' ' + i.qty + ' '),\\n      button({ on: { click: () => setQty(i.id, i.qty + 1) } }, '+'),\\n      button({ on: { click: () => remove(i.id) } }, '删除')\\n    ))\\n  ),\\n  div(null, '总计: ¥', () => total())\\n), '#app')",'xuy'),
      ('H2','下一步'),
      ('P','读 computed 了解如何派生新值，或直接看 effect 理解订阅机制。'),
    ]),`,
"signal")

// ============ computed ============
swap(`    ('core-computed', 'computed', []),`,
`    ('core-computed', 'computed', [
      ('H1','computed'),
      ('P','computed 是从其他 signal 派生的只读值。它自动追踪依赖、缓存结果，只在依赖变化时重新计算。'),
      ('H2','为什么要用它'),
      ('P','假设你要显示"总价"——它由 items 列表算出来。你可以每次都重新算，也可以缓存起来只在 items 变化时算。computed 就是后者。'),
      ('Code',"import { signal, computed } from 'xunay'\\n\\nconst items = signal([{ price: 10, qty: 2 }, { price: 5, qty: 3 }])\\n\\n// 每次都算（不好）\\nconst total1 = () => items().reduce((s, i) => s + i.price * i.qty, 0)\\n\\n// 缓存结果（好）\\nconst total2 = computed(() => items().reduce((s, i) => s + i.price * i.qty, 0))",'xuy'),
      ('H2','基础用法'),
      ('Code',"import { signal, computed } from 'xunay'\\n\\nconst a = signal(1)\\nconst b = signal(2)\\nconst sum = computed(() => a() + b())\\n\\nsum()   // → 3\\na(10)\\nsum()   // → 12\\nb(20)\\nsum()   // → 30",'xuy'),
      ('P','读 computed 用 sum()（加括号），写不了——它是只读的。'),
      ('H2','缓存机制'),
      ('P','computed 会在第一次读时计算结果，之后如果依赖没变就直接返回缓存值，不会重算。如果依赖变了，下次读时才重算（惰性）。'),
      ('Code',"let runs = 0\\nconst a = signal(1)\\nconst double = computed(() => { runs++; return a() * 2 })\\n\\ndouble()   // 第一次，runs = 1\\ndouble()   // 缓存，runs 还是 1\\ndouble()   // 缓存\\na(5)\\ndouble()   // 依赖变，重算，runs = 2",'xuy'),
      ('H2','依赖链'),
      ('P','computed 可以依赖其他 computed，形成链条。链条上任意一环变化都会自动传播。'),
      ('Code',"const price = signal(100)\\nconst qty = signal(3)\\nconst subtotal = computed(() => price() * qty())\\nconst tax = computed(() => subtotal() * 0.13)\\nconst total = computed(() => subtotal() + tax())\\n\\ntotal()   // → 100*3 + 100*3*0.13 = 339\\nprice(200)\\ntotal()   // → 678",'xuy'),
      ('H2','什么时候用 computed'),
      ('Table',['场景','用 signal','用 computed'],[
        ['计数器','✓',''],
        ['输入框的值','✓',''],
        ['从列表算总数','','✓'],
        ['过滤后的列表','','✓'],
        ['格式化后的字符串','','✓'],
        ['多个 signal 的组合','','✓'],
      ]),
      ('P','规则：能写的用 signal，只读的用 computed。'),
      ('H2','computed 与 React useMemo 对比'),
      ('Table',['','XuNay computed','React useMemo'],[
        ['依赖','自动追踪','手写数组 [a, b]'],
        ['忘记依赖','不存在','常见 bug'],
        ['缓存','自动','自动'],
        ['响应式','是，会触发更新','否，只是避免重算'],
        ['返回值','可以直接调用','是普通值'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：在 computed 里写 signal'),
      ('Code',"const n = signal(0)\\nconst bad = computed(() => {\\n  n(5)   // ✗ 副作用！computed 应该只读\\n  return n()\\n})",'xuy'),
      ('P','computed 只应该纯计算——读信号，返回结果，不要写。写操作放事件回调里。'),
      ('H3','陷阱 2：忘了调用'),
      ('Code',"const double = computed(() => n() * 2)\\ndouble        // ✗ 是函数本身\\ndouble()      // ✓ 是值",'xuy'),
      ('P','这是从 React / Vue 过来最容易犯的错。signal 和 computed 都必须加 () 才是值。'),
      ('H3','陷阱 3：依赖不确定'),
      ('Code',"const showA = signal(true)\\nconst a = signal(1)\\nconst b = signal(2)\\nconst val = computed(() => {\\n  if (showA()) return a()\\n  return b()\\n})\\n\\n// 现在依赖是 [showA, a]\\nshowA(false)\\n// 依赖变成 [showA, b]，a 不再触发它",'xuy'),
      ('P','运行时动态切换依赖是支持的——computed 每次重算都会重新收集依赖。但如果依赖集合不稳定，性能会有波动。'),
      ('H2','与 effect 的区别'),
      ('Table',['','computed','effect'],[
        ['返回值','有','没有'],
        ['触发','读时惰性计算','依赖一变就立即跑'],
        ['缓存','有','无'],
        ['用途','派生值','副作用'],
        ['能在 JSX 里读','✓','✗'],
      ]),
      ('H2','完整示例：过滤 + 排序 + 统计'),
      ('Code',"import { signal, computed } from 'xunay'\\n\\nconst todos = signal([\\n  { id: 1, title: '写文档', done: false, priority: 1 },\\n  { id: 2, title: '修 bug', done: true, priority: 3 },\\n  { id: 3, title: '开会', done: false, priority: 2 }\\n])\\n\\nconst filter = signal('all')      // all / active / done\\nconst sortBy = signal('priority')  // priority / title\\n\\n// 第一步：过滤\\nconst filtered = computed(() => {\\n  const list = todos()\\n  const f = filter()\\n  if (f === 'active') return list.filter(t => !t.done)\\n  if (f === 'done') return list.filter(t => t.done)\\n  return list\\n})\\n\\n// 第二步：排序\\nconst sorted = computed(() => {\\n  const list = [...filtered()]\\n  if (sortBy() === 'priority') list.sort((a, b) => a.priority - b.priority)\\n  else list.sort((a, b) => a.title.localeCompare(b.title))\\n  return list\\n})\\n\\n// 第三步：统计\\nconst stats = computed(() => {\\n  const list = todos()\\n  return {\\n    total: list.length,\\n    active: list.filter(t => !t.done).length,\\n    done: list.filter(t => t.done).length\\n  }\\n})\\n\\n// 完整链条：todos / filter / sortBy → filtered → sorted\\n// 改 filter，只有 sorted 会重算，stats 不变\\n// 改 sortBy，只有 sorted 重算\\n// 改 todos，全部重算",'xuy'),
      ('H2','下一步'),
      ('P','读 effect 理解副作用和生命周期，或看 batch 了解如何合并多次更新。'),
    ]),`,
"computed")

// ============ effect ============
swap(`    ('core-effect', 'effect', []),`,
`    ('core-effect', 'effect', [
      ('H1','effect'),
      ('P','effect 是"会自动重跑的副作用"——它执行时读到的 signal 都会成为依赖，那些 signal 变化时，effect 自动重跑。'),
      ('H2','和 signal 的关系'),
      ('P','signal 负责"变"，effect 负责"跑"。当你在 effect 里读一个 signal，就等于订阅了它。它变了，effect 就重跑。'),
      ('Code',"import { signal, effect } from 'xunay'\\n\\nconst n = signal(0)\\n\\neffect(() => {\\n  console.log('n =', n())   // 读了 n，订阅它\\n})\\n// 立即执行一次 → 打印 n = 0\\n\\nn(1)\\n// n 变 → effect 重跑 → 打印 n = 1",'xuy'),
      ('H2','自动依赖收集'),
      ('P','不需要写依赖数组。effect 执行时哪个 signal 被读了，就自动订阅哪个。下次重跑时依赖会重新收集——旧的依赖会被清掉，新的加上。'),
      ('Code',"const useA = signal(true)\\nconst a = signal(1)\\nconst b = signal(2)\\n\\neffect(() => {\\n  if (useA()) console.log('a =', a())\\n  else console.log('b =', b())\\n})\\n// 执行一次，依赖 = [useA, a]\\n\\nb(10)      // 不触发，因为 b 没被读\\nuseA(false)\\n// 重跑，依赖变成 [useA, b]\\na(5)       // 不触发，因为 a 不再被读\\nb(20)      // 触发",'xuy'),
      ('H2','返回清理函数'),
      ('P','effect 可以返回一个函数，它会在下次重跑前、或 effect dispose 时执行。适合清理定时器、事件监听、订阅。'),
      ('Code',"import { signal, effect } from 'xunay'\\n\\nconst interval = signal(1000)\\n\\neffect(() => {\\n  const id = setInterval(() => console.log('tick'), interval())\\n  return () => clearInterval(id)   // 下次重跑前清理旧的\\n})\\n\\ninterval(500)\\n// 旧定时器被清理，新定时器 500ms\\n\\n// dispose 时也会清理\\nconst stop = effect(() => { ... })\\nstop()   // 触发清理",'xuy'),
      ('H2','与组件生命周期'),
      ('P','每个 effect 属于某个 scope（作用域）。DOM 节点挂载时创建 scope，卸载时自动 dispose 所有子 effect。所以大部分情况下不用手动清理。'),
      ('Code',"import { div, effect, onUnmount } from 'xunay'\\n\\nfunction Timer() {\\n  const n = signal(0)\\n  // effect 属于这个组件的 scope\\n  effect(() => {\\n    const id = setInterval(() => n(v => v + 1), 1000)\\n    return () => clearInterval(id)\\n  })\\n  return div(null, () => '秒数: ' + n())\\n  // 组件卸载时，effect 自动清理\\n}",'xuy'),
      ('H2','什么时候用 effect'),
      ('Table',['场景','该用什么'],[
        ['计算派生值','computed，不是 effect'],
        ['同步到 localStorage','effect'],
        ['订阅外部事件','effect'],
        ['启动定时器','effect'],
        ['打日志','effect'],
        ['发请求','onMount 或 async 回调'],
      ]),
      ('H2','effect vs React useEffect'),
      ('Table',['','XuNay effect','React useEffect'],[
        ['依赖数组','无，自动','必须有'],
        ['空依赖','不写就行','[]'],
        ['首次执行','默认执行','默认执行'],
        ['清理','return 函数','return 函数'],
        ['清理时机','重跑前 + dispose','重跑前 + 卸载'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：在 effect 里读又写同一个 signal'),
      ('Code',"const n = signal(0)\\neffect(() => {\\n  console.log(n())\\n  n(n() + 1)   // ✗ 死循环\\n})",'xuy'),
      ('P','写操作触发重跑，重跑又写——永远停不下来。如果确实需要更新，用 setTimeout 或放在事件回调里。'),
      ('H3','陷阱 2：忘记读就以为订阅了'),
      ('Code',"const n = signal(0)\\neffect(() => {\\n  // 没有读 n，不订阅\\n  setTimeout(() => console.log(n()), 100)\\n})\\nn(1)   // 不会触发 effect",'xuy'),
      ('P','只有 effect 的同步执行阶段读的 signal 才订阅。异步回调里读不算（因为 effect 已经执行完了）。'),
      ('H3','陷阱 3：在 effect 里访问 DOM 但 DOM 还没挂载'),
      ('P','effect 在 mount 之前就跑了，此时 DOM 不在文档里。要访问 DOM 用 onMount。'),
      ('Code',"effect(() => {\\n  document.querySelector('.x')   // ✗ 可能 null\\n})\\nonMount(() => {\\n  document.querySelector('.x')   // ✓ 挂载完再跑\\n})",'xuy'),
      ('H2','性能'),
      ('P','effect 的重跑有成本——每次都要清理旧依赖、收集新依赖、执行函数体。如果依赖很多，成本线性增加。'),
      ('P','一条经验：一个 effect 里读的 signal 不要超过 10 个。超过就要考虑拆分——大 effect 拆成几个小 effect，各自只管一件事。'),
      ('H2','手动停止'),
      ('Code',"const stop = effect(() => {\\n  console.log('running')\\n})\\n\\n// 停止\\nstop()\\n// 之后的 signal 变化不再触发",'xuy'),
      ('P','组件 scope 会自动 dispose 内部的 effect。只有顶层 effect（不在组件里）需要手动 stop。'),
      ('H2','完整示例：自动保存草稿'),
      ('Code',"import { signal, effect, div, textarea, span, mount } from 'xunay'\\n\\nfunction Editor() {\\n  // 从 localStorage 恢复\\n  const draft = signal(localStorage.getItem('draft') || '')\\n  const saved = signal('')\\n\\n  // 每次 draft 变，延迟 500ms 保存\\n  effect(() => {\\n    const text = draft()\\n    const id = setTimeout(() => {\\n      localStorage.setItem('draft', text)\\n      saved(new Date().toLocaleTimeString())\\n    }, 500)\\n    return () => clearTimeout(id)\\n  })\\n\\n  return div(null,\\n    textarea({\\n      value: () => draft(),\\n      on: { input: e => draft(e.target.value) }\\n    }),\\n    span(null, () => saved() ? '已保存于 ' + saved() : '未保存')\\n  )\\n}\\n\\nmount(() => Editor(), '#app')",'xuy'),
      ('H2','下一步'),
      ('P','读 batch 了解如何把多次 signal 写合并成一次更新。'),
    ]),`,
"effect")

writeFileSync(p, s)
console.log("signal / computed / effect 三篇已填")
