import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core3", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ props ============
swap(`    ('core-props', '属性', []),`,
`    ('core-props', '属性', [
      ('H1','属性'),
      ('P','属性是传给元素的配置对象——class、id、style、事件、自定义 data-*。xunay 的属性语法和原生 HTML 接近，但多了动态绑定。'),
      ('H2','基础用法'),
      ('Code',"div({\\n  class: 'card',\\n  id: 'main',\\n  title: '悬停提示'\\n}, '内容')",'xuy'),
      ('P','静态属性直接写值，会在 render 时一次性 setAttribute。'),
      ('H2','动态属性'),
      ('P','想让属性跟 signal 变化，值写成函数。框架会自动建一个 effect，只在值变化时更新那一个属性。'),
      ('Code',"div({\\n  class: () => 'card ' + (open() ? 'open' : 'closed'),\\n  id: () => 'item-' + n(),\\n  disabled: () => n() > 10,\\n  hidden: () => !visible()\\n})",'xuy'),
      ('H2','属性自动分派'),
      ('P','xunay 不是什么都 setAttribute——某些 key 走特殊处理，跟原生 DOM 行为一致。'),
      ('Table',['属性','处理方式'],[
        ['class / className','dom.className = 值'],
        ['style（对象）','Object.assign(dom.style, 值)'],
        ['style（字符串）','setAttribute'],
        ['value','dom.value = 值'],
        ['checked / disabled / selected','强转 !! 后赋值'],
        ['html','dom.innerHTML = 值（有 XSS 风险）'],
        ['on','事件绑定（不 setAttribute）'],
        ['ref','获取真实 DOM 引用'],
        ['其他','setAttribute(k, v)'],
      ]),
      ('Warn','html 属性会直接写 innerHTML。如果值来自用户输入，必须先转义。xunay 不自动 sanitize。'),
      ('H2','class 的三种写法'),
      ('Code',"// 1. 静态字符串\\ndiv({ class: 'card' })\\n\\n// 2. 动态字符串\\ndiv({ class: () => 'card ' + variant() })\\n\\n// 3. 对象（key 是类名，值决定加不加）\\ndiv({ class: { card: true, active: () => n() > 0 } })",'xuy'),
      ('H2','style 的两种写法'),
      ('Code',"// 1. 静态对象（对象在 props 创建时求值）\\ndiv({ style: { color: 'red', fontSize: '14px' } })\\n\\n// 2. 动态函数（每次依赖变都重新 assign）\\ndiv({ style: () => ({ color: n() > 0 ? 'red' : 'blue' }) })",'xuy'),
      ('H2','事件绑定'),
      ('P','所有事件放在 on 对象里。事件名是原生事件名（click、input、keydown...）。'),
      ('Code',"button({\\n  on: {\\n    click: e => console.log('点击', e),\\n    mouseenter: () => hover(true),\\n    mouseleave: () => hover(false)\\n  }\\n}, '按钮')",'xuy'),
      ('H2','布尔属性'),
      ('P','disabled、checked、selected、hidden 这类布尔属性，xunay 自动强转。'),
      ('Code',"input({ disabled: true })          // dom.disabled = true\\ninput({ disabled: false })         // dom.disabled = false\\ninput({ disabled: () => !valid() }) // 响应式",'xuy'),
      ('H2','data-* 和 aria-*'),
      ('Code',"div({\\n  'data-id': '42',\\n  'data-type': 'user',\\n  'aria-label': '关闭',\\n  'aria-hidden': 'true'\\n})",'xuy'),
      ('H2','移除属性'),
      ('P','传 null、undefined 或 false 时移除属性：'),
      ('Code',"div({ title: null })        // 移除 title\\ndiv({ title: undefined })   // 移除\\ndiv({ title: false })       // 移除（除布尔属性）",'xuy'),
      ('H2','动态属性和 effect 的关系'),
      ('P','一个元素上的多个动态属性会合并成一个 effect——只会重跑一次，不会每个属性各建一个。'),
      ('Code',"div({\\n  class: () => a() ? 'x' : 'y',\\n  id: () => b(),\\n  title: () => c()\\n})\\n// a 或 b 或 c 变化 → 只跑 1 个 effect → 更新 3 个属性",'xuy'),
      ('H2','ref 属性'),
      ('P','ref 用来拿真实 DOM 引用。传一个回调，元素挂载时被调用。'),
      ('Code',"import { ref } from 'xunay'\\n\\nconst inputRef = ref()\\n\\ninput({\\n  ref: el => { inputRef(el); el.focus() },\\n  placeholder: '自动聚焦'\\n})\\n\\n// 之后\\ninputRef()   // 拿到真实 input 元素",'xuy'),
      ('H2','性能'),
      ('P','静态属性只 setAttribute 一次；动态属性每个元素建一个 effect，多个属性共享。'),
      ('Table',['情况','成本'],[
        ['3 个静态属性','3 次 setAttribute'],
        ['1 个动态属性','1 个 effect，值变化时 1 次赋值'],
        ['3 个动态属性','1 个 effect，值变化时 3 次赋值'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：动态属性忘记加 ()'),
      ('Code',"div({ class: () => open() ? 'open' : '' })   // ✓\\ndiv({ class: open() ? 'open' : '' })          // ✗ 静态求值，不响应",'xuy'),
      ('H3','陷阱 2：on 里的函数写错'),
      ('Code',"// ✓ 传函数引用\\nbutton({ on: { click: handler } })\\n\\n// ✓ 传箭头函数\\nbutton({ on: { click: () => n(v => v + 1) } })\\n\\n// ✗ 立即执行了\\nbutton({ on: { click: handler() } })",'xuy'),
      ('H3','陷阱 3：html 属性'),
      ('Code',"div({ html: '<b>你好</b>' })                    // ✓ 但会解析 HTML\\ndiv({ html: userInput })                     // ⚠ 有 XSS 风险\\ndiv({ html: () => escapeHtml(userInput) })    // ✓ 手动转义",'xuy'),
      ('H2','完整示例：可搜索输入框'),
      ('Code',"import { div, input, ul, li, span, signal, list, show, mount } from 'xunay'\\n\\nfunction Search() {\\n  const q = signal('')\\n  const focus = signal(false)\\n  const items = ['苹果', '香蕉', '橙子', '葡萄']\\n  const results = () => items.filter(i => i.includes(q()))\\n\\n  return div({ class: () => 'search ' + (focus() ? 'focus' : '') },\\n    input({\\n      class: 'search-input',\\n      placeholder: '搜索…',\\n      value: () => q(),\\n      on: {\\n        input: e => q(e.target.value),\\n        focus: () => focus(true),\\n        blur: () => setTimeout(() => focus(false), 200),\\n        keydown: e => { if (e.key === 'Escape') q('') }\\n      }\\n    }),\\n    show(() => focus() && q(), () =>\\n      ul({ class: 'results' },\\n        list(results(), i => i, i => li(null, i))\\n      )\\n    )\\n  )\\n}\\n\\nmount(() => Search(), '#app')",'xuy'),
    ]),`,
"props")

// ============ children ============
swap(`    ('core-children', '子节点', []),`,
`    ('core-children', '子节点', [
      ('H1','子节点'),
      ('P','子节点是元素的"内容"。可以是文本、数字、嵌套元素、动态函数、列表、条件——xunay 自动判断类型并做对应处理。'),
      ('H2','六种子节点类型'),
      ('Table',['类型','例子','处理方式'],[
        ['字符串','"hello"','创建文本节点，永不更新'],
        ['数字','42','转字符串建文本节点'],
        ['vnode','h1(null, "标题")','递归渲染成 DOM'],
        ['函数','() => n()','建 effect，值变化时更新'],
        ['列表','list(arr, key, fn)','keyed diff'],
        ['条件','show(cond, fn)','挂载/卸载切换'],
      ]),
      ('H2','静态子节点'),
      ('Code',"div(null,\\n  '文本',\\n  42,\\n  true ? h1(null, 'yes') : h1(null, 'no'),\\n  h1(null, '嵌套')\\n)",'xuy'),
      ('P','这些都只 render 一次，后续永不更新。'),
      ('H2','动态子节点'),
      ('Code',"const n = signal(0)\\n\\ndiv(null,\\n  () => n(),                  // 动态文本\\n  () => 'n = ' + n(),          // 动态字符串\\n  () => n() > 0 ? '正' : '负',  // 动态条件（短字符串）\\n  () => n() > 0 ? h1(null, '正') : h1(null, '负')  // 动态元素\\n)",'xuy'),
      ('H2','函数返回不同类型的行为'),
      ('P','函数返回什么是关键——渲染器会按类型分派。'),
      ('Table',['返回','行为'],[
        ['字符串/数字','建文本节点，只改 textContent'],
        ['vnode','整块重建（每次依赖变都重建 DOM）'],
        ['null / false','建空文本节点'],
        ['列表对象','走 applyList'],
        ['show 对象','走 renderShow'],
      ]),
      ('Warn','函数返回 vnode 每次都会重建整块。大子树别放函数里——用 show 或 list 替代。'),
      ('H2','fragment 多节点'),
      ('Code',"import { frag } from 'xunay'\\n\\nfrag(\\n  h1(null, '标题'),\\n  p(null, '正文'),\\n  button(null, '按钮')\\n)",'xuy'),
      ('P','frag 不产生真实 DOM 节点（内部用 display:contents 的 span 做占位）。'),
      ('H2','children 的排序'),
      ('Code',"div(null, 'a', 'b', 'c')\\n// 输出三个子节点：a、b、c\\n\\ndiv(null, () => n(), '常量')\\n// 第一个是动态，第二个是静态",'xuy'),
      ('H2','空子节点'),
      ('Code',"div(null)                  // 无子节点\\ndiv(null, null)             // 忽略 null\\ndiv(null, false)            // 忽略 false\\ndiv(null, undefined)        // 忽略\\ndiv(null, '')               // 空字符串也是文本节点",'xuy'),
      ('H2','子节点里的函数执行时机'),
      ('P','框架构建元素时，遇到函数会先执行一次，判断返回类型。这次执行被"隔离"了——它读的 signal 不会污染父 effect（这是之前修过的 bug）。'),
      ('Code',"const n = signal(0)\\ndiv(null,\\n  () => n()   // 探针执行时读 n，但不订阅父级\\n)\\nn(1)   // 只会重跑这个函数节点，父 div 不动",'xuy'),
      ('H2','children 与 key'),
      ('P','xunay 没有 React 那种 key 属性。列表用 list(arr, keyFn, fn)，key 由 keyFn 显式提供。'),
      ('Code',"list(items, i => i.id, i => li(null, i.title))\\n//         ↑ key 函数",'xuy'),
      ('H2','嵌套结构'),
      ('Code',"div({ class: 'card' },\\n  div({ class: 'header' },\\n    h1(null, '标题'),\\n    span(null, '副标题')\\n  ),\\n  div({ class: 'body' },\\n    p(null, '正文内容'),\\n    ul(null,\\n      li(null, '第一项'),\\n      li(null, '第二项')\\n    )\\n  )\\n)",'xuy'),
      ('H2','常见的 children 模式'),
      ('H3','条件内容'),
      ('Code',"show(() => user(), () => div(null, '你好，' + user().name))\\n// 或\\n() => user() ? div(null, '你好') : null",'xuy'),
      ('P','两者都可。show 更省内存（切换时 scope 干净），三目更短。'),
      ('H3','列表 + 空态'),
      ('Code',"div(null,\\n  show(() => items().length === 0, () => p(null, '暂无数据')),\\n  ul(null, list(items, i => i.id, i => li(null, i.title)))\\n)",'xuy'),
      ('H3','动态子节点数量'),
      ('Code',"div(null,\\n  ...items.map(i => li(null, i.title))   // 静态展开，items 变了不会更新\\n)\\n// 想要响应，用 list",'xuy'),
      ('Warn','...items.map 展开是静态的。items 后来变了不会重新展开——每次都要用 list。'),
      ('H2','性能'),
      ('Table',['子节点','每次父更新成本'],[
        ['静态文本','0'],
        ['静态 vnode','0'],
        ['动态文本函数','1 次 textContent 赋值'],
        ['动态 vnode 函数','整块 DOM 重建'],
        ['list','keyed diff，只动变化项'],
      ]),
      ('H2','完整示例：多层评论树'),
      ('Code',"import { div, span, p, button, signal, list, show, mount } from 'xunay'\\n\\nconst comments = signal([\\n  { id: 1, user: '小明', text: '真不错', replies: [\\n    { id: 11, user: '小红', text: '同意' }\\n  ]}\\n])\\n\\nfunction Comment({ c }) {\\n  return div({ class: 'comment' },\\n    div({ class: 'head' }, span(null, c.user)),\\n    p(null, c.text),\\n    show(() => c.replies && c.replies.length, () =>\\n      div({ class: 'replies' },\\n        list(c.replies, r => r.id, r => Comment({ c: r }))\\n      )\\n    )\\n  )\\n}\\n\\nmount(() => div(null,\\n  list(comments, c => c.id, c => Comment({ c }))\\n), '#app')",'xuy'),
    ]),`,
"children")

// ============ show ============
swap(`    ('core-show', '条件渲染', []),`,
`    ('core-show', '条件渲染', [
      ('H1','条件渲染'),
      ('P','show(cond, renderFn) 按条件挂载/卸载一段 DOM。cond 是真值时渲染，假值时移除——跟 v-if 一个意思。'),
      ('H2','基础用法'),
      ('Code',"import { show, div } from 'xunay'\\n\\nshow(() => n() > 0, () => div(null, '正数'))\\n// n() > 0 时显示 div，否则不显示",'xuy'),
      ('H2','两个参数'),
      ('Table',['参数','类型','作用'],[
        ['cond','() => boolean','条件函数，会自动订阅依赖'],
        ['renderFn','() => vnode','条件为真时渲染的内容'],
      ]),
      ('H2','show vs 三目表达式'),
      ('Code',"// 方式 A：show\\nshow(() => open(), () => div(null, '内容'))\\n\\n// 方式 B：三目\\n() => open() ? div(null, '内容') : null",'xuy'),
      ('Table',['','show','三目'],[
        ['切换成本','卸载/挂载 scope','重建整块'],
        ['清理','自动 dispose','随父重建'],
        ['内存','切换时释放','随父重建释放'],
        ['代码','稍长','短'],
        ['适合','复杂子树','简短内容'],
      ]),
      ('P','复杂子树用 show（切换干净）；简单的单行文本用三目更短。'),
      ('H2','show 的生命周期'),
      ('P','cond 变真 → 建 scope → 挂载 → onMount 触发；cond 变假 → onUnmount 触发 → dispose scope → 移除 DOM。'),
      ('Code',"show(() => visible(), () => {\\n  // 这个 div 每次显示都会重新创建\\n  onMount(() => console.log('挂载'))\\n  onUnmount(() => console.log('卸载'))\\n  return div(null, '内容')\\n})",'xuy'),
      ('H2','嵌套 show'),
      ('Code',"show(() => loggedIn(), () =>\\n  div(null,\\n    '已登录',\\n    show(() => hasPermission(), () => button(null, '管理'))\\n  )\\n)",'xuy'),
      ('H2','show 的简写'),
      ('Code',"// 两种写法等价：\\nshow(() => open(), () => div(null, 'x'))\\n\\n// 但注意：不要写成\\nshow(open(), () => div(null, 'x'))   // ✗ 静态条件，不会更新",'xuy'),
      ('H2','多条件分支'),
      ('P','show 只能处理"显示/隐藏"。三个以上分支用函数返回不同 vnode：'),
      ('Code',"() => {\\n  const s = status()\\n  if (s === 'loading') return div(null, '加载中...')\\n  if (s === 'error') return div(null, '出错了')\\n  if (s === 'empty') return div(null, '无数据')\\n  return ul(null, list(items, i => i.id, i => li(null, i.title)))\\n}",'xuy'),
      ('H2','切换动画'),
      ('P','show 切换没有内置过渡。需要动画时用 trans：'),
      ('Code',"import { show, trans } from 'xunay'\\n\\nconst fade = trans(200)\\n\\nshow(() => open(), () => {\\n  const el = div(null, '内容')\\n  // 手动处理进入/离开\\n  onMount(() => fade.enter(el))\\n  onUnmount(() => fade.leave(el))\\n  return el\\n})",'xuy'),
      ('P','或者用 CSS transition——给 show 内的元素加类和过渡。'),
      ('H2','多个 show 组合'),
      ('Code',"div(null,\\n  show(() => loading(), () => div({ class: 'spinner' })),\\n  show(() => error(), () => div({ class: 'error' }, () => error())),\\n  show(() => !loading() && !error(), () => ul(null, ...))\\n)",'xuy'),
      ('H2','性能'),
      ('Table',['切换','成本'],[
        ['假→真','建 scope + 渲染 + appendChild'],
        ['真→假','dispose scope + removeChild'],
        ['频繁切换','每次都是新 DOM，注意内存'],
        ['静态内容','成本可忽略'],
        ['大子树','首渲染成本 = 树大小'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：条件传值而非函数'),
      ('Code',"show(open(), () => div())          // ✗ open() 立即取值，条件不变\\nshow(() => open(), () => div())    // ✓",'xuy'),
      ('H3','陷阱 2：cond 里的函数执行有副作用'),
      ('Code',"show(() => {\\n  fetch('/api')   // ✗ 每次 cond 重跑都发请求\\n  return n() > 0\\n}, () => div())",'xuy'),
      ('P','cond 应该纯读取——不要在里面发请求、改 signal、操作 DOM。'),
      ('H3','陷阱 3：和 v-if 一样的"状态重置"'),
      ('Code',"show(() => visible(), () => {\\n  const count = signal(0)   // ✗ 隐藏再显示会重新创建，值回到 0\\n  return div(null, () => count())\\n})",'xuy'),
      ('P','show 每次切换都重建子树，内部 signal 会重置。需要保留状态时把 signal 提到外面。'),
      ('H2','完整示例：登录模态框'),
      ('Code',"import { div, button, input, signal, show, mount } from 'xunay'\\n\\nconst modalOpen = signal(false)\\nconst user = signal('')\\nconst pass = signal('')\\nconst error = signal('')\\n\\nasync function login() {\\n  error('')\\n  try {\\n    const r = await fetch('/api/login', {\\n      method: 'POST',\\n      headers: { 'Content-Type': 'application/json' },\\n      body: JSON.stringify({ user: user(), pass: pass() })\\n    })\\n    if (!r.ok) throw new Error('HTTP ' + r.status)\\n    modalOpen(false)\\n  } catch (e) {\\n    error(e.message)\\n  }\\n}\\n\\nmount(() => div(null,\\n  button({ on: { click: () => modalOpen(true) } }, '登录'),\\n  show(() => modalOpen(), () => div({ class: 'modal' },\\n    div({ class: 'modal-body' },\\n      input({ placeholder: '用户名', value: () => user(), on: { input: e => user(e.target.value) } }),\\n      input({ type: 'password', placeholder: '密码', value: () => pass(), on: { input: e => pass(e.target.value) } }),\\n      show(() => error(), () => div({ class: 'error' }, () => error())),\\n      button({ on: { click: login } }, '提交'),\\n      button({ on: { click: () => modalOpen(false) } }, '取消')\\n    )\\n  ))\\n), '#app')",'xuy'),
    ]),`,
"show")

writeFileSync(p, s)
console.log("props / children / show 三篇已填")
