#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

# misc-philosophy
swap("    ('misc-philosophy', '设计哲学', []),", r"""    ('misc-philosophy', '设计哲学', [
      ('H1','设计哲学'),
      ('P','xunay 的核心不是"技术领先"，是"有意识地做减法"。'),
      ('H2','五条原则'),
      ('Ul',
        '不发明新语法——.xuy 就是 JS',
        '不做无用抽象——只有 signal 和元素',
        '不保留历史包袱——不兼容 React',
        '不用编译期魔法——纯运行时依赖收集',
        '不追求万能——90% 场景够用就好'),
      ('H2','为什么要"不做"'),
      ('P','React 47KB / Vue 34KB——每个功能都是负担。用户每次看文档、每次调试 bug，都在为这些功能付出成本。'),
      ('Quote','每去掉一层抽象，就少一份认知负担，少一次性能损耗，少一类边界 bug。'),
      ('H2','和主流框架的取舍'),
      ('Table',['框架','核心','代价'],[
        ['React','组件重渲染 + VDOM','概念多、性能一般'],
        ['Vue','编译 + 响应式','需要编译、生态绑定'],
        ['Solid','编译期响应式','必须编译、调试难'],
        ['Svelte','编译 + 无运行时','编译复杂、限制多'],
        ['XuNay','纯运行时响应式','无生态、无编译优化']),
      ('H2','三条"不做"'),
      ('H3','不做 SSR 框架'),
      ('P','SSR 是工具，不是框架级功能。给 renderToString 和 hydrate，让用户自己决定怎么用。'),
      ('H3','不做状态管理'),
      ('P','signal 提到模块顶层就是全局状态。不需要 Redux / Pinia。'),
      ('H3','不做路由'),
      ('P','20 行代码能写出来的东西不做框架内置。'),
      ('H2','什么时候不用 xunay'),
      ('Ul',
        '需要庞大生态（Ant Design 那种）',
        '需要 SSR + 复杂数据层',
        '团队已经熟悉 React / Vue',
        '需要面试时"用了什么"'),
      ('H2','什么时候用'),
      ('Ul',
        '个人项目 / 小工具',
        '内部后台 / 仪表盘',
        '想学"响应式的本质"',
        '想要最小心智模型'),
    ]),""", "misc-philosophy")

# misc-perf
swap("    ('misc-perf', '性能报告', []),", r"""    ('misc-perf', '性能报告', [
      ('H1','性能报告'),
      ('P','xunay 核心运行时的实测数据。'),
      ('H2','signal 操作'),
      ('Table',['操作','耗时','ops/s'],[
        ['signal 创建','228 ns','4.4M'],
        ['signal 读','128 ns','7.8M'],
        ['signal 写（无订阅）','183 ns','5.5M'],
        ['signal 写 → 触发 effect','650 ns','1.5M'],
        ['computed 读','230 ns','4.3M'],
        ['computed 写触发','1.3 µs','0.79M'],
        ['batch 两写合并','4.8 µs','0.21M']),
      ('H2','对比 React'),
      ('Table',['操作','XuNay','React'],[
        ['读状态','128 ns','Hook 调度 ~50 ns'],
        ['写状态','183 ns','调度 + Diff ~50 µs'],
        ['更新 1 个文本节点','1 µs','~10 µs ~ 5 ms']),
      ('H2','对比 Solid'),
      ('Table',['操作','XuNay','Solid'],[
        ['signal 读','128 ns','50 ~ 100 ns'],
        ['signal 写→触发','650 ns','200 ~ 300 ns']),
      ('P','Solid 用编译期优化——它知道每个 signal 在哪用，直接生成代码。xunay 纯运行时——依赖收集在运行时完成。这是架构差异，不是 bug。'),
      ('H2','包体积'),
      ('Table',['文件','gzip'],[
        ['xunay.esm.js','5.9 KB'],
        ['xunay.min.js','6.2 KB'],
        ['xunay-kit.min.js','14.5 KB'],
        ['xunay-devtools.min.js','3.9 KB'],
        ['xunay-full.min.js','19.4 KB']),
      ('H2','1000 项列表'),
      ('Table',['操作','耗时'],[
        ['首次渲染','~40 ms'],
        ['追加 1 项','~0.5 ms'],
        ['删除 1 项','~0.5 ms'],
        ['改 1 项属性','~0.3 ms'],
        ['全重排','~8 ms']),
      ('H2','性能瓶颈在哪'),
      ('P','真实应用里，性能瓶颈通常在：'),
      ('Ul',
        '网络请求（几十到几百 ms）',
        'DOM 操作（每次 10~100 µs）',
        '图片/字体加载（几百 ms）',
        '第三方库'),
      ('P','signal 本身几乎不占时间——1000 次读才 0.13 ms。'),
    ]),""", "misc-perf")

# misc-security
swap("    ('misc-security', '安全', []),", r"""    ('misc-security', '安全', [
      ('H1','安全'),
      ('P','xunay 的安全责任——哪些它管，哪些要用户自己管。'),
      ('H2','xunay 管的'),
      ('Ul',
        'html 属性默认会经过 sanitize（白名单过滤）',
        'setAttribute 不会执行脚本',
        '事件只绑在 DOM 元素上，不 eval'),
      ('H2','xunay 不管的'),
      ('Table',['场景','责任'],[
        ['用户输入直接 set innerHTML','用户'],
        ['API 认证','用户'],
        ['CSRF 保护','用户'],
        ['XSS 转义','用户（除非用 html 属性）']),
      ('H2','html 属性'),
      ('P','html 属性会写 innerHTML。xunay 提供 sanitize 白名单，只放行安全标签：'),
      ('Code',"// 允许的标签\na b i em strong p br hr ul ol li\nh1 h2 h3 h4 h5 h6 code pre blockquote\nspan div table thead tbody tr td th img\n\n// 允许的属性\nhref src alt title class id\n\n// 移除 javascript: 协议\n// 移除 <script> <iframe>",'txt'),
      ('H2','用 text 而不是 html'),
      ('P','大部分场景不需要 HTML——直接写文本就安全：'),
      ('Code',"// 安全：文本节点\nspan(null, userInput)\n\n// 危险：innerHTML（虽然会 sanitize，但白名单有限）\ndiv({ html: userInput })",'xuy'),
      ('H2','认证'),
      ('P','四套后端都用 token——用 HTTPS 传输。'),
      ('H3','token 存储'),
      ('Table',['方式','安全','场景'],[
        ['内存（signal）','最安全','SPA'],
        ['sessionStorage','中','同标签页'],
        ['localStorage','有风险','持久登录'],
        ['Cookie HttpOnly','最安全','传统方案']),
      ('H2','CORS'),
      ('P','后端要明确允许的源——不要用 *。'),
      ('Code',"app.add_middleware(\n    CORSMiddleware,\n    allow_origins=['https://example.com'],   # 不要用 '*'\n    allow_methods=['GET', 'POST'],\n    allow_headers=['Content-Type', 'Authorization']\n)",'py'),
      ('H2','XSS 防护清单'),
      ('Ul',
        '用户输入永远不直接写 innerHTML',
        '用 textContent 而不是 innerHTML',
        'html 属性只放可信内容',
        '用 CSP 头限制脚本来源',
        'Cookie 加 HttpOnly + Secure + SameSite'),
      ('H2','CSRF 防护'),
      ('P','用 token 认证而非 cookie 认证——天然防 CSRF。'),
      ('H2','SQL 注入'),
      ('P','始终用参数化查询：'),
      ('Code',"# 错误\nconn.execute(f\"SELECT * FROM todos WHERE id = {id}\")\n\n# 正确\nconn.execute('SELECT * FROM todos WHERE id = ?', (id,))",'py'),
    ]),""", "misc-security")

# misc-contribute
swap("    ('misc-contribute', '贡献指南', []),", r"""    ('misc-contribute', '贡献指南', [
      ('H1','贡献指南'),
      ('P','xunay 是一个开源项目——欢迎任何形式的贡献。'),
      ('H2','贡献方式'),
      ('Ul',
        '报告 bug',
        '提功能建议',
        '改文档',
        '写测试',
        '改进代码',
        '翻译'),
      ('H2','报告 bug'),
      ('P','提供以下信息：'),
      ('Ul',
        '预期行为',
        '实际行为',
        '复现代码（最短）',
        '环境（浏览器 / Node 版本）'),
      ('H2','提 PR'),
      ('Code',"# 1. fork\n# 2. clone\ngit clone https://github.com/yourname/xunay\n\n# 3. 分支\ngit checkout -b fix-something\n\n# 4. 改\n# 5. 测试\nnode --test test/*.test.js\n\n# 6. 提交\ngit commit -m 'fix: xxx'\ngit push origin fix-something\n\n# 7. 在 GitHub 提 PR",'bash'),
      ('H2','代码规范'),
      ('Ul',
        '不写 TypeScript',
        '不加依赖（除非必要）',
        '保持每个文件单一职责',
        '核心文件保持简洁（core/src 每文件 < 200 行）'),
      ('H2','测试'),
      ('P','改核心代码必须加测试。'),
      ('Code',"import { test } from 'node:test'\nimport assert from 'node:assert/strict'\nimport { signal } from '../core/src/core.js'\n\ntest('改动说明', () => {\n  const s = signal(1)\n  s(2)\n  assert.equal(s(), 2)\n})",'js'),
      ('H2','项目结构'),
      ('Code',"core/          核心运行时\ncompiler2/     .xuy 编译器\nbin/           命令行工具\nbackends/      四套后端\nsite/          文档站\ndocs/          Markdown 文档\nexamples/      示例\ntest/          测试",'txt'),
      ('H2','Commit 规范'),
      ('Table',['前缀','用途'],[
        ['feat:','新功能'],
        ['fix:','修 bug'],
        ['docs:','文档'],
        ['refactor:','重构'],
        ['perf:','性能'],
        ['test:','测试'],
        ['chore:','杂项']),
      ('H2','License'),
      ('P','MIT——贡献即同意以 MIT 协议发布。'),
    ]),""", "misc-contribute")

# misc-roadmap
swap("    ('misc-roadmap', '路线图', []),", r"""    ('misc-roadmap', '路线图', [
      ('H1','路线图'),
      ('H2','v1.0 ✓'),
      ('Ul',
        'Signal 内核',
        '元素渲染',
        '列表 diff',
        '事件委托',
        'SSR',
        '.xuy 编译器'),
      ('H2','v1.0.1 ✓'),
      ('Ul',
        'sanitize——HTML 白名单',
        'resource——异步三态',
        'model——表单绑定',
        'transition——FLIP',
        'hydration——SSR 校验',
        'devtools 完整版',
        '类型声明',
        '测试'),
      ('H2','v1.1 计划'),
      ('Ul',
        '虚拟列表内置',
        '表单库',
        '路由库',
        'Vite 插件发布 npm',
        'Devtools 浏览器扩展'),
      ('H2','v1.2 计划'),
      ('Ul',
        'SSR 完善（流式）',
        'i18n 内置',
        '动画库',
        'React / Vue 桥接'),
      ('H2','v2.0 愿景'),
      ('Ul',
        '编译器优化（编译期特化）',
        '多后端运行时（Rust / WASM）',
        '生态（组件库、工具链）',
        '社区贡献者'),
      ('H2','不做'),
      ('Table',['不做','原因'],[
        ['兼容 React','保留 VDOM 就没法精确更新'],
        ['TS 重写','背离"不写 TS"'],
        ['Fiber 调度','同步渲染够快'],
        ['大型组件库','kit 已够'],
        ['商业化','保持开源')),
      ('H2','现状'),
      ('Table',['模块','状态'],[
        ['核心运行时','稳定'],
        ['编译器','稳定'],
        ['四套后端','稳定'],
        ['文档站','150 篇'],
        ['DevTools','可用'],
        ['npm 发布','待发布'],
        ['生产验证','不足']),
    ]),""", "misc-roadmap")

# misc-versions
swap("    ('misc-versions', '版本', []),", r"""    ('misc-versions', '版本', [
      ('H1','版本'),
      ('H2','当前'),
      ('Code','v1.0.1','txt'),
      ('H2','版本规则'),
      ('Table',['版本','含义','示例'],[
        ['主版本','破坏性变更','1.0.0 → 2.0.0'],
        ['次版本','新增功能','1.0.0 → 1.1.0'],
        ['补丁','bug 修复','1.0.0 → 1.0.1']),
      ('H2','语义化版本'),
      ('P','遵循 semver——主版本.次版本.补丁。'),
      ('H2','兼容性'),
      ('Ul',
        '主版本内向后兼容',
        '次版本不破坏旧 API',
        '补丁不引入新功能'),
      ('H2','升级'),
      ('Code',"npm install xunay@latest",'bash'),
      ('H2','版本历史'),
      ('Table',['版本','日期','说明'],[
        ['v1.0.0','—','核心 + 全栈 + 四后端'],
        ['v1.0.1','—','加固 + 优化 + 修复']),
      ('H2','发布渠道'),
      ('Table',['渠道','用途'],[
        ['npm','正式发布'],
        ['GitHub','源码'],
        ['unpkg','CDN'],
        ['jsdelivr','CDN']),
      ('H2','弃用策略'),
      ('P','弃用 API 会在次版本标记警告，下一个主版本移除。'),
    ]),""", "misc-versions")

# misc-license
swap("    ('misc-license', '许可', []),", r"""    ('misc-license', '许可', [
      ('H1','许可'),
      ('H2','MIT License'),
      ('P','xunay 使用 MIT 协议——最宽松的开源协议之一。'),
      ('H2','你可以'),
      ('Ul',
        '商用',
        '修改源码',
        '分发',
        '私有使用',
        '再许可'),
      ('H2','你必须'),
      ('Ul',
        '保留版权声明',
        '保留许可声明'),
      ('H2','你不必'),
      ('Ul',
        '开源你的修改',
        '提供担保',
        '承担任何责任'),
      ('H2','完整文本'),
      ('Code',"MIT License\n\nCopyright (c) 2024 XuNay\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.",'txt'),
      ('H2','第三方'),
      ('P','xunay 核心零依赖。可选模块可能引第三方：'),
      ('Table',['模块','依赖'],[
        ['core','无'],
        ['kit','无'],
        ['devtools','无'],
        ['compiler2','esbuild（构建时）'],
        ['backends/python','fastapi / pydantic / granian']),
    ]),""", "misc-license")

# misc-credits
swap("    ('misc-credits', '鸣谢', []),", r"""    ('misc-credits', '鸣谢', [
      ('H1','鸣谢'),
      ('H2','设计灵感'),
      ('Table',['项目','借鉴'],[
        ['Solid','信号 + 精确更新模型'],
        ['Svelte','编译 + 简单语法'],
        ['Vue 3','Composition API'],
        ['React','生态系统参考'],
        ['Preact','极小体积思路']),
      ('H2','技术栈'),
      ('Ul',
        'esbuild——极快打包器',
        'granian——Python ASGI 服务器',
        'FastAPI——Python Web 框架',
        'Node.js——JS 运行时'),
      ('H2','工具'),
      ('Ul',
        'VS Code',
        'iTerm / Windows Terminal',
        'Chrome DevTools',
        'git'),
      ('H2','致谢'),
      ('P','感谢所有使用、反馈、贡献的人。'),
      ('H2','联系'),
      ('Ul',
        'GitHub: github.com/xxx/xunay',
        'Email: hello@xunay.dev',
        '文档: xunay.dev'),
    ]),""", "misc-credits")

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("杂项 8 篇已填")
