#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

swap("    ('backend-overview', '总览', []),", r"""    ('backend-overview', '总览', [
      ('H1','后端总览'),
      ('P','xunay 提供四套后端实现（Node / Python / Go / C++），共享同一份路由表和 RPC 协议。'),
      ('H2','为什么四套'),
      ('P','不是"多此一举"，是"换语言不用改前端"。同一份前端代码配任意后端都能跑。'),
      ('Table',['后端','技术栈','端口'],[
        ['Node','原生 http','12341'],
        ['Python','FastAPI + granian','12342'],
        ['Go','net/http','12343'],
        ['C++','httplib','12344'],
      ]),
      ('H2','切换后端'),
      ('P','改 xunay.config.json 一行：'),
      ('Code',"{\n  \"backend\": \"python\",\n  \"ports\": {\n    \"node\": 12341,\n    \"python\": 12342,\n    \"go\": 12343,\n    \"cpp\": 12344\n  }\n}",'json'),
      ('P','然后 `bash bin/start.sh`。前端不用改任何代码。'),
      ('H2','路由唯一真相源'),
      ('P','所有接口定义在 shared/routes.json：'),
      ('Code',"{\n  \"routes\": [\n    { \"name\": \"token\", \"method\": \"GET\", \"path\": \"/rpc/token\", \"auth\": false },\n    { \"name\": \"getTodos\", \"method\": \"GET\", \"path\": \"/rpc/getTodos\", \"auth\": true },\n    { \"name\": \"addTodo\", \"method\": \"POST\", \"path\": \"/rpc/addTodo\", \"auth\": true }\n  ]\n}",'json'),
      ('P','四套后端都读这份文件——加接口只改一处。'),
      ('H2','RPC 协议'),
      ('Code',"// 请求\nGET /rpc/getTodos\nAuthorization: Bearer <token>\n\n// 响应\n{\n  \"ok\": true,\n  \"data\": [...],\n  \"error\": null\n}",'txt'),
      ('H2','目录结构'),
      ('Code',"backends/\n├── node/       server.js + handlers.js + db.js\n├── python/     main.py + handlers.py + db.py\n├── go/         main.go + handlers.go + db.go\n└── cpp/        main.cpp + handlers.cpp + db.cpp",'txt'),
      ('H2','前端调用'),
      ('P','前端不写 URL——RPC 客户端自动生成：'),
      ('Code',"import { client } from './api/client.js'\n\nconst todos = await client.get('/rpc/getTodos')\nawait client.post('/rpc/addTodo', { title: '新任务' })",'xuy'),
      ('H2','增删接口'),
      ('Code',"1. 改 shared/routes.json 加一条\n2. 四套后端的 handlers 各加一个函数\n3. 前端 RPC 客户端自动可用\n4. bash bin/check-routes.js 校验",'bash'),
      ('H2','下一步'),
      ('Link','#backend-node','Node 后端'),
      ('Link','#backend-python','Python 后端'),
    ]),""", "backend-overview")

swap("    ('backend-node', 'Node 后端', []),", r"""    ('backend-node', 'Node 后端', [
      ('H1','Node 后端'),
      ('P','最轻量的后端——零依赖，纯 Node 原生 http 模块。'),
      ('H2','启动'),
      ('Code',"bash bin/start.sh\n# 或\nnode backends/node/server.js",'bash'),
      ('H2','默认端口'),
      ('Code','12341','txt'),
      ('H2','目录'),
      ('Code',"backends/node/\n├── server.js       HTTP 服务器 + 路由\n├── handlers.js     业务逻辑\n├── db.js           JSON 文件持久化\n├── schemas.js      参数校验\n├── mini.js         迷你 Web 框架\n└── data.json       数据文件",'txt'),
      ('H2','handlers'),
      ('Code',"// handlers.js\nexport const handleGetTodos = async (ctx) => {\n  const todos = await db.getTodos()\n  return { ok: true, data: todos }\n}\n\nexport const handleAddTodo = async (ctx) => {\n  const { title } = ctx.body\n  if (!title) throw new Error('title 必填')\n  const todo = await db.addTodo({ title })\n  return { ok: true, data: todo }\n}",'js'),
      ('H2','路由绑定'),
      ('Code',"// server.js\nconst routes = [\n  { path: '/rpc/token', method: 'GET', auth: false, handler: handleToken },\n  { path: '/rpc/getTodos', method: 'GET', auth: true, handler: handleGetTodos },\n  { path: '/rpc/addTodo', method: 'POST', auth: true, handler: handleAddTodo }\n]",'js'),
      ('H2','数据持久化'),
      ('P','用 JSON 文件存储——简单、好调试、零依赖。'),
      ('Code',"// db.js\nimport fs from 'node:fs'\nconst FILE = './data.json'\n\nexport const db = {\n  async getTodos() {\n    return JSON.parse(fs.readFileSync(FILE, 'utf8')).todos || []\n  },\n  async addTodo({ title }) {\n    const data = JSON.parse(fs.readFileSync(FILE, 'utf8'))\n    const todo = { id: Date.now(), title, done: false }\n    data.todos = [...(data.todos || []), todo]\n    fs.writeFileSync(FILE, JSON.stringify(data, null, 2))\n    return todo\n  }\n}",'js'),
      ('H2','WebSocket'),
      ('P','Node 原生不支持 WebSocket——用 ws 库或 SSE 替代。'),
      ('Code',"// 简易 SSE\nimport http from 'node:http'\n\nhttp.createServer((req, res) => {\n  if (req.url === '/ws') {\n    res.writeHead(200, { 'Content-Type': 'text/event-stream' })\n    const timer = setInterval(() => res.write('data: tick\\n\\n'), 1000)\n    req.on('close', () => clearInterval(timer))\n  }\n})",'js'),
      ('H2','优点'),
      ('Ul',
        '零依赖——只用 Node 内置模块',
        '启动快——100ms 内',
        '调试简单——直接 console.log',
        '适合原型和内部工具'),
      ('H2','缺点'),
      ('Ul',
        '单线程——CPU 密集会阻塞',
        '无内置 ORM',
        '无中间件系统'),
    ]),""", "backend-node")

swap("    ('backend-python', 'Python 后端', []),", r"""    ('backend-python', 'Python 后端', [
      ('H1','Python 后端'),
      ('P','基于 FastAPI + granian——功能最完整的后端。'),
      ('H2','启动'),
      ('Code',"bash scripts/run-backend.sh\n# 或\nsource .venv/bin/activate\npython -m uvicorn backend.main:app --port 12342",'bash'),
      ('H2','默认端口'),
      ('Code','12342','txt'),
      ('H2','目录'),
      ('Code',"backend/\n├── main.py          FastAPI 应用\n├── api/\n│   ├── token.py     token 接口\n│   ├── todos.py     todos 接口\n│   └── ws.py        WebSocket\n├── core/\n│   ├── security.py  认证\n│   └── errors.py    错误处理\n├── db.py            SQLite\n├── schemas.py       Pydantic 模型\n└── static.py        静态文件托管",'txt'),
      ('H2','FastAPI 路由'),
      ('Code',"# api/todos.py\nfrom fastapi import APIRouter, Depends\nfrom ..core.security import require_token\n\nrouter = APIRouter()\n\n@router.get('/rpc/getTodos')\nasync def get_todos(user = Depends(require_token)):\n    return { 'ok': True, 'data': db.get_todos() }\n\n@router.post('/rpc/addTodo')\nasync def add_todo(body: AddTodoReq, user = Depends(require_token)):\n    todo = db.add_todo(body.title)\n    return { 'ok': True, 'data': todo }",'py'),
      ('H2','Pydantic 校验'),
      ('Code',"# schemas.py\nfrom pydantic import BaseModel\n\nclass AddTodoReq(BaseModel):\n    title: str\n\nclass Todo(BaseModel):\n    id: int\n    title: str\n    done: bool",'py'),
      ('H2','SQLite 持久化'),
      ('Code',"# db.py\nimport sqlite3\n\nconn = sqlite3.connect('data.db')\nconn.execute('''\n  CREATE TABLE IF NOT EXISTS todos (\n    id INTEGER PRIMARY KEY,\n    title TEXT,\n    done INTEGER DEFAULT 0\n  )\n''')\n\ndef get_todos():\n    rows = conn.execute('SELECT * FROM todos').fetchall()\n    return [dict(id=r[0], title=r[1], done=bool(r[2])) for r in rows]",'py'),
      ('H2','静态文件托管'),
      ('P','Python 后端同时托管前端——不用单独起静态服务器。'),
      ('Code',"# static.py\n@router.get('/myapp/{path:path}')\ndef myapp(path: str = ''):\n    return serve(BASE / 'myapp', path)\n\n@router.get('/site/{path:path}')\ndef site(path: str = ''):\n    return serve(BASE / 'site/dist', path)",'py'),
      ('H2','CORS'),
      ('Code',"app.add_middleware(\n    CORSMiddleware,\n    allow_origins=['*'],\n    allow_methods=['*'],\n    allow_headers=['*'],\n)",'py'),
      ('H2','优点'),
      ('Ul',
        'Pydantic 自动校验',
        'SQLite / PostgreSQL 支持',
        '自动生成 OpenAPI 文档',
        'WebSocket 内建',
        '同时托管前端'),
      ('H2','缺点'),
      ('Ul',
        '依赖较多（fastapi / uvicorn / pydantic）',
        '启动较慢（~1s）',
        '内存占用较大'),
    ]),""", "backend-python")

swap("    ('backend-go', 'Go 后端', []),", r"""    ('backend-go', 'Go 后端', [
      ('H1','Go 后端'),
      ('P','单文件二进制——编译完直接丢到服务器跑，零依赖。'),
      ('H2','启动'),
      ('Code',"cd backends/go\ngo run .\n# 或\ncd backends/go && go build -o server && ./server",'bash'),
      ('H2','默认端口'),
      ('Code','12343','txt'),
      ('H2','目录'),
      ('Code',"backends/go/\n├── main.go        HTTP 服务器\n├── handlers.go    业务逻辑\n├── db.go          数据\n├── schemas.go     结构体\n└── go.mod         模块定义",'txt'),
      ('H2','handler'),
      ('Code',"// handlers.go\nfunc HandleGetTodos(w http.ResponseWriter, r *http.Request) {\n    todos := GetTodos()\n    writeJSON(w, 200, Response{\n        Ok: true,\n        Data: todos,\n    })\n}\n\nfunc HandleAddTodo(w http.ResponseWriter, r *http.Request) {\n    var req AddTodoReq\n    json.NewDecoder(r.Body).Decode(&req)\n    todo := AddTodo(req.Title)\n    writeJSON(w, 200, Response{Ok: true, Data: todo})\n}",'go'),
      ('H2','路由'),
      ('Code',"// main.go\nfunc main() {\n    http.HandleFunc(\"/rpc/token\", HandleToken)\n    http.HandleFunc(\"/rpc/getTodos\", WithAuth(HandleGetTodos))\n    http.HandleFunc(\"/rpc/addTodo\", WithAuth(HandleAddTodo))\n\n    fmt.Println(\"XuNay Go 后端 :12343\")\n    http.ListenAndServe(\":12343\", nil)\n}",'go'),
      ('H2','struct + JSON'),
      ('Code',"// schemas.go\ntype Todo struct {\n    ID    int64  `json:\"id\"`\n    Title string `json:\"title\"`\n    Done  bool   `json:\"done\"`\n}\n\ntype Response struct {\n    Ok    bool        `json:\"ok\"`\n    Data  interface{} `json:\"data\"`\n    Error string      `json:\"error\"`\n}",'go'),
      ('H2','并发模型'),
      ('P','每个请求一个 goroutine——天然支持高并发。'),
      ('Code',"// 例子：批量请求不互相阻塞\nfunc Handler(w http.ResponseWriter, r *http.Request) {\n    var wg sync.WaitGroup\n    wg.Add(2)\n    go fetchA(&wg)\n    go fetchB(&wg)\n    wg.Wait()\n}",'go'),
      ('H2','优点'),
      ('Ul',
        '编译成单文件——拷贝即部署',
        '启动快（~10ms）',
        '内存小（~10MB）',
        '并发强',
        '跨平台交叉编译'),
      ('H2','缺点'),
      ('Ul',
        '生态不如 Node / Python',
        '没有 ORM（用 sqlx 或原生）',
        '开发迭代慢（要重编译）'),
      ('H2','部署'),
      ('Code',"# 本地编译（Mac → Linux）\nGOOS=linux GOARCH=amd64 go build -o server main.go\n\n# 上传 + 运行\nscp server server:/opt/xunay/\nssh server 'nohup /opt/xunay/server &'",'bash'),
    ]),""", "backend-go")

swap("    ('backend-cpp', 'C++ 后端', []),", r"""    ('backend-cpp', 'C++ 后端', [
      ('H1','C++ 后端'),
      ('P','极致性能——httplib 单头文件 HTTP 库，编译后 ~1MB 二进制。'),
      ('H2','启动'),
      ('Code',"cd backends/cpp\nmkdir -p build && cd build\ncmake .. && make\n./server",'bash'),
      ('H2','默认端口'),
      ('Code','12344','txt'),
      ('H2','目录'),
      ('Code',"backends/cpp/\n├── CMakeLists.txt\n├── main.cpp        入口\n├── handlers.cpp    路由处理\n├── handlers.h\n├── db.cpp          数据\n├── db.h\n└── schemas.h       结构体",'txt'),
      ('H2','handler'),
      ('Code',"// handlers.cpp\nvoid handleGetTodos(const Request& req, Response& res) {\n    auto todos = db.getTodos();\n    res.set_content(toJson({\n        { \"ok\", true },\n        { \"data\", todos }\n    }), \"application/json\");\n}",'cpp'),
      ('H2','路由'),
      ('Code',"// main.cpp\nint main() {\n    httplib::Server svr;\n\n    svr.Get(\"/rpc/token\", handleToken);\n    svr.Get(\"/rpc/getTodos\", [](auto& req, auto& res) {\n        if (!checkAuth(req)) return unauthorized(res);\n        handleGetTodos(req, res);\n    });\n\n    std::cout << \"XuNay C++ 后端 :12344\" << std::endl;\n    svr.listen(\"0.0.0.0\", 12344);\n}",'cpp'),
      ('H2','CMake 构建'),
      ('Code',"cmake_minimum_required(VERSION 3.10)\nproject(xunay-backend)\n\nset(CMAKE_CXX_STANDARD 17)\n\nadd_executable(server main.cpp handlers.cpp db.cpp)\ntarget_include_directories(server PRIVATE .)",'cmake'),
      ('H2','性能'),
      ('Table',['指标','C++','Node','Python'],[
        ['启动','5ms','100ms','1s'],
        ['内存','~5MB','~40MB','~80MB'],
        ['QPS','~80000','~15000','~8000'],
        ['编译时间','~5s','—','—'],
      ]),
      ('H2','优点'),
      ('Ul',
        '最快——QPS 是 Node 的 5 倍',
        '内存最小',
        '无运行时依赖',
        '单文件二进制'),
      ('H2','缺点'),
      ('Ul',
        '开发慢——重编译要几秒',
        '调试难——要 gdb',
        '写 JSON 处理麻烦',
        '不适合快速迭代'),
      ('H2','什么时候用'),
      ('P','CPU 密集 + 高并发 + 低延迟——比如实时游戏服务器、量化交易。日常 Web 应用没必要。'),
    ]),""", "backend-cpp")

swap("    ('backend-rpc', 'RPC 协议', []),", r"""    ('backend-rpc', 'RPC 协议', [
      ('H1','RPC 协议'),
      ('P','统一请求格式——四套后端共用。'),
      ('H2','请求'),
      ('Code',"POST /rpc/addTodo HTTP/1.1\nContent-Type: application/json\nAuthorization: Bearer <token>\n\n{\n  \"title\": \"新任务\"\n}",'txt'),
      ('H2','响应'),
      ('Code',"// 成功\n{\n  \"ok\": true,\n  \"data\": { \"id\": 1, \"title\": \"新任务\", \"done\": false },\n  \"error\": null\n}\n\n// 失败\n{\n  \"ok\": false,\n  \"data\": null,\n  \"error\": \"title 必填\"\n}",'json'),
      ('H2','状态码'),
      ('Table',['码','含义'],[
        ['200','成功'],
        ['400','参数错误'],
        ['401','未认证'],
        ['403','无权限'],
        ['404','接口不存在'],
        ['500','服务器错误'],
      ]),
      ('H2','认证'),
      ('Code',"// 1. 获取 token\nGET /rpc/token\n→ { ok: true, data: { token: 'xxx' } }\n\n// 2. 后续请求带 token\nGET /rpc/getTodos\nAuthorization: Bearer xxx",'txt'),
      ('H2','前端客户端'),
      ('Code',"// api/client.js\nexport const client = {\n  async get(path, opts = {}) {\n    const r = await fetch(path, {\n      method: 'GET',\n      headers: { ...authHeader(), ...opts.headers }\n    })\n    const j = await r.json()\n    if (!j.ok) throw new Error(j.error)\n    return j.data\n  },\n  async post(path, body) {\n    const r = await fetch(path, {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json', ...authHeader() },\n      body: JSON.stringify(body)\n    })\n    const j = await r.json()\n    if (!j.ok) throw new Error(j.error)\n    return j.data\n  }\n}",'js'),
      ('H2','为什么用 RPC 而不是 REST'),
      ('Table',['','REST','RPC'],[
        ['URL','/todos/1','/rpc/getTodo'],
        ['语义','资源','动作'],
        ['方法','GET/POST/PUT','都 POST'],
        ['前端友好','一般','好（函数名）'],
        ['缓存','浏览器自动','手动'],
      ]),
      ('P','RPC 的好处：接口名就是函数名，前端不用拼 URL。'),
    ]),""", "backend-rpc")

swap("    ('backend-ws', 'WebSocket', []),", r"""    ('backend-ws', 'WebSocket', [
      ('H1','WebSocket'),
      ('P','实时双向通信——服务端主动推送给客户端。'),
      ('H2','场景'),
      ('Ul',
        '聊天室',
        '实时通知',
        '协同编辑',
        '数据看板'),
      ('H2','前端连接'),
      ('Code',"export function connectWS(onChange) {\n  function connect() {\n    const proto = location.protocol === 'https:' ? 'wss' : 'ws'\n    const ws = new WebSocket(proto + '://' + location.host + '/ws')\n    ws.onmessage = e => {\n      try {\n        const msg = JSON.parse(e.data)\n        if (msg.type === 'todos_changed') onChange()\n      } catch (_) {}\n    }\n    ws.onclose = () => setTimeout(connect, 2000)   // 自动重连\n    ws.onerror = () => ws.close()\n  }\n  connect()\n}",'js'),
      ('H2','后端（Python）'),
      ('Code',"# api/ws.py\nfrom fastapi import APIRouter, WebSocket\n\nrouter = APIRouter()\nclients = set()\n\n@router.websocket('/ws')\nasync def ws_endpoint(ws: WebSocket):\n    await ws.accept()\n    clients.add(ws)\n    try:\n        while True:\n            await ws.receive_text()\n    except:\n        clients.remove(ws)\n\nasync def broadcast(msg):\n    for ws in list(clients):\n        try:\n            await ws.send_json(msg)\n        except:\n            clients.remove(ws)",'py'),
      ('H2','触发广播'),
      ('Code',"# todos.py\n@router.post('/rpc/addTodo')\nasync def add_todo(body: AddTodoReq):\n    todo = db.add_todo(body.title)\n    await broadcast({ 'type': 'todos_changed' })\n    return { 'ok': True, 'data': todo }",'py'),
      ('H2','Node 后端 SSE 替代'),
      ('P','Node 原生不支持 WebSocket——用 SSE（Server-Sent Events）替代单向推送：'),
      ('Code',"// server.js\nif (req.url === '/sse') {\n  res.writeHead(200, {\n    'Content-Type': 'text/event-stream',\n    'Cache-Control': 'no-cache'\n  })\n  const client = { send: msg => res.write('data: ' + JSON.stringify(msg) + '\\n\\n') }\n  clients.add(client)\n  req.on('close', () => clients.delete(client))\n}",'js'),
      ('H2','前端监听 SSE'),
      ('Code',"const es = new EventSource('/sse')\nes.onmessage = e => {\n  const msg = JSON.parse(e.data)\n  if (msg.type === 'todos_changed') reload()\n}",'js'),
      ('H2','重连机制'),
      ('P','网络不稳定时连接会断——必须自动重连。上面的例子用了 setTimeout 2 秒后重连。'),
      ('H2','心跳'),
      ('P','长时间空闲的连接会被中间代理断开——定期发心跳：'),
      ('Code',"setInterval(() => {\n  if (ws.readyState === WebSocket.OPEN) ws.send('ping')\n}, 30000)",'js'),
    ]),""", "backend-ws")

swap("    ('backend-db', '数据库', []),", r"""    ('backend-db', '数据库', [
      ('H1','数据库'),
      ('P','四套后端各自实现数据层——从 JSON 文件到 SQLite 到原生 SQL。'),
      ('H2','Python：SQLite'),
      ('Code',"# backend/db.py\nimport sqlite3\n\nconn = sqlite3.connect('data.db')\nconn.row_factory = sqlite3.Row\n\nconn.execute('''\n  CREATE TABLE IF NOT EXISTS todos (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    title TEXT NOT NULL,\n    done INTEGER DEFAULT 0,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n  )\n''')\n\ndef get_todos():\n    return [dict(r) for r in conn.execute('SELECT * FROM todos').fetchall()]\n\ndef add_todo(title):\n    cur = conn.execute('INSERT INTO todos (title) VALUES (?)', (title,))\n    conn.commit()\n    return get_todo(cur.lastrowid)\n\ndef toggle_todo(id):\n    conn.execute('UPDATE todos SET done = NOT done WHERE id = ?', (id,))\n    conn.commit()\n    return get_todo(id)",'py'),
      ('H2','Node：JSON 文件'),
      ('Code',"// backends/node/db.js\nimport fs from 'node:fs'\n\nconst FILE = './data.json'\nfunction read() {\n  try { return JSON.parse(fs.readFileSync(FILE, 'utf8')) }\n  catch { return { todos: [] } }\n}\nfunction write(data) {\n  fs.writeFileSync(FILE, JSON.stringify(data, null, 2))\n}\n\nexport const db = {\n  getTodos() { return read().todos || [] },\n  addTodo({ title }) {\n    const d = read()\n    const todo = { id: Date.now(), title, done: false }\n    d.todos = [...(d.todos || []), todo]\n    write(d)\n    return todo\n  },\n  toggleTodo(id) {\n    const d = read()\n    d.todos = d.todos.map(t => t.id === id ? { ...t, done: !t.done } : t)\n    write(d)\n    return d.todos.find(t => t.id === id)\n  }\n}",'js'),
      ('H2','Go：内存 + JSON'),
      ('Code',"// backends/go/db.go\nvar (\n    mu    sync.Mutex\n    todos []Todo\n)\n\nfunc init() {\n    data, _ := os.ReadFile(\"data.json\")\n    json.Unmarshal(data, &todos)\n}\n\nfunc GetTodos() []Todo {\n    mu.Lock()\n    defer mu.Unlock()\n    return todos\n}\n\nfunc AddTodo(title string) Todo {\n    mu.Lock()\n    defer mu.Unlock()\n    todo := Todo{ID: time.Now().UnixMilli(), Title: title}\n    todos = append(todos, todo)\n    save()\n    return todo\n}",'go'),
      ('H2','C++：内存 Map'),
      ('Code',"// backends/cpp/db.cpp\nstd::map<int64_t, Todo> todos;\nstd::mutex mu;\n\nstd::vector<Todo> getTodos() {\n    std::lock_guard<std::mutex> lock(mu);\n    std::vector<Todo> out;\n    for (auto& [id, t] : todos) out.push_back(t);\n    return out;\n}\n\nTodo addTodo(const std::string& title) {\n    std::lock_guard<std::mutex> lock(mu);\n    int64_t id = now_ms();\n    Todo t{id, title, false};\n    todos[id] = t;\n    return t;\n}",'cpp'),
      ('H2','对比'),
      ('Table',['后端','持久化','并发安全','扩展性'],[
        ['Node','JSON 文件','无','小项目'],
        ['Python','SQLite','SQLite 锁','中小项目'],
        ['Go','JSON + 互斥锁','是','中项目'],
        ['C++','内存 Map','是','高并发'],
      ]),
      ('H2','升级路径'),
      ('Ul',
        'JSON 文件 → SQLite（推荐起点）',
        'SQLite → PostgreSQL（多人协作）',
        'PostgreSQL → 加缓存层（Redis）'),
    ]),""", "backend-db")

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("后端 8 篇已填")
