import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core4", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ list ============
swap(`    ('core-list', '列表', []),`,
`    ('core-list', '列表', [
      ('H1','列表'),
      ('P','list 是 xunay 里渲染数组的唯一方式。它用 key 做 diff——新增/删除/移动只动变化项，不重建整个列表。'),
      ('H2','基础用法'),
      ('Code',"import { list, ul, li, signal } from 'xunay'\\n\\nconst items = signal(['苹果', '香蕉', '橙子'])\\n\\nul(null,\\n  list(items, i => i, i => li(null, i))\\n)",'xuy'),
      ('H2','三个参数'),
      ('Table',['参数','作用'],[
        ['arr','数组或 () => 数组'],
        ['keyFn','从元素提取唯一 key'],
        ['renderFn','把元素渲染成 vnode'],
      ]),
      ('H2','keyFn 的作用'),
      ('P','key 是 diff 的依据——前后两次渲染 key 相同的项被认为是同一个，DOM 会复用。key 不同则删除旧的、创建新的。'),
      ('Code',"// id 作为 key：稳定\\nlist(todos, t => t.id, t => li(null, t.title))\\n\\n// 索引作为 key：不稳定（重排时全错位）\\nlist(todos, (t, i) => i, t => li(null, t.title))   // ⚠ 慎用\\n\\n// 字符串本身作 key\\nlist(names, n => n, n => li(null, n))",'xuy'),
      ('H2','数组可以是 signal'),
      ('P','传 signal 时会自动订阅——signal 变，列表更新。传普通数组时是静态的。'),
      ('Code',"const todos = signal([...])\\nlist(todos, t => t.id, t => li(null, t.title))\\n// 或\\nconst todos = signal([...])\\nlist(() => todos(), t => t.id, t => li(null, t.title))\\n// 两者等价",'xuy'),
      ('H2','diff 算法'),
      ('P','list 维护一个 Map<key, {dom, item}>。每次更新时：'),
      ('Ul',
        '遍历新数组，key 在 map 里 → 复用 DOM',
        'key 不在 map 里 → 创建新 DOM，加进 map',
        'map 里的 key 不在新数组里 → 从 map 删除，DOM 移除'),
      ('P','如果 item 引用变了（不只是顺序），会先试 fastUpdate 原地更新属性，失败才重建。'),
      ('Code',"const todos = signal([{ id: 1, done: false }])\\n\\n// 改 done 属性：fastUpdate 原地改 class\\ntodos(list => list.map(t => t.id === 1 ? { ...t, done: true } : t))\\n\\n// 换整个对象：fastUpdate 失败，重建该行\\ntodos(list => [{ id: 1, done: true }])",'xuy'),
      ('H2','增删改查模式'),
      ('H3','新增'),
      ('Code',"const todos = signal([])\\ntodos(list => [...list, { id: Date.now(), title: '新任务', done: false }])",'xuy'),
      ('H3','删除'),
      ('Code',"const todos = signal([])\\ntodos(list => list.filter(t => t.id !== id))",'xuy'),
      ('H3','修改'),
      ('Code',"const todos = signal([])\\ntodos(list => list.map(t => t.id === id ? { ...t, done: !t.done } : t))",'xuy'),
      ('H3','排序'),
      ('Code',"const todos = signal([])\\ntodos(list => [...list].sort((a, b) => a.priority - b.priority))",'xuy'),
      ('H3','清空'),
      ('Code',"todos([])",'xuy'),
      ('H2','空列表处理'),
      ('Code',"import { list, ul, li, p, show } from 'xunay'\\n\\ndiv(null,\\n  show(() => items().length === 0, () => p(null, '暂无数据')),\\n  ul(null, list(items, i => i.id, i => li(null, i.name)))\\n)",'xuy'),
      ('H2','嵌套列表'),
      ('Code',"ul(null,\\n  list(categories, c => c.id, c =>\\n    li(null,\\n      span(null, c.name),\\n      ul(null,\\n        list(c.items, i => i.id, i => li(null, i.title))\\n      )\\n    )\\n  )\\n)",'xuy'),
      ('H2','列表项带事件'),
      ('Code',"ul(null,\\n  list(todos, t => t.id, t => li({ class: () => t.done ? 'done' : '' },\\n    input({\\n      type: 'checkbox',\\n      checked: () => t.done,\\n      on: { change: () => toggle(t.id) }\\n    }),\\n    span({ class: 'title' }, t.title),\\n    button({ on: { click: () => remove(t.id) } }, '删除')\\n  ))\\n)",'xuy'),
      ('H2','list 内部机制'),
      ('P','applyList 里维护一个 scope（listScope）。每个列表项渲染时创建子 scope。删除项时 disposeScope，自动清理内部所有 effect。'),
      ('Code',"// list 里每一项都是独立的 scope\\nlist(todos, t => t.id, t => {\\n  // 这里的 signal / effect 属于这一项的 scope\\n  const editing = signal(false)\\n  effect(() => console.log('item ' + t.id, editing()))\\n  return li(null, t.title)\\n})\\n// 删除项 → scope dispose → 内部 effect 自动清理",'xuy'),
      ('H2','fastUpdate 细节'),
      ('P','当 key 存在但 item 引用变了，先尝试 fastUpdate——原地更新属性：'),
      ('Ul',
        '类型相同（都是 string）→ 只改 textContent',
        'tag 相同 → 递归更新属性和子节点',
        '有一个动态子节点 → 放弃，走重建',
        '结构不同 → 放弃，走重建'),
      ('H2','性能'),
      ('Table',['操作','1000 项耗时','复杂度'],[
        ['首次渲染','~40ms','O(n)'],
        ['追加 1 项','~0.5ms','O(1) + 1 次 appendChild'],
        ['删除 1 项','~0.5ms','O(1) + 1 次 removeChild'],
        ['改 1 项属性','~0.3ms','fastUpdate'],
        ['重排（全换位置）','~8ms','用 DocumentFragment 一次性替换'],
      ]),
      ('H2','与 React key 对比'),
      ('Table',['','xunay list','React'],[
        ['key 位置','显式参数','props.key'],
        ['key 类型','任意','字符串'],
        ['diff 时机','同步','异步（批量）'],
        ['重排','DocumentFragment','DOM 操作序列'],
        ['空列表','渲染空','渲染空'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：用索引做 key'),
      ('Code',"// ✗ 列表重排后，状态跟错行\\nlist(todos, (t, i) => i, ...)\\n\\n// ✓ 用稳定 id\\nlist(todos, t => t.id, ...)",'xuy'),
      ('P','用索引做 key 时，删除中间项会导致后面所有项的 key 都变——checkbox 选中状态会错乱。'),
      ('H3','陷阱 2：key 不唯一'),
      ('Code',"list(items, i => i.type, ...)   // ✗ type 可能有重复\\nlist(items, i => i.id, ...)     // ✓ id 唯一",'xuy'),
      ('H3','陷阱 3：直接 push 数组'),
      ('Code',"const todos = signal([])\\ntodos().push({ id: 1 })       // ✗ 对象引用没变，不触发\\ntodos(list => [...list, item]) // ✓ 返回新数组",'xuy'),
      ('H3','陷阱 4：列表项渲染有副作用'),
      ('Code',"list(todos, t => t.id, t => {\\n  fetch('/api/' + t.id)   // ✗ 每次重渲染都请求\\n  return li(null, t.title)\\n})",'xuy'),
      ('P','渲染函数应该纯——只读不写。要发请求用 onMount。'),
      ('H2','大数据量'),
      ('P','1000 项以上建议用虚拟滚动——只渲染可见区域。xunay 没有内置虚拟列表，但可以通过「只取可视范围的 slice」实现：'),
      ('Code',"const all = signal([...10000 items])\\nconst start = signal(0)\\nconst pageSize = 50\\n\\nconst visible = computed(() =>\\n  all().slice(start(), start() + pageSize)\\n)\\n\\nul({ style: { height: '500px', overflow: 'auto' } },\\n  list(visible, i => i.id, i => li(null, i.title))\\n)",'xuy'),
      ('H2','完整示例：多选待办'),
      ('Code',"import { div, ul, li, input, button, span, signal, computed, list, show, mount } from 'xunay'\\n\\nconst todos = signal([\\n  { id: 1, title: '写文档', done: false },\\n  { id: 2, title: '修 bug', done: true }\\n])\\nconst filter = signal('all')\\n\\nconst filtered = computed(() => {\\n  const t = todos(), f = filter()\\n  if (f === 'active') return t.filter(x => !x.done)\\n  if (f === 'done') return t.filter(x => x.done)\\n  return t\\n})\\n\\nconst stats = computed(() => ({\\n  total: todos().length,\\n  active: todos().filter(t => !t.done).length\\n}))\\n\\nfunction toggle(id) {\\n  todos(list => list.map(t => t.id === id ? { ...t, done: !t.done } : t))\\n}\\n\\nfunction remove(id) {\\n  todos(list => list.filter(t => t.id !== id))\\n}\\n\\nfunction add() {\\n  const title = prompt('新任务')\\n  if (!title) return\\n  todos(list => [...list, { id: Date.now(), title, done: false }])\\n}\\n\\nmount(() => div({ class: 'app' },\\n  div({ class: 'tabs' },\\n    ['all', 'active', 'done'].map(f =>\\n      span({\\n        class: () => 'tab' + (filter() === f ? ' on' : ''),\\n        on: { click: () => filter(f) }\\n      }, f === 'all' ? '全部' : f === 'active' ? '未完成' : '已完成')\\n    )\\n  ),\\n  ul({ class: 'list' },\\n    list(filtered, t => t.id, t => li({ class: () => 'item' + (t.done ? ' done' : '') },\\n      input({ type: 'checkbox', checked: () => t.done, on: { change: () => toggle(t.id) } }),\\n      span({ class: 'title' }, t.title),\\n      button({ on: { click: () => remove(t.id) } }, '×')\\n    ))\\n  ),\\n  div({ class: 'footer' },\\n    span(null, () => stats().active + ' / ' + stats().total),\\n    button({ on: { click: add } }, '添加')\\n  )\\n), '#app')",'xuy'),
    ]),`,
"list")

// ============ fragment ============
swap(`    ('core-fragment', 'Fragment', []),`,
`    ('core-fragment', 'Fragment', [
      ('H1','Fragment'),
      ('P','Fragment 是"一组并列节点的容器"——它本身不产生真实 DOM 节点，只把子节点拼在一起。用来避免多余的包裹层。'),
      ('H2','为什么需要它'),
      ('P','组件返回多个根节点时，React 要求用 <></> 或 <div> 包。用 div 会多一层无意义的 DOM；xunay 用 frag 解决。'),
      ('Code',"// 方式 A：包一层 div（多一层 DOM）\\nreturn div(null,\\n  h1(null, '标题'),\\n  p(null, '正文')\\n)\\n\\n// 方式 B：fragment（无包裹）\\nreturn frag(\\n  h1(null, '标题'),\\n  p(null, '正文')\\n)",'xuy'),
      ('H2','基础用法'),
      ('Code',"import { frag, h1, p, button } from 'xunay'\\n\\nfrag(\\n  h1(null, '标题'),\\n  p(null, '正文'),\\n  button(null, '按钮')\\n)",'xuy'),
      ('H2','内部机制'),
      ('P','frag 内部创建一个 display:contents 的 span 作为容器。display:contents 的 span 不参与布局——它的子元素直接参与父级布局，视觉上等于"没有这个 span"。'),
      ('Code',"// frag(...) 内部结构\\nconst holder = document.createElement('span')\\nholder.style.display = 'contents'\\n// 子节点 appendChild 到 holder\\n// holder 本身不占空间",'js'),
      ('H2','frag 与 F'),
      ('P','F 是 frag 的短别名。'),
      ('Code',"import { frag, F } from 'xunay'\\nfrag(a, b)   // 两者等价\\nF(a, b)",'xuy'),
      ('H2','使用场景'),
      ('H3','组件返回多个根节点'),
      ('Code',"function UserCard({ user }) {\\n  return frag(\\n    h1(null, user.name),\\n    p(null, user.bio)\\n  )\\n}",'xuy'),
      ('H3','条件渲染中的多节点'),
      ('Code',"show(() => loggedIn(), () => frag(\\n  span(null, '欢迎 ' + user().name),\\n  button({ on: { click: logout } }, '退出')\\n))",'xuy'),
      ('H3','列表项返回多个节点'),
      ('Code',"list(items, i => i.id, i => frag(\\n  li(null, i.title),\\n  li(null, i.desc)\\n))",'xuy'),
      ('H2','frag vs 其他容器'),
      ('Table',['方案','DOM 开销','布局影响','适用场景'],[
        ['frag','1 个 span（display:contents）','无','多根节点'],
        ['div','1 个 div','有（默认 block）','需要 class/style 时'],
        ['span','1 个 span','无（inline）','行内多节点'],
        ['null','0','无','不需要'],
      ]),
      ('H2','frag 与 key'),
      ('P','frag 没有 key 概念。列表用 list + keyFn 处理，不需要给 frag 加 key。'),
      ('H2','嵌套 fragment'),
      ('Code',"frag(\\n  h1(null, '标题'),\\n  frag(\\n    p(null, '段落 1'),\\n    p(null, '段落 2')\\n  )\\n)\\n// 输出 3 个并列节点",'xuy'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：frag 里没有子节点'),
      ('Code',"frag()   // 空 frag，无意义",'xuy'),
      ('H3','陷阱 2：以为 frag 能加 class'),
      ('Code',"frag({ class: 'x' }, a, b)   // ✗ frag 不接受 props\\nfrag(a, b)                    // ✓",'xuy'),
      ('P','frag 只接受子节点参数。需要属性用 div。'),
      ('H3','陷阱 3：fragment 里的 ref'),
      ('Code',"frag(\\n  input({ ref: el => inputRef(el) }),\\n  button(null, 'x')\\n)\\n// ref 各自处理，不冲突",'xuy'),
      ('H2','完整示例：评论 + 回复'),
      ('Code',"import { frag, div, span, p, button, ul, li, signal, list, show, mount } from 'xunay'\\n\\nconst comments = signal([\\n  { id: 1, user: 'A', text: '第一条', replies: [{ id: 11, user: 'B', text: '回复' }] }\\n])\\n\\nfunction Comment({ c }) {\\n  return frag(\\n    div({ class: 'comment-head' },\\n      span(null, c.user + ': '),\\n      span(null, c.text)\\n    ),\\n    show(() => c.replies && c.replies.length,\\n      () => ul({ class: 'replies' },\\n        list(c.replies, r => r.id, r => li(null, r.user + ': ' + r.text))\\n      )\\n    )\\n  )\\n}\\n\\nmount(() => div(null,\\n  list(comments, c => c.id, c => Comment({ c }))\\n), '#app')",'xuy'),
    ]),`,
"fragment")

writeFileSync(p, s)
console.log("list / fragment 两篇已填")
