import { readFileSync, writeFileSync } from "node:fs"
const p = "site/gen-docs.py"
let s = readFileSync(p, "utf8")
writeFileSync(p + ".bak.core5", s)

function swap(anchor, replacement, label) {
  if (!s.includes(anchor)) { console.log("未命中:", label); return }
  s = s.replace(anchor, replacement)
}

// ============ lifecycle ============
swap(`    ('core-lifecycle', '生命周期', []),`,
`    ('core-lifecycle', '生命周期', [
      ('H1','生命周期'),
      ('P','xunay 的生命周期只有两个钩子：onMount（DOM 挂载后）和 onUnmount（DOM 卸载前）。简单、清晰、没有 useLayoutEffect / componentWillUnmount 那种繁杂概念。'),
      ('H2','两个钩子'),
      ('Table',['钩子','触发时机','用途'],[
        ['onMount(fn)','元素挂载到文档后','访问 DOM、发请求、订阅'],
        ['onUnmount(fn)','元素被卸载前','清理定时器、取消订阅'],
      ]),
      ('H2','基础用法'),
      ('Code',"import { div, onMount, onUnmount } from 'xunay'\\n\\nfunction Timer() {\\n  onMount(() => console.log('挂载了'))\\n  onUnmount(() => console.log('卸载了'))\\n  return div(null, '定时器')\\n}",'xuy'),
      ('H2','onMount 能拿到 DOM 吗'),
      ('P','能。onMount 触发时元素已经在文档里，可以 getBoundingClientRect、focus、scrollIntoView。'),
      ('Code',"import { input, ref, onMount } from 'xunay'\\n\\nconst inputRef = ref()\\n\\ninput({ ref: el => inputRef(el), placeholder: '自动聚焦' })\\n\\nonMount(() => {\\n  inputRef().focus()\\n  inputRef().select()\\n})",'xuy'),
      ('H2','触发顺序'),
      ('P','父先于子。渲染时父节点先 appendChild 到文档，然后递归运行 mount 回调。所以 onMount 里父 scope 的回调比子 scope 的先跑。'),
      ('Code',"// <Parent><Child /></Parent>\\n// onMount 顺序：Parent → Child\\n// onUnmount 顺序：Child → Parent",'xuy'),
      ('H2','在动态节点里'),
      ('P','动态函数节点每次重跑都会创建新 scope——旧的销毁（触发 onUnmount），新的挂载（触发 onMount）。'),
      ('Code',"show(() => visible(), () => {\\n  onMount(() => console.log('进入'))\\n  onUnmount(() => console.log('离开'))\\n  return div(null, '内容')\\n})\\n// visible 变 true → 打印"进入"\\n// visible 变 false → 打印"离开"\\n// 再次变 true → 又打印"进入"",'xuy'),
      ('H2','在模块顶层不生效'),
      ('Warn','onMount 需要当前 scope。模块加载时没有 scope，onMount 会直接 return——回调不注册。必须在组件函数体里调用。'),
      ('Code',"// ✗ 模块顶层：不生效\\nonMount(() => { ... })\\n\\nexport function Home() {\\n  // ✓ 组件函数体内：生效\\n  onMount(() => { ... })\\n  return div(null, 'ok')\\n}",'xuy'),
      ('H2','多次调用'),
      ('P','同一 scope 里可以多次 onMount。按注册顺序执行。'),
      ('Code',"function Multi() {\\n  onMount(() => console.log('A'))\\n  onMount(() => console.log('B'))\\n  onMount(() => console.log('C'))\\n  return div()\\n}\\n// 打印：A B C",'xuy'),
      ('H2','onUnmount 的执行时机'),
      ('P','scope 被 dispose 时触发。两种情况：'),
      ('Ul',
        '父节点卸载，递归 dispose 所有子 scope',
        'show/list 切换时，对应 scope 被销毁'),
      ('P','dispose 时先跑 onUnmount 回调，再清理 effect，最后递归子 scope。'),
      ('H2','和 effect 的区别'),
      ('Table',['','onMount','effect'],[
        ['触发','挂载一次','依赖变就重跑'],
        ['依赖','无','有'],
        ['清理','onUnmount','返回函数'],
        ['访问 DOM','✓ 安全','✗ 可能 null'],
        ['适合','一次性初始化','响应式副作用'],
      ]),
      ('H2','常见用途'),
      ('H3','访问 DOM 尺寸'),
      ('Code',"import { div, ref, onMount, signal } from 'xunay'\\n\\nfunction Measured() {\\n  const el = ref()\\n  const size = signal({ w: 0, h: 0 })\\n  onMount(() => {\\n    const r = el().getBoundingClientRect()\\n    size({ w: r.width, h: r.height })\\n  })\\n  return div({ ref: e => el(e), class: 'box' },\\n    () => size().w + ' × ' + size().h\\n  )\\n}",'xuy'),
      ('H3','订阅外部事件'),
      ('Code',"function WindowSize() {\\n  const size = signal({ w: innerWidth, h: innerHeight })\\n  onMount(() => {\\n    const handler = () => size({ w: innerWidth, h: innerHeight })\\n    window.addEventListener('resize', handler)\\n    onUnmount(() => window.removeEventListener('resize', handler))\\n  })\\n  return div(null, () => size().w + '×' + size().h)\\n}",'xuy'),
      ('H3','初始化第三方库'),
      ('Code',"function Chart() {\\n  const el = ref()\\n  let chart = null\\n  onMount(() => {\\n    chart = echarts.init(el())\\n    chart.setOption({ ... })\\n  })\\n  onUnmount(() => { if (chart) chart.dispose() })\\n  return div({ ref: e => el(e), class: 'chart' })\\n}",'xuy'),
      ('H3','发一次请求'),
      ('Code',"function Profile({ userId }) {\\n  const data = signal(null)\\n  const loading = signal(true)\\n  onMount(async () => {\\n    try {\\n      const r = await fetch('/api/user/' + userId)\\n      data(await r.json())\\n    } finally {\\n      loading(false)\\n    }\\n  })\\n  return div(null, () => loading() ? '加载中' : data().name)\\n}",'xuy'),
      ('H2','完整示例：自动滚到底'),
      ('Code',"import { div, ul, li, list, ref, onMount, signal, mount } from 'xunay'\\n\\nfunction ChatLog() {\\n  const msgs = signal([])\\n  const scrollEl = ref()\\n\\n  // 每 1 秒模拟新消息\\n  onMount(() => {\\n    const id = setInterval(() => {\\n      msgs(list => [...list, { id: Date.now(), text: '消息 ' + list.length }])\\n    }, 1000)\\n    onUnmount(() => clearInterval(id))\\n  })\\n\\n  // 新消息自动滚到底部\\n  const scrollBottom = () => {\\n    const el = scrollEl()\\n    if (el) el.scrollTop = el.scrollHeight\\n  }\\n\\n  return div({ class: 'chat' },\\n    ul({\\n      ref: e => scrollEl(e),\\n      class: 'chat-body',\\n      style: { height: '300px', overflowY: 'auto' }\\n    },\\n      list(msgs, m => m.id, m => li(null, m.text)),\\n      () => { setTimeout(scrollBottom, 0); return null }\\n    )\\n  )\\n}\\n\\nmount(() => ChatLog(), '#app')",'xuy'),
    ]),`,
"lifecycle")

// ============ ref ============
swap(`    ('core-ref', 'ref', []),`,
`    ('core-ref', 'ref', [
      ('H1','ref'),
      ('P','ref 是一个闭包变量，专门用来保存 DOM 引用。读它返回真实 DOM，写它更新引用。'),
      ('H2','基础用法'),
      ('Code',"import { ref, input, onMount } from 'xunay'\\n\\nconst inputRef = ref()\\n\\ninput({\\n  ref: el => inputRef(el),\\n  placeholder: '输入'\\n})\\n\\nonMount(() => inputRef().focus())",'xuy'),
      ('H2','为什么用函数包装'),
      ('P','ref 返回一个函数：\\n· 调用 r() 读\\n· 调用 r(dom) 写\\n\\n这样避免暴露内部变量，也能保证每次读到的都是最新值。'),
      ('Code',"const r = ref()\\nr()          // 读（null）\\nr(el)        // 写\\nr()          // 读（el）",'xuy'),
      ('H2','ref 不是响应式的'),
      ('Warn','ref 和 signal 不一样——它不是响应式的。写 ref 不会触发 effect，读 ref 也不会订阅。它就是一个简单的变量存储。'),
      ('Code',"const r = ref()\\neffect(() => {\\n  console.log(r())   // ✗ 不会因为 r 变化而重跑\\n})",'xuy'),
      ('H2','ref vs signal'),
      ('Table',['','ref','signal'],[
        ['读','r()','s()'],
        ['写','r(v)','s(v)'],
        ['触发 effect','不','会'],
        ['嵌套在动态里','不重跑','会重跑'],
        ['用途','DOM 引用','状态'],
      ]),
      ('P','简单记：想触发更新用 signal，只想存个值用 ref。'),
      ('H2','什么时候用 ref'),
      ('Ul',
        '拿到 DOM 后 focus / blur',
        '测量元素尺寸（getBoundingClientRect）',
        '滚动控制（scrollTop / scrollIntoView）',
        '第三方库初始化（echarts / mapbox / video）',
        '手动操作 DOM（特殊情况）'),
      ('H2','多个元素共享 ref'),
      ('P','一个 ref 只能存一个值。要存多个用 Map 或对象。'),
      ('Code',"const inputs = {}        // 普通对象\\n// 或\\nconst inputs = new Map()\\n\\nitems.map(i =>\\n  input({\\n    ref: el => inputs[i.id] = el\\n  })\\n)\\n\\n// 之后\\ninputs[42].focus()",'xuy'),
      ('H2','ref 的时机'),
      ('P','ref 回调在元素创建后立即执行，但此时元素还没挂到文档树。要确保挂载后用 onMount。'),
      ('Code',"let el = null\\ndiv({ ref: e => { el = e; console.log('创建') } })\\n// 打印"创建"\\nonMount(() => console.log('挂载', el))\\n// 打印"挂载 <div>",'xuy'),
      ('H2','ref 在列表里'),
      ('P','list 每一项可以有自己的 ref。用 map 存：'),
      ('Code',"import { list, li, ref } from 'xunay'\\n\\nconst itemRefs = new Map()\\n\\nlist(todos, t => t.id, t =>\\n  li({\\n    ref: el => {\\n      if (el) itemRefs.set(t.id, el)\\n      else itemRefs.delete(t.id)\\n    }\\n  }, t.title)\\n)",'xuy'),
      ('H2','ref 在组件间传递'),
      ('P','父组件想访问子组件的 DOM——有两种模式：'),
      ('Code',"// 模式 A：子组件内部处理，父组件不关心\\nfunction FancyInput(props) {\\n  const el = ref()\\n  onMount(() => el().focus())\\n  return input({ ref: e => el(e), ...props })\\n}\\n\\n// 模式 B：父组件显式传入 ref 回调\\nfunction FancyInput({ inputRef, ...props }) {\\n  return input({ ref: inputRef, ...props })\\n}\\n// 用：FancyInput({ inputRef: el => myRef(el) })",'xuy'),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：以为 ref 是响应式的'),
      ('Code',"const r = ref()\\ndiv(null, () => r() ? r().tagName : '未挂载')\\n// ✗ ref 变化不触发这个动态节点重跑",'xuy'),
      ('H3','陷阱 2：在 onMount 之前读'),
      ('Code',"const r = ref()\\ndiv({ ref: e => r(e) })\\nconsole.log(r())   // 立即读：可能是 null（DOM 还没挂载）\\nonMount(() => console.log(r()))   // ✓ 一定非空",'xuy'),
      ('H3','陷阱 3：把 ref 当 signal 传给模板'),
      ('Code',"div({ class: () => r() ? 'ready' : '' })\\n// ✗ 首次求值后就不再更新",'xuy'),
      ('H2','完整示例：自定义滚动条'),
      ('Code',"import { div, ref, signal, onMount, onUnmount, mount } from 'xunay'\\n\\nfunction CustomScroll() {\\n  const scroller = ref()\\n  const content = ref()\\n  const thumbH = signal(50)\\n  const thumbTop = signal(0)\\n\\n  const update = () => {\\n    const s = scroller(), c = content()\\n    if (!s || !c) return\\n    const ratio = s.clientHeight / c.scrollHeight\\n    thumbH(Math.max(30, s.clientHeight * ratio))\\n    const maxTop = s.clientHeight - thumbH()\\n    thumbTop((s.scrollTop / (c.scrollHeight - s.clientHeight)) * maxTop)\\n  }\\n\\n  onMount(() => {\\n    const s = scroller()\\n    s.addEventListener('scroll', update)\\n    window.addEventListener('resize', update)\\n    update()\\n    onUnmount(() => {\\n      s.removeEventListener('scroll', update)\\n      window.removeEventListener('resize', update)\\n    })\\n  })\\n\\n  return div({\\n    ref: e => scroller(e),\\n    class: 'scroll-wrap',\\n    style: { position: 'relative', height: '300px', overflow: 'auto' }\\n  },\\n    div({ ref: e => content(e) },\\n      ...Array.from({ length: 50 }, (_, i) => div(null, '行 ' + i))\\n    ),\\n    div({\\n      class: 'scroll-thumb',\\n      style: () => ({\\n        height: thumbH() + 'px',\\n        transform: 'translateY(' + thumbTop() + 'px)'\\n      })\\n    })\\n  )\\n}\\n\\nmount(() => CustomScroll(), '#app')",'xuy'),
    ]),`,
"ref")

// ============ ctx ============
swap(`    ('core-ctx', 'ctx', []),`,
`    ('core-ctx', 'ctx', [
      ('H1','ctx'),
      ('P','ctx 是"上下文"——把值从祖先传给后代，避免层层传 props（prop drilling）。类似 React 的 Context，但更轻。'),
      ('H2','为什么需要它'),
      ('P','假设 User 数据在最顶层，深层子组件要用——一层层传 props 太啰嗦。ctx 让后代直接从上下文取。'),
      ('Code',"// 不用 ctx\\nfunction App() { return User() }\\nfunction User() { return Layout({ user: userData }) }\\nfunction Layout({ user }) { return Card({ user }) }\\nfunction Card({ user }) { return div(null, user.name) }\\n\\n// 用 ctx\\nconst UserCtx = ctx()\\nfunction App() {\\n  return UserCtx.provide(userData, () => User())\\n}\\nfunction Card() {\\n  const user = UserCtx.get()\\n  return div(null, user.name)\\n}",'xuy'),
      ('H2','创建上下文'),
      ('Code',"import { ctx } from 'xunay'\\n\\n// 创建时给一个默认值\\nconst ThemeCtx = ctx('light')\\nconst UserCtx = ctx(null)\\nconst LocaleCtx = ctx('zh-CN')",'xuy'),
      ('H2','提供值'),
      ('P','.provide(value, fn) 在 fn 执行期间把 value 压入栈，fn 执行完自动弹出。'),
      ('Code',"const ThemeCtx = ctx('light')\\n\\nThemeCtx.provide('dark', () => {\\n  // 这里所有后代读 ThemeCtx.get() 都拿到 'dark'\\n})\\n// 出了 fn 之外，又是 'light'（默认）",'xuy'),
      ('H2','读取值'),
      ('P','.get() 从栈顶往下找最近一次 provide 的值。找不到用默认值。'),
      ('Code',"const ThemeCtx = ctx('light')\\n\\nconsole.log(ThemeCtx.get())   // 'light'\\n\\nThemeCtx.provide('dark', () => {\\n  console.log(ThemeCtx.get())   // 'dark'\\n})\\n\\nconsole.log(ThemeCtx.get())   // 'light'",'xuy'),
      ('H2','完整例子：主题切换'),
      ('Code',"import { ctx, div, button, signal, mount } from 'xunay'\\n\\nconst ThemeCtx = ctx('light')\\n\\nfunction Button() {\\n  const theme = ThemeCtx.get()\\n  return div({\\n    class: 'btn',\\n    style: {\\n      background: theme === 'dark' ? '#333' : '#eee',\\n      color: theme === 'dark' ? '#fff' : '#000'\\n    }\\n  }, '按钮 (' + theme + ')')\\n}\\n\\nfunction Card() {\\n  const theme = ThemeCtx.get()\\n  return div({\\n    style: { padding: '20px', background: theme === 'dark' ? '#222' : '#f5f5f5' }\\n  },\\n    '卡片',\\n    Button(),\\n    Button()\\n  )\\n}\\n\\nmount(() => {\\n  const theme = signal('light')\\n  return div(null,\\n    button({ on: { click: () => theme(theme() === 'dark' ? 'light' : 'dark') } }, '切换主题'),\\n    // 每次 theme 变，都重新 provide——后代读到新值\\n    () => ThemeCtx.provide(theme(), () => Card())\\n  )\\n}, '#app')",'xuy'),
      ('H2','嵌套 provide'),
      ('P','可以嵌套——内层覆盖外层。'),
      ('Code',"const Ctx = ctx('root')\\n\\nCtx.provide('outer', () => {\\n  console.log(Ctx.get())   // 'outer'\\n  Ctx.provide('inner', () => {\\n    console.log(Ctx.get())   // 'inner'\\n  })\\n  console.log(Ctx.get())   // 'outer'\\n})",'xuy'),
      ('H2','和 signal 组合'),
      ('P','ctx 传递的可以是 signal 本身，后代读 signal 就能响应式。'),
      ('Code',"const UserCtx = ctx(null)\\n\\n// 祖先\\nconst user = signal({ name: 'x' })\\nUserCtx.provide(user, () => Card())\\n\\n// 后代\\nfunction Card() {\\n  const user = UserCtx.get()\\n  return div(null, () => user().name)   // ✓ 响应式\\n}",'xuy'),
      ('H2','ctx 的实现原理'),
      ('P','ctx 内部是一个全局栈。provide 时 push，fn 执行后 pop。get 从栈顶往下找。'),
      ('Code',"// 伪代码\\nconst stack = []\\nfunction ctx(defaultValue) {\\n  const id = Symbol()\\n  return {\\n    get() {\\n      for (let i = stack.length - 1; i >= 0; i--)\\n        if (stack[i].id === id) return stack[i].value\\n      return defaultValue\\n    },\\n    provide(value, fn) {\\n      stack.push({ id, value })\\n      try { return fn() } finally { stack.pop() }\\n    }\\n  }\\n}",'js'),
      ('H2','和 React Context 对比'),
      ('Table',['','xunay ctx','React Context'],[
        ['创建','ctx(default)','createContext(default)'],
        ['提供','.provide(v, fn)','<Provider value={v}>'],
        ['读取','.get()','useContext(Ctx)'],
        ['嵌套','自动','自动'],
        ['响应式','传 signal 即可','value 变化触发重渲染'],
        ['作用域','同步执行期','组件树'],
      ]),
      ('H2','常见陷阱'),
      ('H3','陷阱 1：异步里读不到'),
      ('Code',"Ctx.provide('x', async () => {\\n  console.log(Ctx.get())   // 'x'\\n  await sleep(100)\\n  console.log(Ctx.get())   // ✗ 已经退出 provide，读不到 'x'\\n})",'xuy'),
      ('P','ctx 是同步栈。await 之后栈已恢复，读不到当初的值。异步场景用闭包捕获或参数传递。'),
      ('H3','陷阱 2：忘记用返回值'),
      ('Code',"// ✗ 丢掉了返回\\n() => { Ctx.provide('dark', () => Card()) }\\n\\n// ✓ 返回 provide 的结果\\n() => Ctx.provide('dark', () => Card())",'xuy'),
      ('P','在动态节点里，provide 的返回值（渲染结果）必须被返回，否则节点不挂载。'),
      ('H3','陷阱 3：模块顶层 provide'),
      ('Code',"Ctx.provide('x', () => {})   // ✗ 立即执行然后立即返回\\n// 什么也没发生",'xuy'),
      ('H2','完整示例：i18n'),
      ('Code',"import { ctx, div, span, button, signal, mount } from 'xunay'\\n\\nconst dict = {\\n  'zh-CN': { hello: '你好', bye: '再见' },\\n  'en-US': { hello: 'Hello', bye: 'Bye' }\\n}\\n\\nconst I18nCtx = ctx('zh-CN')\\n\\nfunction t(key) {\\n  const locale = I18nCtx.get()\\n  return dict[locale][key] || key\\n}\\n\\nfunction Greeting() {\\n  return div(null,\\n    span(null, t('hello')),\\n    button(null, t('bye'))\\n  )\\n}\\n\\nmount(() => {\\n  const locale = signal('zh-CN')\\n  return div(null,\\n    button({ on: { click: () => locale('zh-CN') } }, '中文'),\\n    button({ on: { click: () => locale('en-US') } }, 'English'),\\n    () => I18nCtx.provide(locale(), () => Greeting())\\n  )\\n}, '#app')",'xuy'),
    ]),`,
"ctx")

writeFileSync(p, s)
console.log("lifecycle / ref / ctx 三篇已填")
