#!/usr/bin/env python3

p = "site/gen-docs.py"
with open(p, 'r', encoding='utf-8') as f:
    s = f.read()

def swap(anchor, replacement, label):
    global s
    if anchor not in s:
        print("未命中:", label)
        return
    s = s.replace(anchor, replacement)

# ============ 10-faq ============
swap("    ('10-faq', '常见问题', []),", r"""    ('10-faq', '常见问题', [
      ('H1','常见问题'),
      ('P','第一次接触 xunay 会遇到的问题，一次说清。'),
      ('H2','为什么读 signal 要加 ()？'),
      ('P','signal 是一个函数。n() 是"调用它读值"，n(1) 是"调用它写值"。加 () 让读和写统一成一种语法——都是函数调用。'),
      ('Code',"const n = signal(0)\nn()     // 读 → 0\nn(1)    // 写 → 1",'xuy'),
      ('P','配合"动态值用函数包"的规则，模板里写成 () => n()——第一个 () 是框架的约定，第二个是 signal 的调用。'),
      ('H2','为什么组件只执行一次？'),
      ('P','因为不需要重复执行。React 每次更新都要重跑组件函数、重建整棵 vnode 树、再 diff。xunay 把"数据变化时做什么"直接交给 effect——组件只负责构建一次 DOM 结构。'),
      ('Code',"function Counter() {\n  const n = signal(0)\n  console.log('初始化')   // 只打印一次\n  return div(null, () => n())   // 这个函数每次都跑\n}",'xuy'),
      ('H2','不用 VDOM 怎么做更新？'),
      ('P','用 effect 精确追踪。当你在 effect 里读 n() 时，n 记录了"谁在读我"。n 变化时，通知那个 effect 重跑——而那个 effect 只改对应节点的 textContent。'),
      ('Code',"// 组件里\nspan(null, () => n())\n\n// 框架内部（伪代码）\neffect(() => {\n  textNode.textContent = String(n())\n})\n// n 变 → effect 重跑 → 只改 textContent",'js'),
      ('H2','为什么不兼容 React？'),
      ('P','不是"做不到"，是"不想做"。兼容 React 意味着保留 VDOM、Hooks 依赖数组、组件重渲染等一堆历史包袱，最终变成另一个 React。xunay 选择从零设计。'),
      ('H2','依赖数组去哪了？'),
      ('P','xunay 用运行时依赖收集——effect 执行时读到哪些 signal，就自动订阅哪些。不用手写，也不会漏。'),
      ('Code',"// React：必须手写依赖\nuseEffect(() => {\n  console.log(a, b)\n}, [a, b])   // 忘了写就是 bug\n\n// XuNay：自动\neffect(() => {\n  console.log(a(), b())\n})",'xuy'),
      ('H2','能在 .xuy 里用普通 JS 吗？'),
      ('P','能。.xuy 就是 JS——所有 JS 语法都能用。唯一区别：标签名（div、span、button）可以当函数直接调用，不用 import。'),
      ('Code',"// app.xuy —— 可以直接写 div(...)\nconst n = signal(0)\nmount(() => div(null, button(null, () => String(n()))), '#app')",'xuy'),
      ('H2','怎么调试？'),
      ('P','用内置 devtools。它会显示所有 signal、effect、请求、日志。'),
      ('Code',"import 'xunay/devtools'\n// 右下角出现悬浮按钮",'xuy'),
      ('H2','性能真有那么快？'),
      ('P','核心更新的量级：'),
      ('Table',['操作','耗时'],[
        ['signal 读','~130ns'],
        ['signal 写（无订阅）','~180ns'],
        ['触发 1 个 effect','~650ns'],
        ['更新 1 个文本节点','~1µs'],
        ['React 更新组件','~50µs ~ 5ms'],
      ]),
      ('P','真实应用里，瓶颈通常在 DOM 和网络，不在 signal。'),
      ('H2','和 Solid / Svelte 有什么区别？'),
      ('Table',['','Solid','Svelte','XuNay'],[
        ['语法','JSX','模板','JS'],
        ['编译','必须','必须','可选'],
        ['运行时','~7KB','~2KB','~4.7KB'],
        ['依赖收集','编译期','编译期','纯运行时'],
        ['学习成本','中','中','低'],
      ]),
      ('P','xunay 的核心差异：不依赖编译，纯运行时。可以直接当 JS 库用，也可以选 .xuy。'),
      ('H2','怎么发请求？'),
      ('P','用原生 fetch + signal。xunay 不发明自己的网络层。'),
      ('Code',"const data = signal(null)\nconst loading = signal(true)\n\nonMount(async () => {\n  try {\n    data(await (await fetch('/api/todos')).json())\n  } finally {\n    loading(false)\n  }\n})",'xuy'),
      ('H2','怎么管理全局状态？'),
      ('P','signal 提到模块顶层就是全局状态。不用 Redux / Pinia。'),
      ('Code',"// store.js\nexport const user = signal(null)\nexport const todos = signal([])\n\n// 组件里\nimport { user } from './store.js'\ndiv(null, () => user() ? user().name : '未登录')",'xuy'),
      ('H2','支持 TypeScript 吗？'),
      ('P','提供类型声明（types/xunay.d.ts）。但 xunay 本身不写 TS——设计哲学里明确"不写 TS"。类型对使用方是可选的。'),
      ('H2','和 jQuery / 原生 DOM 混用？'),
      ('P','可以。xunay 只是包装 DOM 操作，不霸占 document。可以用 ref 拿真实 DOM，交给 jQuery 或原生 API 处理。'),
      ('Code',"const el = ref()\ndiv({ ref: e => el(e) })\n\nonMount(() => {\n  // 交给别的库\n  new SomeLibrary(el())\n})",'xuy'),
      ('H2','生产环境可以用吗？'),
      ('P','代码层面能跑，但生态还在早期。建议：'),
      ('Ul',
        '个人项目 / 内部工具：可以直接用',
        '创业公司 MVP：可以用，配合 Vue 做复杂图表',
        '大型团队 / 关键业务：观望，或用 React / Vue'),
      ('H2','为什么不发布到 npm？'),
      ('P','还没发布。目前是源码引用——把 core/dist 拷贝到项目里，或从 npm 装（等发布）。'),
      ('H2','怎么参与贡献？'),
      ('P','看「贡献指南」。'),
    ]),""", "10-faq")

# ============ 11-design ============
swap("    ('11-design', '设计理念', []),", r"""    ('11-design', '设计理念', [
      ('H1','设计理念'),
      ('P','xunay 的核心是"做减法"——每去掉一层抽象，就少一份认知负担、一次性能损耗、一类边界 bug。'),
      ('H2','五个原则'),
      ('Ul',
        '不发明新语法（.xuy 就是 JS）',
        '不做无用的抽象（只有 signal 和元素）',
        '不保留历史包袱（不兼容 React）',
        '不用编译期魔法（纯运行时依赖收集）',
        '不追求万能（90% 场景够用就好）'),
      ('H2','不做清单'),
      ('Table',['不做','原因'],[
        ['不兼容 React','保留 VDOM 就没法做精确更新'],
        ['不用 TS','类型在框架内部是负担'],
        ['不用 Hooks 链表','Scope 树更简单更可靠'],
        ['不用 Fiber','同步渲染够快，不需要调度'],
        ['不用 diff','精确更新能省掉整个算法'],
        ['不搞分层','一层解决，不堆中间件'],
        ['不做大而全','核心小，功能可选'],
      ]),
      ('H2','为什么是"信号"不是"状态"'),
      ('P','"状态"是值，"信号"是"会通知的值"。区别在于：状态需要框架去比较（diff），信号自己知道什么时候变、谁在听。'),
      ('Code',"// 状态：框架需要遍历对比\nconst state = { n: 0 }\n// ...\n// <div>n = {state.n}</div>   → diff 对比\n\n// 信号：值自己通知\neffect(() => {\n  textNode.textContent = 'n = ' + n()\n})\n// n 变 → 直接调用这个 effect",'xuy'),
      ('H2','为什么"组件只执行一次"'),
      ('P','React 的模型是"状态变 → 重跑组件 → 重建 vnode → diff → 更新 DOM"。这条链上有两次遍历（重建 + diff）都可以省掉。'),
      ('Code',"// React：3 次遍历\n// 1. 组件函数重跑\n// 2. 生成 vnode 树\n// 3. diff 新旧树\n\n// XuNay：0 次遍历\n// 状态变 → effect 直接改 DOM",'xuy'),
      ('H2','为什么"纯运行时"'),
      ('P','编译期优化需要"静态分析代码"——分析不了的情况（动态属性、条件依赖、运行时计算）就退化成运行时。xunay 直接放弃编译期，用最简单的运行时模型。'),
      ('P','好处：'),
      ('Ul',
        '代码就是代码，没有编译魔法',
        '调试时看到的就是执行的',
        '可以直接在浏览器 Console 里跑',
        '不需要构建工具'),
      ('H2','为什么核心这么小'),
      ('P','核心只做一件事：把"数据变"映射到"DOM 变"。UI 组件、动画、表单、SSR 都是可选的，不塞进核心。'),
      ('Table',['模块','gzip'],[
        ['核心','4.7 KB'],
        ['kit（UI 组件）','14.5 KB'],
        ['devtools','10 KB'],
        ['anim','1.3 KB'],
      ]),
      ('P','核心 4.7 KB——比 Preact 略大，比 Solid 小。'),
      ('H2','为什么和别家都不一样'),
      ('Table',['框架','核心思想','代价'],[
        ['React','组件重渲染 + VDOM','概念多、性能一般'],
        ['Vue','编译 + 响应式','需要编译、生态绑定'],
        ['Solid','编译期响应式','必须编译、调试难'],
        ['Svelte','编译 + 无运行时','编译复杂、限制多'],
        ['XuNay','纯运行时响应式','无生态、无编译优化'],
      ]),
      ('H2','有意识的取舍'),
      ('P','xunay 不是"更好的 React"，是"另一条路"。'),
      ('H3','要什么'),
      ('Ul',
        '极简的心智模型',
        '可预测的性能',
        '零编译依赖',
        '可调式的运行时'),
      ('H3','放弃什么'),
      ('Ul',
        '生态（没有第三方组件库）',
        '编译期优化（无 Svelte 那种特化）',
        '调试工具链（Chrome 扩展等）',
        '大规模验证（没人用它做百万用户应用）'),
      ('H2','一句话总结'),
      ('Quote','React 是 2013 年的回答，Vue 是 2014 年的回答，Svelte 是 2016 年的回答。xunay 是现在的回答——用最直接的方式，解决 90% 的前端问题。'),
    ]),""", "11-design")

# ============ 12-changelog ============
swap("    ('12-changelog', '版本历史', []),", r"""    ('12-changelog', '版本历史', [
      ('H1','版本历史'),
      ('H2','v1.0.1'),
      ('P','核心加固与优化。'),
      ('H3','新增'),
      ('Ul',
        'sanitize.js —— HTML 白名单净化',
        'resource.js —— 异步三态助手',
        'model.js —— 表单双向绑定',
        'transition.js —— FLIP 过渡',
        'hydration.js —— SSR 校验',
        'devpanel.js —— 调试面板',
        'errors.js —— 编译器错误提示',
        'vite-plugin-xunay.js —— Vite 插件',
        'types/xunay.d.ts —— 类型声明',
        'test/core.test.js —— core 测试',
        'test/compiler.test.js —— 编译器测试'),
      ('H3','性能'),
      ('Table',['操作','v1.0.0','v1.0.1'],[
        ['signal 读','262ns','128ns'],
        ['signal 写','272ns','183ns'],
        ['触发 effect','988ns','650ns'],
        ['computed 写触发','2528ns','1263ns'],
        ['batch','7212ns','4829ns'],
      ]),
      ('P','signal 读快 2 倍。'),
      ('H3','修复'),
      ('Ul',
        'render.js 探针污染——动态子节点判断时误追踪外层 effect',
        'renderDyn 不跑 onMount——动态节点里 onMount 静默失效',
        'fastUpdate 错误复用——函数子节点被跳过但父节点被判为可复用',
        'example.xuy 参数化模板——裸 tag 引用未定义变量',
        '包体积虚高——kit / devtools 全打进核心'),
      ('H3','包体积'),
      ('Table',['产物','gzip'],[
        ['xunay.esm.js','5.9 KB'],
        ['xunay.min.js','6.2 KB'],
        ['xunay-devtools.min.js','3.9 KB'],
        ['xunay-kit.min.js','14.5 KB'],
        ['xunay-full.min.js','19.4 KB'],
      ]),
      ('H2','v1.0.0'),
      ('H3','核心'),
      ('Ul',
        'Signal 内核——signal / computed / effect / batch',
        '元素渲染——createElement + render + mount',
        '列表——list + key 复用 + fastUpdate',
        '事件委托 / 条件渲染 / Fragment / 生命周期',
        '进阶——ref / ctx / err / lazy / trans / ssr / hydrate / devtool',
        'gzip 4.5KB，零依赖'),
      ('H3','全栈'),
      ('Ul',
        'shared/routes.json 路由唯一真相源',
        '四个后端——Node / Python / Go / C++',
        '统一 RPC 客户端，前端不写 URL',
        '端口配置化（xunay.config.json）',
        '一键切换后端',
        '路由一致性校验'),
      ('H3','工具'),
      ('Ul',
        'bin/create.js —— 脚手架',
        'bin/xuyc.js —— .xuy 构建工具',
        'bin/switch.js —— 后端切换',
        'bin/check-routes.js —— 路由校验',
        'bin/sync-routes.js —— 路由同步',
        'bin/start.sh —— 启动脚本'),
      ('H3','文档'),
      ('Ul',
        '文档站 125 篇（12 组）',
        'Playground 在线编辑器',
        '代码块复制按钮',
        '上一篇 / 下一篇导航'),
      ('H3','示例'),
      ('Ul',
        '计数器 / Todo / 1000 行列表 / 生命周期',
        '完整 Todo / 聊天 / 表格 / 表单验证',
        'myapp 大项目骨架',
        'demo 脚手架示例'),
      ('H2','版本规则'),
      ('Table',['版本','含义'],[
        ['主版本','破坏性变更'],
        ['次版本','新增功能'],
        ['补丁','bug 修复']),
      ('H2','升级指南'),
      ('P','从 v1.0.0 升级到 v1.0.1：'),
      ('Ul',
        '无破坏性变更',
        '可选引入 sanitize / resource 等新模块',
        '旧代码无需改动'),
    ]),""", "12-changelog")

with open(p, 'w', encoding='utf-8') as f:
    f.write(s)
print("10 / 11 / 12 已填")
