plugins { id 'com.android.application' }
android {
    namespace 'com.xunay.filament'
    compileSdk 35
    defaultConfig { applicationId 'com.xunay.filament'; minSdk 24; targetSdk 35; versionCode 1; versionName "1.0" }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
    implementation 'com.google.android.filament:filament-android:1.51.6'
    implementation 'com.google.android.filament:filament-utils-android:1.51.6'
    implementation 'com.google.android.filament:gltfio-android:1.51.6'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
    implementation 'com.google.android.filament:filamat-android:1.51.6'
}